### ISSUE TITLE
Convert Haiku example to work in p5js and the DOM

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#112]
Code is here:  www/examples/HaikuGrammar/HaikuGrammar.pde. 
We need 2 new versions:
1) In p5js, without RiText -- use only p5js drawing methods, e.g text(str, x, y)
2) No canvas or P5js, jQuery is OK if needed, use DOM for rendering
Both should use YAML grammar

**Comment by CyrusSUEN** [comment]
p5js demo here: http://jsbin.com/legoniseru/edit?js,output

Think there is something wrong with:
* [rita-1.0.90.min.js](https://rednoise.org/rita/download/rita-latest.min.js)   (complete, minimized)    [1.6m] from https://rednoise.org/rita/download/index.html

The above demo won't run if I'm using rita-1.0.90.min.js unless switched to rita-1.0.90.js   (complete: lexicon, LTS-rules)    [1.8m].
I thought the 1.6m one is just a minimized version of the 1.8m one.

**Comment by dhowe** [comment]
I don't know what "something is wrong with" means..
Was there an error?

**Comment by CyrusSUEN** [comment]
> Was there an error?

Cannot use RiGrammar object from rita-1.0.90.min.js.

**Comment by dhowe** [comment]
Please include the error message

**Comment by CyrusSUEN** [comment]
When using [rita-1.0.90.min.js](https://rednoise.org/rita/download/rita-latest.min.js) (complete, minimized) [1.6m]
Error from Console:
```
rita-latest.min.js:2 Uncaught ReferenceError: ex is not defined
```

**Comment by dhowe** [comment]
done
