### ISSUE TITLE
Extract TODOs from src/rita.js (and RiTa-java) into GH issues

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#113]
Go through this (long) source file. Whenever you see a TODO, either fix it (if its very simple), or add it as an issue in github. If you are not sure, what it means, mark it as a 'question' and assign it to me.

**Comment by dhowe** [comment]
good

**Comment by dhowe** [comment]
I still see a number of TODOs in the source code. Please go through and either 1) remove if finished, or 2) create a separate issue if needed, and list the # here

Then once I approve the issue (or the completion), remove the TODO from the source

**Comment by dhowe** [comment]
Also do this for Java

**Comment by dhowe** [comment]
status?

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by dhowe** [comment]
Start with rita package (RiTa/java/rita) and rita.js
