### ISSUE TITLE
Need function examples for docs

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#125]
for the following functions:
```
pluralize  
singularize 
tokenize 
getPosTagsInline
```
see inline TODO for more details

**Comment by dhowe** [comment]
please check that this is done? otherwise add the docs...

**Comment by CyrusSUEN** [comment]
Just added the examples: https://github.com/dhowe/RiTa/pull/234
and remove TODO comment: https://github.com/dhowe/RiTaJS/pull/6

Please verify
