### ISSUE TITLE
RiTa.stem("become") returns "becom" instead of "become"

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#129]
RiTa.stem("become", RiTa.LANCASTER)
or RiTa.PORTER, or RiTa.PLING parameter still returns "becom"

Other affected words:
awake
shine

**Comment by CyrusSUEN** [comment]
This is also the reason my PR fails Travis CI
https://travis-ci.org/dhowe/RiTaJS/jobs/67570156

Was it me misusing the stem() or it has to better handle words ending with 'e'?

**Comment by dhowe** [comment]
see my comments in your pull-request

**Comment by dhowe** [comment]
do we have failing tests for this TODO?

**Comment by CyrusSUEN** [comment]
> do we have failing tests for this TODO?

Yes. This PR https://github.com/dhowe/RiTaJS/pull/50 is still failing.
Do not merge yet.

**Comment by dhowe** [comment]
I mean, do we have js tests in the repo that fail because of this error? We need these before attempting to fix it. If so, please provide a filename and line#.

**Comment by CyrusSUEN** [comment]
No test fails.
```RiTaJS/test/RiTa-tests.html```
818 tests of 818 passed, 0 failed.

Also no other js tests fail except of course the KnownIssues-tests.

**Comment by dhowe** [comment]
We (always) need tests before attempting to fix something -- otherwise we don't know when it is fixed.
Please add the tests you have been using to rita.test.RiTaTest.java. Then try to find a case where an unstemmed verb fails. For example:

  String stem = RiTa.getPresentParticiple("ran"); // should be 'running'
or
  String stem = RiTa.getPresentParticiple("learnt"); // should be 'learning'

**Comment by CyrusSUEN** [comment]
Strange. This is the test from src/rita/test/RiTaTest.java line1428
```java  
  @Test
  public void testStemString()
  {
    equal(RiTa.stem("cakes"), "cake");

    String[] tests = { "run", "runs", "running" };
    for (int i = 0; i < tests.length; i++)
    {
      equal(RiTa.stem(tests[i]), "run");
    }

    equal(RiTa.stem("gases"), "gase");
    equal(RiTa.stem("buses"), "buse");
    equal(RiTa.stem("happiness"), "happi");
    equal(RiTa.stem("terrible"), "terribl");

    String test = "Stemming is funnier than a bummer";
    String result = "Stem is funnier than a bummer";
    //System.out.println("testStemString: " + RiTa.stem(test));
    equal(RiTa.stem(test), result);
  }
```

Seems like it has been already ignoring input ending with 'e' and 's':
```
    equal(RiTa.stem("gases"), "gase");
    equal(RiTa.stem("buses"), "buse");
    equal(RiTa.stem("happiness"), "happi");
    equal(RiTa.stem("terrible"), "terribl");
```

Don't think my new test cases will do something different
```
    equal(RiTa.stem("become"), "become");
    equal(RiTa.stem("awake"), "awake");
    equal(RiTa.stem("shine"), "shine");
```

**Comment by dhowe** [comment]
We are talking about RiTa.getPresentParticiple() and RiTa.getPastParticiple(), no?

**Comment by CyrusSUEN** [comment]
> We are talking about RiTa.getPresentParticiple() and RiTa.getPastParticiple(), no?

I was invesitgating the RiTa.getPresentParticiple() and RiTa.getPastParticiple() that led me to this ticket.
It was my bad that I didn't realize a stem may not be a real word.

And the other problem of this ticket was that I wasn't calling the Pling stemmer correctly.
This is just for the RiTa Java version:
```java
RiTa.stem("become", RiTa.PLING);
```

This is RiTaJS version:
```js
RiTa.stem("become", 'Pling');
```
RiTa.PLING is not a valid parameter in RiTaJS.

I think we should update [the reference page](http://rednoise.org/rita/reference/RiTa/RiTa.stem/index.html) informing this difference and this ticket can be closed.
