### ISSUE TITLE
Remove all plurals from rita_dict.js

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#131]

**Comment by dhowe** [comment]
In progress: see java -> rita.docgen.DictFromCMU

**Comment by cqx931** [comment]
Errors:

Module: RiLexicon Test: testSize
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:44:19)

Module: RiLexicon Test: testContainsWord
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:50:12)

Module: RiLexicon Test: testIsNoun
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:288:12)

Module: RiLexicon Test: testIsNoun
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:289:12)

Module: RiLexicon Test: testIsNoun
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:291:12)

Module: RiLexicon Test: testSimilarByLetter
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:569:15)
Actual value:
[ 'ace', 'dice', 'iced', 'icy', 'ire', 'lice', 'nice', 'rice', 'vice' ]
Expected value:
[ 'ace',
  'dice',
  'iced',
  'icy',
  'ire',
  'lice',
  'mice',
  'nice',
  'rice',
  'vice' ]

Module: RiLexicon Test: testSimilarByLetter
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:572:15)
Actual value:
[ 'ace', 'dice', 'iced', 'icy', 'ire', 'lice', 'nice', 'rice', 'vice' ]
Expected value:
[ 'ace',
  'dice',
  'iced',
  'icy',
  'ire',
  'lice',
  'mice',
  'nice',
  'rice',
  'vice' ]

Module: RiLexicon Test: testSuperstrings
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:673:5)
Actual value:
[ 'supermarket' ]
Expected value:
[ 'supermarket', 'supermarkets' ]

Module: RiLexicon Test: testSuperstrings
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:677:5)
Actual value:
[ 'impunity',
  'punish',
  'punishable',
  'punished',
  'punishes',
  'punishing',
  'punishment',
  'punitive',
  'unpunished' ]
Expected value:
[ 'impunity',
  'punish',
  'punishable',
  'punished',
  'punishes',
  'punishing',
  'punishment',
  'punishments',
  'punitive',
  'unpunished' ]

Module: RiLexicon Test: RiLexicon-gets
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:857:5)
Actual value:

Expected value:
ae/b-er/ey/sh-ah-n-z

Module: RiLexicon Test: RiLexicon-gets
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:860:5)
Actual value:

Expected value:
ae-b-er-ey-sh-ah-n-z

Module: RiLexicon Test: RiLexicon-gets
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiLexicon-tests.js:863:5)
Actual value:

Expected value:
0/0/1/0

**Comment by dhowe** [comment]
so lets try a test with isNoun()
in rilexicon.js, try changing it to be:

````js
  isNoun: function(word) {

    var result = this._checkType(word, PosTagger.NOUNS);
    if (!result) {
      var singular = RiTa.singularize(word);
      if (singular !== word) {
        result = this._checkType(singular, PosTagger.NOUNS);
        result && console.log('found plural noun: '+word+' ('+singular+')');
      }
    }
    return result;
  },

**Comment by cqx931** [comment]
New Tests for plurals

RiTa-tests
testGetPhonemes

      var result = RiTa.getPhonemes("flowers");
      var answer = "f-l-aw-er-z";
      equal(result, answer);

      var result = RiTa.getPhonemes("mice");
      var answer = "m-ay-s";
      equal(result, answer);

testGetPosTags

      var result = RiTa.getPosTags("teeth");
      var answer = ["nns"];
      deepEqual(result, answer);

testGetPosTagsInline

      var result = RiTa.getPosTagsInline("teeth");
      var answer = "teeth/nns";
      deepEqual(result, answer);


RiString

testPos

    rs = new RiString("teeth");
    result = rs.pos();
    deepEqual(result, [“nns"]);

testPosAt

    rs = new RiString("She bought a few knives.”);
    result = rs.posAt(4);
    equal("nns", result);

testGet
    var rs = RiString("Tomatoes and apricots").analyze();
    ok(rs);
    ok(rs.features());

    if (noLexicon()) return;

    var ph = rs.get(RiTa.PHONEMES);
    var sy = rs.get(RiTa.SYLLABLES);
    var st = rs.get(RiTa.STRESSES);
    ok(ph && sy && st);


    equal(ph, "t-ah-m-ey-t-ow-z ae-n-d ae-p-r-ah-k-aa-t-s");
    equal(sy, "t-ah/m-ey/t-ow-z ae-n-d ae/p-r-ah/k-aa-t-s");
    equal(st, "0/1/0 1 1/0/0”);


testAnalyze
   
 features = RiString("Tomatoes and apricots").analyze().features();
    ok(features);
    equal(features.phonemes, "t-ah-m-ey-t-ow-z ae-n-d ae-p-r-ah-k-aa-t-s");
    equal(features.syllables, "t-ah/m-ey/t-ow-z ae-n-d ae/p-r-ah/k-aa-t-s");
    equal(features.stresses, "0/1/0 1 1/0/0");

**Comment by dhowe** [comment]
Looks good. If all tests are passing, then please submit a PR (for RiTaJS only)...

**Comment by dhowe** [comment]
@cqx931 where do we stand on this ticket?

**Comment by cqx931** [comment]
I think it shall be this commit https://github.com/dhowe/RiTa/commit/069c859910e4d854bdb5b2e9d8ff4776721a2844
The plurals are removed, a few test cases have been added

**Comment by dhowe** [comment]
can be closed?

**Comment by cqx931** [comment]
yes
