### ISSUE TITLE
Reference CSS seems to be broken (page background is purple)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#138]
![screen shot 2015-06-25 at 7 38 05 pm](https://cloud.githubusercontent.com/assets/737638/8353554/c202daa6-1b71-11e5-9335-70d95e38efab.png)

**Comment by cqx931** [comment]
It seems to work when I look from here
http://lab-lamp.scm.cityu.edu.hk/~qianxchen2/RiTa/reference/RiWordNet/getSynset/index.php

![2015-06-26 9 38 56 pm](https://cloud.githubusercontent.com/assets/3056154/8378410/e407aa48-1c4b-11e5-8303-9e0a2235b4f7.png)

**Comment by dhowe** [comment]
I see. But we need it to work also from within the www/reference directory... this is what people get when they download the Processing edition or the node.js edition.  I suppose we could change this if necessary, but better if we can figure out a way to support both (plain html for download of reference-only), and php for the website itself

**Comment by cqx931** [comment]
The css was caused by the html template... I just tried to change the html template and it works fine like this:
![2015-06-26 10 30 03 pm](https://cloud.githubusercontent.com/assets/3056154/8379548/4eedeea6-1c53-11e5-8d74-77285a94a244.png)
If this is ok, I will push it later.
And in this case, will all the webpages within github repository stay html, while the real website use php?
And will the plain html for download also use the new design?

**Comment by dhowe** [comment]
Well, for the repository (which gets packed into the zip files), we only care about the reference, not the rest of the site. So we would need an html and php version of the reference, and just php for everything else. Alternatively we could include a single index.html file in the zips, which just has links to the online (php) versions. Which seems easier/better ?

**Comment by cqx931** [comment]
well, I think an index.html that links back to the online version should be the most easiest way to keep everything updated.

**Comment by dhowe** [comment]
sounds good. can you make it so?

**Comment by cqx931** [comment]
Sure.So it will be the index.html for the whole website, right? And should I delete other contents of the website or keep them staying there first?

**Comment by dhowe** [comment]
No, just the reference/index.html, but the links inside should go to the correct reference pages, but on the web…
