### ISSUE TITLE
Remove RiWordNet function list from /RiTa/www/reference/index.html

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#139]
to create the 4 column layour that we discussed for the reference sections:
-- move the list of RiWordNet functions to bottom of RiWordNet.html (similar to RiText)

![screen shot 2015-06-25 at 8 00 32 pm](https://cloud.githubusercontent.com/assets/737638/8353871/520d2a2c-1b75-11e5-99e0-3b6ccff1b65c.png)

**Comment by cqx931** [comment]
Updated
http://lab-lamp.scm.cityu.edu.hk/~qianxchen2/RiTa/reference/index.php

**Comment by dhowe** [comment]
Do you see how RiText is (with the function list at the bottom of RiText.html, but not on index.html)? This is how RiWordNet should be as well...

**Comment by cqx931** [comment]
oh..I see...It should be ok right now.
