### ISSUE TITLE
Check/fix stemming issues

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#144]
Java:  rita.test.RiTaTest
JS:  RiTaJS/test/RiTa-tests.js

Determine current state of 3 stemmers in each of Java and JS (total 6)

Check our stemmer tests in (Java/JS) for Lancaster/Porter against this page: http://text-processing.com/demo/stem/. Figure out if Porter or Lancaster is working better...

Install Pling Stemmer (Java) and verify that our tests are correct http://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/javatools/

Make sure same tests are in both Java/JS

**Comment by CyrusSUEN** [comment]
> Install Pling Stemmer (Java) and verify that our tests are correct http://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/javatools/

Everything looks good.
![screen shot 2015-07-07 at 4 58 24 pm](https://cloud.githubusercontent.com/assets/2461812/8542599/6d6dbbf8-24c9-11e5-9936-b8bbcb3e2a47.png)

And I've just discovered that Pling Stemmer does NOT process words ending with 'ing' by observing the results from the above tool (Pling Stemmer (Java)). 

Modified the test case to suit this behaviour: https://github.com/dhowe/RiTa/pull/146

**Comment by CyrusSUEN** [comment]
> Check our stemmer tests in (Java/JS) for Lancaster/Porter against this page: http://text-processing.com/demo/stem/. Figure out if Porter or Lancaster is working better...

Found an answer on StackOverFlow:
[What are the major differences and benefits of Porter and Lancaster Stemming algorithms](http://stackoverflow.com/questions/10554052/what-are-the-major-differences-and-benefits-of-porter-and-lancaster-stemming-alg)

Lancaster was considered too aggressive to be used.
The answer stated that Snowball is preferred and then Porter 2 or Porter.

**Comment by CyrusSUEN** [comment]
> Make sure same tests are in both Java/JS

Synced the test cases of RiTaJS with the ones from RiTa: https://github.com/dhowe/RiTaJS/pull/54

**Comment by dhowe** [comment]
see  #148
