### ISSUE TITLE
Modernizr style html interface for downloading individual components

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#145]
http://modernizr.com/download/

### Prebuilt 
- rita-core-latest.js (size)
- rita-full-latest.js (size)

### Roll-your-own
- [x] RiMarkov (size)
- [ ] RiGrammar (size)
- [ ] RiLexicon (size)
- [ ] RiLetterToSound (size)
- [ ] RiText (deprecated) (size)

**Comment by cqx931** [comment]
Mock-up
<img width="483" alt="2015-07-06 7 58 57 am" src="https://cloud.githubusercontent.com/assets/3056154/8514009/e579e006-23b4-11e5-9ea2-681d294ced4c.png">

http://lab-lamp.scm.cityu.edu.hk/~qianxchen2/rita/download.php

**Comment by dhowe** [comment]
Looks good. You can go ahead and add this to the download-page as html, but leave it commented out,  until I have time to do the back-end work...

**Comment by cqx931** [comment]
when you say "add as html", do you mean creating a new download.html and comment this out? Since right now in the web folder there is no html files.

**Comment by dhowe** [comment]
correct (it will just look like a blank template page) -- what is left for the website?

**Comment by cqx931** [comment]
the php link problem for the header

**Comment by dhowe** [comment]
ahh, i thought we solved that, no? is there a ticket?

**Comment by cqx931** [comment]
I see no ticket so far, this is where we were last time:
<img width="409" alt="2015-07-12 1 40 23 pm" src="https://cloud.githubusercontent.com/assets/3056154/8636555/a07dd64c-289b-11e5-9f98-d6f7d8735c66.png">

**Comment by dhowe** [comment]
ok, so if you've done this already (using the one variable), please create a ticket assigned to me with this task of fixing it
