### ISSUE TITLE
Test the new Porter2 stemmer and log the results/differences below

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#148]
It is enabled now instead of the old (Porter1) stemmer

**Comment by CyrusSUEN** [comment]
Porter 2 pass the original Porter (1) test case in RiTaTest.java.

And it has less than 5% difference and compared to Porter 1 in sampled words from and according to this page:
http://snowball.tartarus.org/algorithms/english/stemmer.html

> To begin with, here is the basic algorithm without reference to the exceptional forms. An exact comparison with the Porter algorithm needs to be done quite carefully if done at all. Here we indicate by * points of departure, and by + additional features. In the sample vocabulary, Porter and Porter2 stem slightly under 5% of words to different forms.
