### ISSUE TITLE
Remove jquery from website?

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#152]
Curious if we can remove jquery from the website? Currently it is only used a couple of times, referenced from web/js/main.js. 

Only if its easy...

**Comment by cqx931** [comment]
You mean totally don't use jquery?
Right now only the auto hide/show of "fork me on github" is done by jquery as well as the toggle menu for mobile. Using css to do these two should be possible but the movements will not be that smooth...

**Comment by dhowe** [comment]
we can use JS, not only CSS -- the point is to avoid the large download for one or two features, but lets wait til we can discuss in person and look at the mobile version
on hold
