### ISSUE TITLE
RiTa.minEditDistance tests (2) are failing

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#155]
File is rita.test.RiTaTest.java (line 1901). Uncomment the 2 tests, then check/fix.

![screen shot 2015-07-22 at 8 34 41 pm](https://cloud.githubusercontent.com/assets/737638/8825360/1c2b9780-30b1-11e5-96e3-9b1345fbc2a7.png)

**Comment by CyrusSUEN** [comment]
please verify: https://github.com/dhowe/RiTa/pull/159
