### ISSUE TITLE
Better tests for 3 new RiTa functions

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#156]
Tests are either missing or incomplete:

In Java and JS:
RiTa.concordance()
RiTa.kwic()
RiTa.minEditDistance();

Also, generate and check docs (via ant:make.docs)

**Comment by CyrusSUEN** [comment]
JS version PR: https://github.com/dhowe/RiTa/pull/164

**Comment by CyrusSUEN** [comment]
JS version PR
RiTa repo: https://github.com/dhowe/RiTa/pull/168
RiTaJS repo: https://github.com/dhowe/RiTaJS/pull/58
