### ISSUE TITLE
Port rita.examples.KWIKmodel.java to p5js/DOM

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#157]
And allow user to enter the keyword in an html text input box

![screen shot 2015-07-23 at 1 26 39 pm](https://cloud.githubusercontent.com/assets/737638/8843698/82691292-313e-11e5-88bb-19bc46196f56.png)

**Comment by CyrusSUEN** [comment]
rita.examples.KWIKmodel.java cannot be found.

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/RiTaJS/pull/59
