### ISSUE TITLE
Finish implementing and test RiTranslator 

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#16]

**Comment by dhowe** [comment]
Next: figure out which of the methods we have implemented in GoogleTranslator are available through the (pay) GoogleTranslateAPI

**Comment by CyrusSUEN** [comment]
Don't think there is a public Google Dictionary API.
There are many people requesting on Google Code for the public API as well.
https://code.google.com/p/google-ajax-apis/issues/detail?id=16

According to the javadoc from paid Google Translate service
https://developers.google.com/resources/api-libraries/documentation/translate/v2/java/latest/
I believe we only have the translate() from the paid Google Translate service.
While someone said that there is a hidden Google Dictionary API and it has to be paid to get it work.
http://stackoverflow.com/questions/22329810/google-dictionary-api-not-working-is-there-another-solution

There are 2 free alternatives to Google Dictionary though

http://google-dictionary.so8848.com/meaning?word=test
definitions(); 
examples();

And https://glosbe.com/a-api
definitions(); 
example();
synonyms();

**Comment by dhowe** [comment]
This appears to be the Java API: http://google-translate-api-v2-java.googlecode.com/svn/trunk/resources/latest-javadoc/index.html

**Comment by CyrusSUEN** [comment]
Not sure why there are 2 Java API.
I found mine from https://developers.google.com/api-client-library/java/apis/translate/v2

Anyway I can't seem to find anything except translate() method from the link you provided.

**Comment by dhowe** [comment]
Agreed.

**Comment by dhowe** [comment]
done
