### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#160]
https://travis-ci.org/dhowe/RiTa

```
BUILD FAILED
/home/travis/build/dhowe/RiTa/resources/build.xml:177: /home/travis/build/dhowe/RiTa/web/examples does not exist.
Total time: 1 second
The command "ant" exited with 1.
```

**Comment by dhowe** [comment]
why is it failing?

**Comment by CyrusSUEN** [comment]
> why is it failing?

It has failed since https://github.com/dhowe/RiTa/commit/1a27b7f5b1725571b8ce3834283fe625c25d66c7
I'm looking for a fix.

**Comment by dhowe** [comment]
can this be closed?

**Comment by CyrusSUEN** [comment]
> can this be closed?

I think so. After https://github.com/dhowe/RiTa/pull/162 the failing has stopped.
