### ISSUE TITLE
RiTa.kwic() returns duplicate results when target word appears more than once within wordCount

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#169]
To reproduce, set the RiTaJS canvas width to 4000px in the example of KWIKmodel (p5js) or the DIV height to 4000px in KWIKmodel (dom) and then search for the word 'door'.
Here is the result:
![1](https://cloud.githubusercontent.com/assets/2461812/9015581/7ab7c2e0-37fc-11e5-96fb-acb3dadfce15.png)

The original text from Line 1879 and 1880 of kafka.txt:
```
immediate notice."  With that, he took hold of the door
handle and slammed the door.
```

If I set the wordCount to 4 in opts, it looks correct:
![2](https://cloud.githubusercontent.com/assets/2461812/9015746/9b83df6c-37fd-11e5-92b3-83d9dbd9e827.png)

Is this a bug or am I misusing kwic()?

**Comment by dhowe** [comment]
Appears to be a bug, please investigate...

**Comment by CyrusSUEN** [comment]
> does this happen in both Java and JS

Yes. 
Here is the console msg from the KWIKmodel.java
```
he took hold of the door handle and slammed the door
door handle and slammed the door. Gregor's father staggered back
```

But I think this is because of the misuse of split() which returns at the first occurrence of the word.
We should only split the sentence in the middle i.e. at the value of wordCount. But then we have to use tokenize() to find the word in the center of the sentence.

**Comment by dhowe** [comment]
please link directly to the specific line # when mentioning code like this

**Comment by CyrusSUEN** [comment]
> link directly to the specific line #

Line 33 and 34 of KWIKmodel.java
```java
      System.out.println(display[i]);
      String[] parts = display[i].split(word);
```

The above text is captured from Eclipse Console (at the very bottom) when the keyword is "door".

**Comment by dhowe** [comment]
LINK to the specific line
something like:
https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L1052-L1155

**Comment by CyrusSUEN** [comment]
> LINK to the specific line in the repo

Line 33 and 34 of KWIKmodel.java
```java
      System.out.println(display[i]);
      String[] parts = display[i].split(word);
```
is from https://github.com/dhowe/RiTa/blob/master/java/rita/render/examples/KWIKmodel.java#L33-L34

The following part is from the very bottom part of the console of Eclipse when the keyword is "door".
```
he took hold of the door handle and slammed the door
door handle and slammed the door. Gregor's father staggered back
```

**Comment by dhowe** [comment]
As always, make a failing test, and add it below.

**Comment by dhowe** [comment]
What is the status?

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
Please verify: https://github.com/dhowe/RiTa/pull/305

**Comment by CyrusSUEN** [comment]
PR for RiTaJS: https://github.com/dhowe/RiTaJS/pull/22
