### ISSUE TITLE
Compatibility with Processing 3.0

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#183]

**Comment by CyrusSUEN** [comment]
- [x]  run some basic tests 
- [ ] then make sure our code compiles against the new core.jar (3.0)
- [ ] that our unit tests still pass

**Comment by CyrusSUEN** [comment]
> Library authors, now is the time to reduce your reliance on AWT! In 3.0, we're moving away from AWT in a big way (here's why). Any library features that require AWT should be treated with suspicion. Modes and Tools can still use AWT, but the OpenGL renderers (P2D and P3D) and the upcoming FX2D renderer don't use AWT at all.

> This is one reason we built the processing.event classes in 2.x, and have been removing spurious AWT usage from the core API, documentation, and examples.)
> The other reason is that we can't rely on AWT features when targeting JavaScript or Android, so it was encouraging bad habits.

Found 2 affected java classes using AWT features:
java/rita/render/RiGrammarEditor.java
java/rita/render/RiEditorWindow.java

**Comment by dhowe** [comment]
For now you can just exclude these from the ant build...

**Comment by dhowe** [comment]
I've removed these from RiTa/java -- please continue this ticket

**Comment by CyrusSUEN** [comment]
tested on Processing 3.0b5
pass all the examples from RiTa library (RiTa-1.0.95.zip](https://rednoise.org/rita/download/RiTa-latest.zip)
pass all the examples from RiTa library RiTa-1.0.96.zip generated by ant build 

Tried ant build with core-2.2.1.jar and core-3.0.jar from Processing and the RiTa library generated can all pass the test.

But one interesting thing is that even if I removed core-3.0.jar and its reference from the Eclipse project and .classpath, Ant build could still build the library that passes all the test although Eclipse indicated that there were many error.
![screen shot 2015-09-11 at 1 33 08 am](https://cloud.githubusercontent.com/assets/2461812/9795779/3c4bf82a-5825-11e5-81e5-97da66a274b6.png)

**Comment by dhowe** [comment]
Except for RiText and the rita.render package, there should be no other errors. I've moved KWIKModel.java to the render package. Once v1.1 is ready, we can test this again...

**Comment by CyrusSUEN** [comment]
[RiTa](http://rednoise.org/~dhowe/ftp/RiTa-1.1.0.zip) examples tested on Processing 3.0 Beta 5

All examples work but there is a warning when 2 examples windows are opened.
To reproduce:
1. Open HaikuGrammar.pde
2. Open Kafgenstein.pde
3. Warning messages appear in the Console area of the previous Processing window 
![screen shot 2015-09-18 at 5 19 44 pm](https://cloud.githubusercontent.com/assets/2461812/9956179/6386fa2a-5e29-11e5-8e5d-356ebeb602ce.png)


```
[INFO] RiTa.version [1.1.0]
The Editor class has moved to the processing.app.ui package in Processing 3
The Editor class has moved to the processing.app.ui package in Processing 3
"Applet Export and Signer" is not compatible with this version of Processing
"Color Selector Plus" is not compatible with this version of Processing
"Sketch Outline" is not compatible with this version of Processing
"Speed Tool" is not compatible with this version of Processing
"SvgExe" is not compatible with this version of Processing
```

**Comment by dhowe** [comment]
Are you using a fresh install of Processsing 3.0?

**Comment by CyrusSUEN** [comment]
> Are you using a fresh install of Processsing 3.0?

Tested on Mac. 
Downloaded and moved Processing3.0.app to Application folder and then put RiTa library in the sketch path

Just found that Processing 3.0 Beta 6 is out. I will delete and the sketch folder and start fresh to test again.

**Comment by CyrusSUEN** [comment]
No problem on Processing 3.0 Beta 6 after I delete the sketch folder (after a fresh installation).

**Comment by dhowe** [comment]
Can we update the documentation for the WordNet sketches to CLEARLY state that a local WordNet is required...

**Comment by CyrusSUEN** [comment]
> update the documentation for the WordNet sketches to CLEARLY state that a local WordNet is required

Given there is mentioning of WordNet in the source code comment, I think we should try try and catch to print friendlier message in the console.
Created a ticket for this: https://github.com/dhowe/RiTa/issues/194

**Comment by CyrusSUEN** [comment]
Can this be closed?
