### ISSUE TITLE
Handle all KnownIssues tests (Java & JS)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#186]
Either solve or create a new ticket for each issues. If a new ticket is created, leave a comment in the KnownIssues with the ticket #

**Comment by dhowe** [comment]
status?

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
Handled testTokenizeAndBack and testUntokenize in RiTaJS's known issues: https://github.com/dhowe/RiTa/issues/250
Porting the fix and new test cases to RiTa Java.
