### ISSUE TITLE
Optimize tests/RiLexicon-tests.js

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#187]
This test is currently taking ~40 seconds when running outside of the browser (headlessly in PhantomJS). Please profile and propose some steps for reducing the time.

**Comment by CyrusSUEN** [comment]
It takes me only ~8s to run in gulp test (commented out other tests except RiLexicon) and ~5s on Safari browser.

Can I know how did you run it headlessly?
I can profile and try to find out the bottleneck in my case but that might not also be the bottleneck for costing it 40s.

**Comment by dhowe** [comment]
> On 11 Sep, 2015, at 4:27 am, Cyrus S <notifications@github.com> wrote:
> 
> It takes me only ~8s to run in gulp test (commented out other tests except RiLexicon) and ~5s on Safari browser.
> 
They run in about 6 sec for me in the browser… the problem is from gulp, where they take over 30 sec
> Can I know how did you run it headlessly?
> 

$ gulp test --name RiLexicon
[09:05:45] Starting 'clean'...
[09:05:45] Finished 'clean' after 9.07 ms
[09:05:45] Starting 'build'...
[INFO] Writing [ rita.js, rita.min.js ] to dist
[09:05:54] Finished 'build' after 9.26 s
[09:05:54] Starting 'test'...
[INFO] Testing test/RiLexicon-tests
[INFO] RiTaJS.version [1.0.98]
[INFO] Testing RiLexicon
done

Global summary:
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 34    │ 389        │ 0      │ 389    │ 31596   │
└───────┴───────┴────────────┴────────┴────────┴─────────┘
> I can profile and try to find out the bottleneck in my case but that might not also be the bottleneck for costing it 40s.
> 
Sure, but better make sure you can recreate the issue first (pull and retry)

**Comment by CyrusSUEN** [comment]
I am able to reproduce the problem. That is to run gulp test in RiTa/js repo instead of RiTaJS repo.

And found 3 test cases that take the most of the time:
testSimilarByLetter
testSimilarBySound
testSimilarBySoundAndLetter
Removing these 3 and the running time will be down to ~7 seconds in RiTa/js.

-------------------

Also tried profiling in the browser:
All tests completed in 5639 milliseconds when tested in Safari
Most of the tests are under 50ms.

testSimilarByLetter takes 787.85703000176ms
testSimilarBySound takes 1587.1154020023823ms 
testSimilarBySoundAndLetter takes 1381.6399839997757ms 

Or if I reduce the number of tests to just one:
similarByLetter() takes ~170ms
similarBySound() takes ~200ms 
similarBySoundAndLetter() takes ~250ms

**Comment by dhowe** [comment]
please pull and repeat your tests, see if there is any change…

**Comment by CyrusSUEN** [comment]
> pull and repeat your tests

No change.

Just pulled 0a2841dadb1d98747480981ea6a6e951483e56c9.
original test: 48821
reduced test (minus the above 3 tests): 8303

**Comment by dhowe** [comment]
profile those 3 functions and see what is the bottleneck...

**Comment by CyrusSUEN** [comment]
Take the following for example from testSimilarByLetter
```js
var result = lex.similarByLetter("banana");
deepEqual(result, ["banal", "bonanza", "cabana", "lantana", "manna", "wanna"]);
```

Running gulp test in RiTaJS repo measures 160ms while in RiTa/js it takes 2135ms.

When dived deep into rita.js file to look for the method similarByLetter():
```js 
    console.log("testSimilarByLetter started");
    var p0 = [];

    for (var entry in RiLexicon.data) {

        if (entry.length < minLen) continue;

        if (preserveLength && (entry.length != inputLen)) continue;

        if (entry == input || entry == inputS || entry == inputES) continue;

        var t0 = Date.now();
        med = MinEditDist.computeRaw(entry, input);
        var t1 = Date.now();
        p0.push(t1 - t0);

        // we found something even closer
        if (med >= minAllowedDist && med < minVal) {

            minVal = med;
            result = [entry];
        }

        // we have another best to add
        else if (med == minVal) {

            result.push(entry);
        }
    }

    var sum = 0;
    for (var i = 0; i < p0.length; i++) {
        sum += parseInt(p0[i]);
    }
    console.log("Total iteration: " + sum);
    console.log("Avg iteration " + (sum / p0.length));

    return result;
```
The total time of ```MinEditDist.computeRaw(entry, input);``` in the for-loop from RiTaJS accounts for 113ms
the same operation takes 2012ms in RiTa/js.

On avg iteration it's 0.0033870871050896228 vs 0.060308135003896646ms.
That's 17 times longer.

Actually even the parts before it is much slower.
This part
```js
        if (entry.length < minLen) continue;

        if (preserveLength && (entry.length != inputLen)) continue;

        if (entry == input || entry == inputS || entry == inputES) continue;
```
accumulates only 2ms in the for-loop in RiTaJS while it does 38ms in RiTa/js

**Comment by dhowe** [comment]
I'm confused -- why are you comparing to RiTaJS? I thought the comparison was browser vs headless?

**Comment by CyrusSUEN** [comment]
Done. Closing
