### ISSUE TITLE
Rhyming problems

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#192]
testRhyming() from KnownIssuesTest.java

```java
  @Test
  public void testRhyming()
  {
    RiLexicon lex = new RiLexicon();
    String[] result = lex.rhymes("savage");
    String[] answer = new String[] { "ravage", "disparage", "cabbage", "etc" };
    deepEqual(answer, result);
  }
```

And the method for checking rhyming
```java
  /**
   * Returns the rhymes for a given word or null if none found.
   * <P>
   * Two words rhyme if their final stressed vowel and all following phonemes
   * are identical.
   */
  private void rhymes(String input, Set result) {
    String lss = lastStressedPhoneToEnd(input, false); // TODO: change to true !
    if (lss == null)
      return; // no result

    for (Iterator it = lexicalData().keySet().iterator(); it.hasNext();) {
      String cand = (String) it.next();

      if (cand.equals(input))
	continue;

      String chck = lexImpl.getRawPhones(cand);
      if (chck != null && chck.endsWith(lss))
	result.add(cand);
    }
  }
```

By looking up rita_dict.js
'savage': ['s-ae1-v ax-jh','jj nn'],
'ravage': ['r-ae1-v ih-jh','vb'],
'disparage': ['d-ih-s p-eh1-r ih-jh','vb'],
'cabbage': ['k-ae1-b ax-jh','nn'],

The above 2 words are compared using builtin String method from Java endsWith(). And the result is false because "'r-ae1-v ih-jh" does not end with "ae1-v ax-jh".

The main difference is "ax" and "ih" here.

But when I looked up the dictionary their phonetics should be as follow:
savage: ˈsavɪdʒ 
ravage: ˈravɪdʒ

And by looking up [IPA/CMU/TIMIT phone mappings](http://roch.sdsu.edu/cs682/IPA-CMU-TIMIT-Phoneset.pdf)
"ɪdʒ" should be translated to "ih-jh" instead of "ax-jh" in TIMIT speech for the word "savage".

After correcting the "savage" in the dictionary ```target\classes\rita\rita_dict.js```
It returned "ravage" when doing RiLexicon.rhymes("savage").

I do not create a PR because "disparage" and "cabbage" still failed to return. 
For "cabbage"
"ae1-v ax-jh" vs "ae1-b ax-jh" or
"ae1-v ih-jh" vs "ae1-b ih-jh" after correcting their TIMIT speeches
The difference is '-v' vs '-b'.

In fact, I think we should only compare this part /ɪdʒ/ from /ˈsavɪdʒ/.
That is to return "ih-jh" from ```lastStressedPhoneToEnd("savage", false)```
```java
  private void rhymes(String input, Set result) {
    String lss = lastStressedPhoneToEnd(input, false);
```
However it only returns "ae1-v ax-jh" no matter whatever the 2nd parameter is.

To further work on the test case, I think we should focus on lastStressedPhoneToEnd(). What is your opinion on this one, @dhowe ?

I've looked up the passed test cases:
```java
    String[] result = lex.rhymes("apple");
    String[] answer = { "pineapple", "chapel", "grapple" };
    deepEqual(result, answer);

    result = lex.rhymes("bible");
    answer = new String[] { "libel", "tribal" };
    deepEqual(result, answer);

    result = lex.rhymes("google");
    answer = new String[] { "bugle", "frugal" };
    // System.out.println(RiTa.asList(result));
    deepEqual(result, answer);
```
For them, the current lastStressedPhoneToEnd() works just fine.

**Comment by dhowe** [comment]
Do the following and report back here:
a) Search for better algorithmic definition of 'rhyme' -- currently we testing for a match of last-stressed-phoneme-to-end
b) Search words in lexicon ending with ax-jh', and see if they are correct (compare on internet)
c) Wait until we discuss a) before implementing RiLexicon.lastStressedVowelSyllableToEnd()

**Comment by dhowe** [comment]
Literature on definition of rhyme:
* https://www.cs.utah.edu/~miriah/publications/rhyme-design.pdf
* http://sci.tech-archive.net/Archive/sci.lang/2011-03/msg00401.html

**Comment by dhowe** [comment]
Start with: two words rhyme if their final stressed vowel and all subsequent phonemes are identical. before the last stressed vowel are different (also, the sounds immediately
before the last stressed vowel must be different)

**Comment by dhowe** [comment]
Start by looking at the Processing source code here: http://www.sci.utah.edu/~nmccurdy/rhymeDesign/tools/RhymeDesign_Processing221.zip

**Comment by cqx931** [comment]
If the goal is just to do the rhyme without differentiate the type, would it be ok to change the currently lastStressedPhoneToEnd() to lastVowelPhoneToEnd()?

Perfect Masculine ... - O [N C]’
Perfect Feminine  ... - O [N C’ - O N C]
Perfect Dactylic    ... - O [N C’ - O N C - O N C]

For the above three types, the common feature is the last [N C], which is "the last vowel phoneme to the end".
So for two words, if the last [N C] are the same, it should be at least be a Perfect Masculine.

As for the processing code they wrote, I would not suggest implementing that into RiTa.
Fundamentally they have a quite different way to break the syllable,which makes sense for their much more complicated system of rhyming. But if we just use the basic three types, we don't need to implement their system.

Ex: 
The syllables for "tricky" in RiTa    t-r-ih-k / iy
The syllables for "tricky" in the paper    t-r-ih / k-iy

And the code was indeed too messy...

**Comment by cqx931** [comment]
#280

**Comment by dhowe** [comment]
great -- now port to js

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTaJS/pull/17

**Comment by cqx931** [comment]
for the case "yo","bro",useLTS = true
they represent the case where words have no stress at all when using the LTS rules.
As our current way of doing the isRhyme function is based on lastStressedPhoneToEnd, it will return null as no stress is found.
So now I'm not sure whether I should change the rhyming rules to ignore the stress at all or trying to handles them as special cases.
