### ISSUE TITLE
Update p5js KWIKmodel example to work like DOM

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#193]
rita/js/examples/p5js/KWIKmodel/
rita/js/examples/dom/KWIKmodel/

Should show message when no word is found **
But use font from p5js version in DOM version

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/RiTaJSHistory/pull/61

**Comment by CyrusSUEN** [comment]
new PR: https://github.com/dhowe/RiTaJS/pull/2

**Comment by CyrusSUEN** [comment]
But there is a bug in my dom version 
![screen shot 2015-09-24 at 7 33 54 pm](https://cloud.githubusercontent.com/assets/2461812/10072328/3b3950f8-62f3-11e5-9667-b5e5df14bc1e.png)
When there is insufficient width, the text is wrapped to next line. 

It's not an easy fix. A temporary workaround is to increase the width of the container element.

**Comment by dhowe** [comment]
you should be able to fix it with css overflow, no?
http://www.w3schools.com/cssref/pr_pos_overflow.asp

**Comment by CyrusSUEN** [comment]
> fix it with css overflow

Tried experiment with overflow and position attr in the browser's inspector. But I can't fix it.
Overflow doesn't work very well and there are some side effects when modifying individual position attr.

I think to solve it, I may need more than one container element to better control the layout.

**Comment by dhowe** [comment]
not just something like this? http://makandracards.com/makandra/5883-use-css-text-overflow-to-truncate-long-texts

**Comment by dhowe** [comment]
Status?

**Comment by CyrusSUEN** [comment]
Thanks! It's now fixed: https://github.com/dhowe/RiTaJS/pull/3
