### ISSUE TITLE
Website download links too wide

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#195]
Elements should have width of visible rectangles

![screen shot 2015-09-19 at 3 39 10 pm](https://cloud.githubusercontent.com/assets/737638/9975170/990b32ae-5ee4-11e5-93a3-d9b29d8e5922.png)

**Comment by dhowe** [comment]
is there a pr for this?

**Comment by cqx931** [comment]
you mean this?
https://github.com/cqx931/RiTa/commit/3e71a67c246fabac0271e7b6eb4b027f2a7a03a4

**Comment by dhowe** [comment]
No a pull request... or did I merge it already?

**Comment by cqx931** [comment]
yes, already merged

**Comment by dhowe** [comment]
ah right, here it is... https://github.com/dhowe/RiTa/pull/207
thanks
