### ISSUE TITLE
Improvements to Tutorials

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#210]
- [x] A code example from RiTa for EVERY sub-section/section (including what the output would be)

- [x] Markov-page is great, but only about halfway done; continue describing 
  - [x] how to create a model from an existing text, and 
  - [x] how to use that model to generate a new text
  - [x] code examples 
  - [x] link to Kafgenstein example: /RiTaJS/examples/p5js/Kafgenstein

- [x] Grammar page
  - [x] include a larger grammar (with standard YAML format, no '|'s)
  - [x] show an example with generateFrom()   -- see RiGrammar.php
  - [x] link to Haiku example: /RiTaJS/examples/p5js/HaikuGrammar

- [x] Concordance page needs a lot more work
  - [x] better explanation, see [this](http://shiffman.net/teaching/a2z/analysis/#concordance)
  - [x] code examples 
  - [x] info on [KWIC models](https://en.wikipedia.org/wiki/Key_Word_in_Context)
  - [x] link to KWICModel example: /RiTaJS/examples/p5js/KWICmodel

- [x] Syntax highlighting (see #209)

Note: this [page](http://shiffman.net/teaching/a2z/generate/) has some good info for deepening our generation pages. Feel free to borrow from it (with citation of course)

**Comment by cqx931** [comment]
Two questions:
1. "A code example from RiTa for EVERY sub-section/section,"
Does that mean something like this for every sub-section?

You can use RiTa.getPhonemes to analyse the phonemes.
RiTa.getPhonemes("An elephant is a mammal");
The output will be: 'ae-n eh-l-ax-f-ax-n-t ih-z ey m-ae-m-ax-l'.


2."this page has some good info for deepening our generation pages. "
What do you mean by "generation pages"? The kitchen sketch?

I will get started this Sunday, but probably get more time to work on it on Monday.

**Comment by dhowe** [comment]
> On 26 Sep, 2015, at 6:38 pm, cqx931 <notifications@github.com> wrote:
> 
> Two questions:
> 1. "A code example from RiTa for EVERY sub-section/section,"
> Does that mean something like this for every sub-section?
> 
> You can use RiTa.getPhonemes to analyse the phonemes.
> RiTa.getPhonemes("An elephant is a mammal");
> The output will be: 'ae-n eh-l-ax-f-ax-n-t ih-z ey m-ae-m-ax-l'.
> 
exactly, though we need to a) add proper syntax highlighting, 
and b) figure out some consistent convention for showing the output
> 2."this page has some good info for deepening our generation pages. "
> What do you mean by "generation pages"? The kitchen sketch?
> 
No, I mean the n-gram and grammar pages (used for generating text).
In fact, on tutorial/index.php, lets change those headings to:

— Analyzing Text
— Transforming Text
— Generating Text
	— Generating with grammars
	— Generating with n-grams

**Comment by cqx931** [comment]
For grammar page, by "include a larger grammar" do you mean use a more complex grammar for the example or add a more complex grammar in addition to the current one? And how "large" should it be?Something like a Haiku grammar?

**Comment by dhowe** [comment]
Actually the grammar that you have there is probably fine. But please also show a native yaml version. Something like: "You can also represent your grammar without the "|" shortcut, as follows:"
Then show this format for the same grammar:

![screen shot 2015-10-03 at 4 44 11 pm](https://cloud.githubusercontent.com/assets/737638/10262142/146c2822-69ee-11e5-91a8-c52f7395e287.png)
