### ISSUE TITLE
Simple sketch with RiTimer, RiText, RiWordNet

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#213]
To test some deprecated functions. Start with the code below and update to work with current RiTa. Keep a list of any functions that no longer work.

````processing

RiText rt, rts[];
RiWordNet wordnet;

void setup() 
{
  size(300, 300);    
  
  RiText.defaultFill(255);
  RiText.defaultFont("arial", 14);
  
  rt = new RiText(this, "random", 280, 40);
  rt.align(RIGHT).fontSize(36);

  wordnet = new RiWordNet("/WordNet-3.1", false, false);
  RiTa.timer(this, 2.0); 
}

void draw() 
{  
  background(40);
  RiText.drawAll();
}

void onRiTaEvent(RiTaEvent re) { // called every 2 seconds by timer   
  
    String[] tmp = {};    
    while (tmp.length < 1) {
      
      String word = wordnet.getRandomWord("n");
      rt.text(word);
      tmp = wordnet.getAllSynonyms(word, "n", 13);
    }    
    Arrays.sort(tmp); // alphabetize the list
    
    RiText.dispose(rts);
    rts = RiText.createLines(this, tmp, 30, 73);
}

**Comment by CyrusSUEN** [comment]
```
Arrays.sort(tmp);
```

Should be changed to ```sort(tmp);```

Also updated reference page https://github.com/dhowe/RiTa/pull/214

**Comment by dhowe** [comment]
Where is sort() coming from, PApplet?

**Comment by CyrusSUEN** [comment]
I think it's a builtin method of Processing. 
https://processing.org/reference/sort_.html

**Comment by dhowe** [comment]
every method in java comes from a class
in this case, [PApplet](http://processing.org/reference/javadoc/core/processing/core/PApplet.html)
why do you prefer PApplet.sort() over Arrays.sort()?

**Comment by CyrusSUEN** [comment]
> why do you prefer PApplet.sort()

I test the sample code in Processing 3.0 beta 7 which complaints "Connot find anything named "Arrays".

**Comment by CyrusSUEN** [comment]
Should we document
```java
public RiWordNet(String wordnetInstallDir, Object parent)
public RiWordNet(String wordnetInstallDir, boolean ignoreCompoundWords)
public RiWordNet(String wordnetInstallDir, boolean ignoreCompoundWords, boolean ignoreUpperCaseWords)
public RiWordNet(String wordnetInstallDir, Object parent, boolean ignoreCompoundWords, boolean ignoreUpperCaseWords)
```

Currently it only demonstrates how to use ```public RiWordNet(String wordnetInstallDir)``` on Mac and Windows on the [reference page](https://rednoise.org/rita/reference/RiWordNet.php).

**Comment by dhowe** [comment]
I will ask again, does the sketch actually work as is?

**Comment by dhowe** [comment]
Update the documentation to include these 2 (not the others):
````
public RiWordNet(String wordnetInstallDir, boolean ignoreCompoundWords);
public RiWordNet(String wordnetInstallDir, boolean ignoreCompoundWords, boolean ignoreUpperCaseWords);

**Comment by CyrusSUEN** [comment]
> does the sketch actually work as is

Unless we include 
```
import java.util.*;
```

**Comment by dhowe** [comment]
use java.util.Arrays.sort()

**Comment by dhowe** [comment]
Here is an updated version:

import rita.*;

RiText rt, rts[];
RiWordNet wordnet;

void setup() 
{
  size(300, 300);    

  RiText.defaultFill(255);
  RiText.defaultFont("georgia", 14);

  rt = new RiText(this, "random", 280, 40);
  rt.align(RIGHT).fontSize(36);

  // load wordnet, ignoring compound & uppercase words
  wordnet = new RiWordNet("/WordNet-3.1", true, true);
  RiTa.timer(this, 2.0);
}

void draw() 
{  
  background(40);
  RiText.drawAll();
}

void onRiTaEvent(RiTaEvent re) { // called every 2 seconds by timer   

  String[] tmp = {};    
  while (tmp.length < 3) {

    rt.text(wordnet.getRandomWord("n"));
    tmp = wordnet.getAllSynonyms(rt.text(), "n", 13);
  }    
  java.util.Arrays.sort(tmp); // alphabetize the list

  RiText.dispose(rts);
  rts = RiText.createLines(this, tmp, 30, 66);
}

**Comment by dhowe** [comment]
Next create the same sketch (for Processing) without using RiText

**Comment by CyrusSUEN** [comment]
> create the same sketch (for Processing) without using RiText

```processing
import rita.*;

String strings;
String randomWord;
RiWordNet wordnet;

void setup() 
{
  size(300, 300);    

  fill(255);
  textFont(createFont("Georgia", 36));

  randomWord = "random";
  strings = "empty";

  // load wordnet, ignoring compound & uppercase words
  wordnet = new RiWordNet("D:\\Development\\WordNet3.1", true, true);
  RiTa.timer(this, 2.0);
}

void draw() 
{  
  background(40);

  textAlign(RIGHT);
  textSize(36);
  text(randomWord, 280, 40);

  textSize(14);
  textLeading(14);
  textAlign(LEFT);
  text(strings, 30, 66);
}

void onRiTaEvent(RiTaEvent re) { // called every 2 seconds by timer   

  String[] tmp = {};    
  while (tmp.length < 3) {

    randomWord = wordnet.getRandomWord("n");
    text(randomWord, 280, 40);
    tmp = wordnet.getAllSynonyms(randomWord, "n", 13);
  }    
  java.util.Arrays.sort(tmp); // alphabetize the list

  strings = "";
  for (int i = 0; i < tmp.length; i++)
    strings += (tmp[i] + "\n");
}
```

**Comment by CyrusSUEN** [comment]
> Update the documentation to include these 2

https://github.com/dhowe/RiTa/pull/215

**Comment by dhowe** [comment]
edited and checked-in to /RiTa/examples/processing
