### ISSUE TITLE
Website not centering correctly at certain widths

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#221]
text cut off on right edge:

![screen shot 2015-10-03 at 3 30 02 pm](https://cloud.githubusercontent.com/assets/737638/10261914/b6497c68-69e3-11e5-902c-40e338d0299e.png)

**Comment by dhowe** [comment]
Also, I'm not sure if the first paragraph is centering correctly in general...

**Comment by CyrusSUEN** [comment]
Please also check against browsers on mobile device
![screenshot_2015-10-05-22-13-28](https://cloud.githubusercontent.com/assets/2461812/10282619/70f14bf6-6bae-11e5-8e47-97849842ce40.png)

**Comment by cqx931** [comment]
@CyrusSUEN  Thanks for mentioning that. The text problem on mobile device is already fixed in the current version in github.

**Comment by dhowe** [comment]
Looks good.
