### ISSUE TITLE
Punctuation spacing incorrect in KWICModel

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#223]
![screen shot 2015-10-03 at 4 51 43 pm](https://cloud.githubusercontent.com/assets/737638/10262184/439e6e2e-69ef-11e5-9294-31af14a52650.png)

**Comment by dhowe** [comment]
check if this is a problem with the text itself, or with the tokenization, or...

**Comment by CyrusSUEN** [comment]
What's the error?
Is it ```felt before." Oh,``` should be ```felt before. "Oh,``` ?

**Comment by CyrusSUEN** [comment]
The text itself is 
```
there that he had never felt before.

"Oh, God", he thought, "what a strenuous career it is that
```
from line 33 to 35 of kafka.txt

**Comment by dhowe** [comment]
right. There should be no space between " and 'Oh',  but there should be a space after the last comma
````
felt before. "Oh, God",  he thought, "

**Comment by CyrusSUEN** [comment]
This is a problem when doing untokenize()
```dist/rita.js``` line 245

```if (!RiTa.isPunctuation(arr[i]))``` returns false when ```i = 3``` and ```arr[i] = \"``` 
That the delim char (space char) is skipped.

![capture](https://cloud.githubusercontent.com/assets/2461812/10276962/51ee9ad4-6b85-11e5-9725-739b9937eb8b.PNG)

I think to solve this we need to add some conditions before calling line 250.

**Comment by dhowe** [comment]
create a very simple test-case that fails in RiTa-tests.js (testUntokenize)

**Comment by CyrusSUEN** [comment]
test case:
```js

      input = ["felt", "before", ".", "\"", "Oh", "God", "\"", ",", "he", "thought", ",", "\""];
      expected = "felt before. \"Oh, God\", he thought, \"";
      output = RiTa.untokenize(input);
      deepEqual(output, expected);
```

Shall I create a PR only after solving it?

**Comment by dhowe** [comment]
no, you can create one for the test as well…

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/RiTaJS/pull/5
added 2 new test cases to untokenize() and 
fixed the function by checking this kind of situation by ```if ((arr[i - 1]).match(/[\.,:]/g) && arr[i] == '\"')``` where arr[i] is an index of the tokenized string

**Comment by dhowe** [comment]
have you solved this for RiTa?

**Comment by dhowe** [comment]
I am not convinced by this fix. 
First fix:  RiTaJS: test/KnownIssues-test.js -> function: "RiTa.testTokenizeAndBack"
This is working in Java

**Comment by CyrusSUEN** [comment]
Ported untokenize() from RiTa to RiTaJS: https://github.com/CyrusSUEN/RiTaJS/commit/1db4d8f4eeaece4b7b8ce8979102c64b91cb654f
But it doesn't pass the current test case.
![capture](https://cloud.githubusercontent.com/assets/2461812/10512425/ba0d512e-7372-11e5-95c3-a0b8f6ddd181.PNG)

------------------------
Updated untokenize() in RiTa to meet new test cases: https://github.com/CyrusSUEN/RiTa/commit/1a87aae3f0e891ae4afe2a44d7e29fa3d25f8493
```
"\"Oh God,\" he thought.";
"\"Oh God.\" he thought.";
"\"Oh God,\" he thought, \"maybe this is the end.\"";
```
new test cases pass but an old one breaks
```
"(that's why this is our place).";
```

**Comment by dhowe** [comment]
see my email with a fix

**Comment by dhowe** [comment]
status?

**Comment by dhowe** [comment]
related to #250

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
Please verify: https://github.com/dhowe/RiTaJS/pull/21

**Comment by dhowe** [comment]
Can this be closed?

**Comment by CyrusSUEN** [comment]
> Can this be closed?

Yes. The PR was merged.
