### ISSUE TITLE
Navigation dissapears at widths under 985px 

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#226]
window in this screenshot is about 985px -- that and any size smaller, and the navigation disappears and the little menu pops up -- which means that most users will never see the navigation... Is this intentional? Perhaps the font should scale down first...

![screen shot 2015-10-09 at 2 31 51 am](https://cloud.githubusercontent.com/assets/737638/10376000/1a0c5524-6e2e-11e5-8634-94a649d88652.png)

**Comment by cqx931** [comment]
yes, it is intentional. Since the menu is pretty long, when the window is smaller than apr. 1000px, the menu won't be able to show within single line. 
And the current font size for the menu bar is 14px, which I think shouldn't be smaller...

**Comment by dhowe** [comment]
ok for now...
