### ISSUE TITLE
No lexicon entries loaded on Windows (Processing 2.2.1)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#227]
The file IS being loaded, however no valid entries are found.
My guess is the problem originates in line 186 of JSONLexicon.java,
where the regex is failing due to the system-specific line-separator
@CyrusSUEN please check this first...

Windows8.1, Processing2.2.1, RiTa1.1.12

**Comment by CyrusSUEN** [comment]
> My guess is the problem originates in line 186 of JSONLexicon.java,

Yes you are right.
In successful case loadJSON() returns a String array of size 33390 while in fail case it returns a String array with size 1.

Both successful and fail cases can be created on a Windows 10 machine. 
If I ran the ReLexicon from RiTa repo's RiLexiconTest.java, it can load all the entries. While running it from an Eclipse Processing example it fails to load.

I'm trying what I can do about it.

**Comment by CyrusSUEN** [comment]
Line 186 of JSONLexicon.java:
```java
String splitter = "\\|?" + System.getProperty("line.separator");
```
The value of ```splitter``` is always "\\|?\r\n" on WIndows platform. But the newline char from from file ```rita.jar/rita/rita_dict.js``` is just "\n".

I added a newline detection in this fix:
https://github.com/dhowe/RiTa/pull/228/files

It doesn't look elegant but It can pass the JUnit test and the Processing example on both Windows and Mac.

**Comment by dhowe** [comment]
good -- closing.
