### ISSUE TITLE
New examples page needed

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#229]
We need a new page (and nav link) for "examples"

There will be some number of examples (maybe 5-6) and each one will have a title, a screenshot (150x150?), and 4 links: one for the p5js example, one for the dom example, and 'source' for each

I created a very simple version at RiTa/web/examples.php

**Comment by dhowe** [comment]
nice -- lets also add the nav link

**Comment by cqx931** [comment]
Can we move the "contact" from the menu to the footer? There are already many content in the menu, so I think it might be better to move the "contact " to footer since it is not a page.

**Comment by dhowe** [comment]
Sure, I guess that works. But for tutorials, examples, and quick-start, I'd like it to be more prominent...

**Comment by dhowe** [comment]
the other option would be to take tutorials and quickstart and examples and group them under a tab called “Learning”… Which do you prefer?
