### ISSUE TITLE
Need new analysis example

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#233]
Perhaps a simple sketch (similar to RiTa/examples/RandomSyns), that selects a random word every 2 seconds, from the lexicon, then calls RiString.features(), and displays each of the features (pos, stress, phonemes, etc) in an aesthetically interesting way...

**Comment by cqx931** [comment]
Is it just a pde sketch like the RandomSyns or is it one of the examples for the website?

**Comment by dhowe** [comment]
Are you asking if its java or javascript? doesn't matter for the initial version (whatever's easier for you)... eventually we will use it for both the included examples in the download (java/pde) and for the website (p5js)

**Comment by dhowe** [comment]
please add the color-coding for part-of speech (either colored text or background rectangle)...
check-in (note location below) 
and the convert to p5js

**Comment by cqx931** [comment]
btw, when I finish this example, shall I also save it to RiTaJS/examples?

**Comment by dhowe** [comment]
first save the java/processing version where it is, then we need to create a new version for p5js, and a new version for the DOM, which will be saved in RiTaJS with the other examples...

**Comment by cqx931** [comment]
Updated the java version
https://github.com/dhowe/RiTa/pull/245
