### ISSUE TITLE
Webpage prompting for Flash?

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#235]
Are we using Flash anywhere on the site? If so, I'd like to remove it (it is totally insecure at this point)...

![screen shot 2015-10-17 at 1 50 08 pm](https://cloud.githubusercontent.com/assets/737638/10557256/d8352b6c-74d6-11e5-9118-374f16a60641.png)

**Comment by cqx931** [comment]
I didn't use any flash in the website though... the video is played by html <video> tag

**Comment by dhowe** [comment]
ok
