### ISSUE TITLE
Tweaks to source-code links

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#239]
A few items need fixing:
* remove "close" link from source-page (users can just close the tab)
* changes links to use syntax-enabled source here: http://rednoise.org/rita/examples.php
* change grammar link to use syntax-enabled source here: http://rednoise.org/rita/examples/p5js/HaikuGrammar/
* change grammar link to use syntax-enabled source here: http://rednoise.org/rita/examples/dom/HaikuGrammar/

Also a question: how do we adjust the colors used in the syntax highlighting? Current colors are a bit strange, for example strings and function names have the same color:

<img width="703" alt="screen shot 2015-10-21 at 6 09 35 pm" src="https://cloud.githubusercontent.com/assets/737638/10633705/080ec744-781f-11e5-9dfe-68e8409b2e61.png">

**Comment by dhowe** [comment]
@cqx931 I also realize that all of these changes example HTML were made in the wrong place, so we need to move them over to /RiTaJS/examples/...  (they are automatically copied into /RiTa/web during the build process, so will be overwritten)

**Comment by cqx931** [comment]
Shall I then just leave the example folder in RiTa and update all the files in RiTaJS? As it will be overwritten anyway...

**Comment by dhowe** [comment]
correct

On November 5, 2015 3:16:42 PM GMT+08:00, cqx931 <notifications@github.com> wrote:
>Shall I then just leave the example folder in RiTa and update all the
>files in RiTaJS? As it will be overwritten anyway...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dhowe/RiTa/issues/239#issuecomment-153975625


[mobile]

**Comment by cqx931** [comment]
<img width="493" alt="2015-11-05 4 16 29 pm" src="https://cloud.githubusercontent.com/assets/3056154/10963123/ba9b83a6-83d8-11e5-8516-afea1f8c6e5a.png">
currently the way I am doing it is by linking the page back to the js & css files within the RiTa web folder, so if I copy the same file to RiTaJS, the source code won't work within RiTaJS. But it works when it will work ultimately when it is built in the web folder... will this be ok? Or you will prefer keeping everything within the example folder?

**Comment by dhowe** [comment]
Still to do:
* remove "close" link from source-page (users can just close the tab) 
* change grammar link to use syntax-enabled source here: http://rednoise.org/rita/examples/p5js/HaikuGrammar/
* change grammar link to use syntax-enabled source here: http://rednoise.org/rita/examples/dom/HaikuGrammar/

**Comment by cqx931** [comment]
It seems like that " <start> " will always disappear, when the code is loading, and it will looks like this:
<img width="1101" alt="2015-11-30 2 07 57 pm" src="https://cloud.githubusercontent.com/assets/3056154/11465299/90e19e08-9772-11e5-931b-c18deaac006e.png">
http://lab-lamp.scm.cityu.edu.hk/~qianxchen2/yaml/

**Comment by dhowe** [comment]
Sorry, can you explain more clearly what the issue is here?

**Comment by cqx931** [comment]
The grammar file is like this:
<img width="1119" alt="2015-12-01 10 34 04 am" src="https://cloud.githubusercontent.com/assets/3056154/11490806/1396b9ba-9817-11e5-9b90-1189577fefa4.png">

When the code is loaded with the following code,even without any prism or google code prettify, &lt;start&gt; will disappear.
function getcode(url,id){
     $.ajax({
        url: url,
        dataType: "text",
        success: function (data)
        {
          $(id).html(data);
        }
      });
  }

<img width="1101" alt="2015-11-30 2 07 57 pm" src="https://cloud.githubusercontent.com/assets/3056154/11490788/093d7698-9817-11e5-9293-0f8c13d4313d.png">

**Comment by dhowe** [comment]
you need to encode the HTML entities. try this inside the getcode function:

````js
      var encoded = data.replace(/[\u00A0-\u9999<>\&]/gim, function(i) {
        return '&#'+i.charCodeAt(0)+';';
      });
      $(id).html(encoded);

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTaJS/pull/10
