### ISSUE TITLE
Add notes on 'how to cite'

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#240]
Something like:

----------

If you publish work that uses RiTa, please cite RiTa as follows:

Example Reference:
Howe, D. C. (2015). RiTa [Computer software]. Retrieved from http://rednoise.org/rita.

Example Text Citations
“We used the RiTa library (Version 1.12; Howe 2015) to perform natural language processing of our text".

Or, if you prefer to cite the paper:

Howe, D.C.  2009. RiTa: creativity support for computational literature. In *Proceedings of the seventh ACM conference on Creativity and cognition (C&C '09)*. ACM, New York, NY, USA, 205-210. DOI=http://dx.doi.org/10.1145/1640233.1640265

And let us know! We'd love to include your work in our [link: gallery]

**Comment by cqx931** [comment]
How about something like this? As the main page is center aligned, find it kind of strange to put this left-aligned material at the bottom, so I made a separate page and create a link in the footer.
http://lab-lamp.scm.cityu.edu.hk/~qianxchen2/rita/cite.php

**Comment by dhowe** [comment]
Looks great -- just add a little space before each of the citation examples (or some other visual clue), as we discussed

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/243
