### ISSUE TITLE
Add to RiTa gallery

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#242]
https://play.google.com/store/apps/details?id=processing.test.jumping_wild

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/243

**Comment by dhowe** [comment]
http://antiboredom.github.io/a-letter-to-our-zuckerberg/
http://antiboredom.github.io/zuckify/

**Comment by dhowe** [comment]
Thanks -- as with press links, lets add the new projects at the top (from now on)...
