### ISSUE TITLE
Add all gallery resources to web/gallery

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#246]
We need to make sure that all projects in the gallery are added to the repo. I've created a dir at /RiTa/web/gallery  - you can start moving things over. Let me know if you can't find (or download) something...

The goal here is to have all project resources, in case the original project disappears

**Comment by CyrusSUEN** [comment]
All done

http://localhost/RiTa/web/gallery/The%20Whole%20Brilliant%20Enterprise
http://localhost/RiTa/web/gallery/
http://localhost/RiTa/web/gallery/
http://localhost/RiTa/web/gallery/

Made 2 PRs and only the second PR includes the Visual Grammars and automatype because of the huge size of video files.

**Comment by CyrusSUEN** [comment]
Put video files on rednoise.org:
https://github.com/dhowe/RiTa/pull/254

After this PR all Gallery resources should be working and available to local server via the above URLs.

**Comment by CyrusSUEN** [comment]
new folder name: https://github.com/dhowe/RiTa/pull/255

[http://localhost/RiTa/web/gallery/AboutNothingPlaces](http://localhost/RiTa/web/gallery/AboutNothingPlaces)
[http://localhost/RiTa/web/gallery/Automatype](http://localhost/RiTa/web/gallery/Automatype)
[http://localhost/RiTa/web/gallery/CornellsYokeMachine](http://localhost/RiTa/web/gallery/CornellsYokeMachine)
[http://localhost/RiTa/web/gallery/GameDefinitions](http://localhost/RiTa/web/gallery/GameDefinitions)
[http://localhost/RiTa/web/gallery/HarryPotterBookGenerator](http://localhost/RiTa/web/gallery/HarryPotterBookGenerator)
[http://localhost/RiTa/web/gallery/MemoireInvolontaireNo1](http://localhost/RiTa/web/gallery/MemoireInvolontaireNo1)
[http://localhost/RiTa/web/gallery/RiTaTwitterbots](http://localhost/RiTa/web/gallery/RiTaTwitterbots)
[http://localhost/RiTa/web/gallery/ShanShui](http://localhost/RiTa/web/gallery/ShanShui)
[http://localhost/RiTa/web/gallery/SpinState](http://localhost/RiTa/web/gallery/SpinState)
[http://localhost/RiTa/web/gallery/TheGodardFilmGenerator](http://localhost/RiTa/web/gallery/TheGodardFilmGenerator)
[http://localhost/RiTa/web/gallery/TheWholeBrilliantEnterprise](http://localhost/RiTa/web/gallery/TheWholeBrilliantEnterprise)
[http://localhost/RiTa/web/gallery/VisualGrammars](http://localhost/RiTa/web/gallery/VisualGrammars)

**Comment by dhowe** [comment]
update gallery.php with new links and test each one.

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/RiTa/pull/267
All links updated except RiTa Twitterbots which I encountered a technical difficulty that CSS was  missing.

**Comment by CyrusSUEN** [comment]
Discussion here: https://github.com/dhowe/RiTa/pull/268

Should be good if there is no further issues in RiTaTwitterbots

**Comment by dhowe** [comment]
Links are still broken on left side of RiTaTwitterbots:
"http://localhost/JonSnow_exe" should be "http://twitter.com/JonSnow_exe"

**Comment by CyrusSUEN** [comment]
> Links are still broken on left side of RiTaTwitterbots

Fixed: https://github.com/dhowe/RiTa/pull/274
