### ISSUE TITLE
Create test-set for java function: arpaToIPA(String phonemes)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#248]
Add tests here (single words are fine):  rita.java.PhonemeTests.testArpaToIPA()

I imagine most or all will fail. Do NOT fix the algorithm as yet.
Just create a good test-set that covers every phoneme.

You can use these as the examples:
  http://web.stanford.edu/class/linguist238/fig04.01.pdf

Also see:
  https://en.wikipedia.org/wiki/Arpabet
  http://www.speech.cs.cmu.edu/cgi-bin/cmudict?in=C+M+U+Dictionary

**Comment by CyrusSUEN** [comment]
Do we need to include stress?

Stress
Value	Description
0	No stress
1	Primary stress
2	Secondary stress

With stress example:
PARSLEY P AA1 R S L IY0 .

without stress example:
PARSLEY P AA R S L IY .

**Comment by dhowe** [comment]
Should be able to do both. Perhaps add a boolean flag to the function signature: "includeStresses"

**Comment by CyrusSUEN** [comment]
Please verify: https://github.com/dhowe/RiTa/pull/251

**Comment by CyrusSUEN** [comment]
Re-fix to testArpaToIPA(): https://github.com/dhowe/RiTa/pull/253

**Comment by CyrusSUEN** [comment]
PR: https://github.com/dhowe/RiTa/pull/288

**Comment by CyrusSUEN** [comment]
Done and closing
