### ISSUE TITLE
LTS returning 2 syllable words with both syllables stressed

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#264]
Hello
Apple
Catnip

**Comment by dhowe** [comment]
Should be fixed. Please verify @CyrusSUEN

**Comment by CyrusSUEN** [comment]
What should be the desirable result?
When I run PhonemeTests.java as Java app, it prints
```
[RiTa] Using letter-to-sound rules for: catnip
2) ˈkætˈnɪp
```

Or ```k-ae1-t n-ih1-p``` from the LTS rule

**Comment by dhowe** [comment]
see #266

**Comment by CyrusSUEN** [comment]
> see #266

'capnip' is not a 2-syllable-word with both syllables stressed according to [CMU dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict?in=Catnip&stress=-s) and [Google dictionary](https://www.google.com.hk/search?q=define+CATNIP&oq=define+CATNIP&aqs=chrome..69i57j69i59l2j0l3.776j0j7&sourceid=chrome&es_sm=93&ie=UTF-8).

It should be:
k-ae1-t n-ih0-p
ˈkat nɪp

Right now RiTa returns 'k-ae1-t n-ih1-p'.

**Comment by dhowe** [comment]
Your test method: RiLexiconTest.testGetRawPhonesStringBoolean is not working correctly.
Read the documentation of RiLexicon.getRawPhones() more carefully. 
It only uses LTS when the word is NOT found in the dictionary.
Turn off RiTa.SILENT and RiLexicon.SILENCE_LTS at the top
and you get the following output, which shows which words are ACTUALLY using LTS:

````
[RiTa] Using letter-to-sound rules for: bing
[RiTa] Using letter-to-sound rules for: laggin
[RiTa] Using letter-to-sound rules for: coder
[RiTa] Using letter-to-sound rules for: streamer
[RiTa] Using letter-to-sound rules for: washington
[RiTa] Using letter-to-sound rules for: alaska

**Comment by dhowe** [comment]
You also need to finish KnownIssuesTest.testLTS() by adding the correct expected results.

**Comment by CyrusSUEN** [comment]
> finish KnownIssuesTest.testLTS()

https://github.com/dhowe/RiTa/pull/300

**Comment by dhowe** [comment]
Can this be closed?

**Comment by CyrusSUEN** [comment]
The problem has been added to KnownIssuesTest.testLTS(). Closing this one.
