### ISSUE TITLE
LetterToSound errors

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#265]
Example: 
````w-aa1 sh-ih1-ng t-ah1-n````
instead of 
````w-aa1 sh-ih0-ng t-ah0-n````

Compare to RhymeDesign::LTS.java

**Comment by dhowe** [comment]
fixed, verify with tests...

**Comment by CyrusSUEN** [comment]
> fixed, verify with tests...

Current RiTaJS test cases not passing after this fix.
39 failed

**Comment by CyrusSUEN** [comment]
> fixed, verify with tests...

Tests passed after gulp build with rita_newdict.js
