### ISSUE TITLE
Make sure both RiTa/RiTaJS have simple LTS tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#266]
include apple, hello, washington, etc.

**Comment by CyrusSUEN** [comment]
Added RiTa version: https://github.com/dhowe/RiTa/pull/288
https://github.com/CyrusSUEN/RiTa/commit/4d1935892115d8fe4f75fe79a1309c2efa17caa9

**Comment by dhowe** [comment]
I don't see the LTS tests. These should be in RiLexiconTest.java and RiLexicon-tests.js and should test that we are getting the correct outputs (syllables, stresses, phonemes, etc.) for words not in our dictionary. This ticket has nothing to do with IPA phonemes.

**Comment by CyrusSUEN** [comment]
Is it like this? https://github.com/dhowe/RiTa/pull/290/files

**Comment by dhowe** [comment]
Yes, that is fine for now. Make sure that we have a good range of tests (different numbers of syllables, number of stresses, etc.), and that the results come from good online sources.

**Comment by CyrusSUEN** [comment]
I will update the test case.
At the meantime, I cannot do the same for RiTaJS in RiLexicon-tests.js. The error is  lex.getRawPhones is not a function:
```js
      lex = RiLexicon();

      s = lex.getRawPhones("dragging", false);
      equal(s, "d-r-ae1 g-ih-ng");
```

```js
      lex = RiLexicon();

      s = lex._getRawPhones("dragging", false);
      equal(s, "d-r-ae1 g-ih-ng");
```

**Comment by CyrusSUEN** [comment]
Updated RiTa version.
Ready for PR: https://github.com/dhowe/RiTa/pull/290
