### ISSUE TITLE
Convert gallery examples to p5js

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#276]
(any that are still using processing.js)

also check that the link on the HTML page goes to p5js and not processing.js

only work on this when other tasks are finished or on-hold...

**Comment by CyrusSUEN** [comment]
Only RandomSyns and ReplaceableWriting need to be converted. They both use WordNet.
How can we use WordNet online (in a web browser environment)?

**Comment by dhowe** [comment]
on hold
