### ISSUE TITLE
arpaToIPA() needs NAmE and BrE pronunciation?

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#282]
For example: go
North American English: ˈgəʊ
British English: ˈgəʊ

In Phoneme.java
```java
    amap.put("ow", "əʊ"); // əʊ in NA; or oʊ in England
```

Another example: fast
NAmE: fɑːst
BrE: fæst

For now I will stick to NAmE when working on this.
We may decide if we need to include this feature after everything is done.

**Comment by dhowe** [comment]
Use NA
