### ISSUE TITLE
Remove excess vertical space from HaikuGrammar

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#284]
RiTaJS/examples/dom/HaikuGrammar
RiTaJS/examples/p5js/HaikuGrammar

also synchronize background colors between dom and p5js

**Comment by cqx931** [comment]
the image and title should link to p5js

**Comment by cqx931** [comment]
check the link path, make sure everything comes from the lib folder

bg for randomRhyme --> Dark Grey instead of Black

Color of links : no underline, grey color

**Comment by cqx931** [comment]
fixed
