### ISSUE TITLE
RiTa fails to load on Processing 3 on RaspberryPi 

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#306]
Installed RiTa with the contribution manager, everything seems ok (the Rita folder is in sketchbook/libraries folder).
But when running p5 says that "no library found for Rita"

**Comment by dhowe** [comment]
Please debug

**Comment by dhowe** [comment]
Status?

**Comment by CyrusSUEN** [comment]
haven't tried that yet. Will conduct test this week

**Comment by CyrusSUEN** [comment]
I can reproduce this on RaspberryPI. But it's painfully slow to debug on it. It takes minutes to open Processing 3. And its Console literally printed "no library found for Rita" when the Rita folder is in sketchbook/libraries folder.

I will try to find an emulator (ARM virtual machine with PaspberryPi OS image) to test it and try to debug on it. 

At the meantime, can you try this on your Linux?

**Comment by CyrusSUEN** [comment]
OK. So @dhowe have found out that the library folder name has to be 'rita' instead of 'RiTa'. After this change we can now successfully use RiTa library on Processing on Ubuntu and Raspbian OS.

**Comment by dhowe** [comment]
@CyrusSUEN  can this be closed ?

**Comment by CyrusSUEN** [comment]
> can this be closed ?

The problem and solution has been found. Can be closed.
But ultimately we should update the library's folder name from `RiTa` to `rita` for Processing so that users on case-sensitive file systems can enjoy a hassle-free installation process.
