### ISSUE TITLE
Example mistake in RiTa.singularize Reference Page

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#315]
<img width="774" alt="screen shot 2016-02-14 at 12 16 03 pm" src="https://cloud.githubusercontent.com/assets/3056154/13031824/d2b16f2e-d314-11e5-88db-3485b7bb576f.png">

**Comment by dhowe** [comment]
sorry, what is the mistake?

**Comment by dhowe** [comment]
good catch, now fixed
