### ISSUE TITLE
Unexpected angle brackets

### ISSUE THREAD

**Issue by limzykenneth** [dhowe/RiTa#317]
I'm using the RiGrammer to generate sentences and I found that with rules like this (note line 10):
![screen shot 2016-03-11 at 12 19 17](https://cloud.githubusercontent.com/assets/7543950/13702018/8b54f2da-e783-11e5-938b-0d5347eb07e5.png)

I get sentence like this:
![screen shot 2016-03-11 at 12 18 15](https://cloud.githubusercontent.com/assets/7543950/13702025/953ad738-e783-11e5-89d8-5486c1457c53.png)

The angle brackets in the rendered sentence disappear if I remove angle brackets around `<scenario>` in the grammar file and the sentence will still render as if the angle brackets are still there.

**Comment by dhowe** [comment]
This looks correct to me, though perhaps I'm missing  your question. There is actually nothing special about the angle-brackets, they are just convention. You have a rule called 'scenario' (in line 12, without angle brackets), so when the parser encounters '<scenario>', it runs the 'scenario' rule and replaces 'scenario' with 'the robots do not learn', thus: '<the robots do not learn>'.

**Comment by limzykenneth** [comment]
Ah...I see, silly me~ Thanks!
