### ISSUE TITLE
Triggers download action of rita.js files instead of page viewing when downloading RiTaJS

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#319]
Affected page: http://rednoise.org/rita/download.php (those *.js files)
Solution: http://stackoverflow.com/a/18678698/1571343

**Comment by dhowe** [comment]
Good point. Please fix...

**Comment by CyrusSUEN** [comment]
Fixed and also updated file size infomation: https://github.com/dhowe/RiTa/pull/325
