### ISSUE TITLE
RiTa website improvement

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#320]
Example page 

* Source pages of KWICmodel example (dom and p5js) have double vertical scroll bars.
http://rednoise.org/rita/examples/dom/KWICmodel/index.html#source http://rednoise.org/rita/examples/p5js/KWICmodel/index.html#source
* Should not be allowed to do text selection by double-clicking on Kafgenstein and HaikuGrammar examples
![1](https://cloud.githubusercontent.com/assets/2461812/14151240/8d3b00c4-f6df-11e5-9d47-445068766fd4.PNG)
![2](https://cloud.githubusercontent.com/assets/2461812/14151239/8d3896f4-f6df-11e5-9d25-e07373431846.PNG)

Reference page
 * Resource missing (HTTP error 500) See the following screen capture

 * Should not print "git-work"
![5](https://cloud.githubusercontent.com/assets/2461812/14150045/bd1135da-f6d9-11e5-9ad5-a77676bd9e36.PNG)

 * Missing favicon icons in all index.php files
![2](https://cloud.githubusercontent.com/assets/2461812/14150153/454b5610-f6da-11e5-906d-8ad0fb78327e.PNG)
 * Only at 924px page width (or at certain page width) does it show a more condensed layout
![924px](https://cloud.githubusercontent.com/assets/2461812/14150334/2addb204-f6db-11e5-8107-a861cba6f32c.PNG)
![1500px](https://cloud.githubusercontent.com/assets/2461812/14150333/2add4738-f6db-11e5-8fd8-a0d5f8764bc5.PNG)

Gallery Page
 * On http://rednoise.org/rita/gallery/Automatype/, 
https://rednoise.org/~dhowe/automatype/css/imgs/rita.bg2.jpg Failed to load resource: the server responded with a status of 404 (Not found)

 * On http://rednoise.org/rita/gallery/MemoireInvolontaireNo1/
![55](https://cloud.githubusercontent.com/assets/2461812/14150858/b59b26b8-f6dd-11e5-9989-746dee27ae8b.png)

 * The snapshot page of [MemoireInvolontaireNo1](http://rednoise.org/rita/gallery/MemoireInvolontaireNo1/) in Gallery is more detailed than the one under Selected Projects category in http://rednoise.org/rita/index.php

**Comment by CyrusSUEN** [comment]
And how about we remove the "Fork me on Github" ribbon from the website? Because there is the link to Github page of RiTa at the bottom of the website.

**Comment by dhowe** [comment]
Lets keep the 'fork me' ribbon, but the others are valid bugs. Can you fix these others? Any that you can't we can assign to @cqx931 ...

**Comment by cqx931** [comment]
I think these problems need to be checked out of the RiTa folder:

1.Reference page
Resource missing (HTTP error 500)
![bd1135da-f6d9-11e5-9ad5-a77676bd9e36](https://cloud.githubusercontent.com/assets/3056154/14582263/d3d4d68a-0432-11e6-9de8-07e3f8061a52.png)

Gallery Page

On http://rednoise.org/rita/gallery/Automatype/, 
https://rednoise.org/~dhowe/automatype/css/imgs/rita.bg2.jpg Failed to load resource: the server responded with a status of 404 (Not found)

**Comment by dhowe** [comment]
These should all be fixed now, and will be pushed live with next version. Can you verify on your local build, @CyrusSUEN ?

**Comment by CyrusSUEN** [comment]
Thanks @cqx931. Above problems have been fixed except the following:
Example page
 * Almost all examples except HaikuGrammar have the following JS problem:
![screen shot 2016-04-19 at 5 09 53 pm](https://cloud.githubusercontent.com/assets/2461812/14633768/ae41a134-0651-11e6-9d4a-62929f85fd4a.png)
 * Some have a blank line between ```<a>``` and ```<div>```:
![screen shot 2016-04-19 at 5 13 27 pm](https://cloud.githubusercontent.com/assets/2461812/14634078/f49951b2-0652-11e6-8a98-7ceb0beff98a.png)

BTW I'm unable to test locally on my machine if the missing favicon icons problem in all index.php files in Reference page has been fixed. 

The following maybe this is design choice / decision that does not need a fix.
Example page
 * Should not be allowed to do text selection by double-clicking on Kafgenstein and HaikuGrammar examples ()

Gallery Page
 * The snapshot page of MemoireInvolontaireNo1 in Gallery is more detailed than the one under Selected Projects category in http://rednoise.org/rita/index.php

**Comment by dhowe** [comment]
Fixed MemoireInvolontaireNo1

**Comment by CyrusSUEN** [comment]
One more: http://rednoise.org/sketches/Shanshui/sketch.html
![1](https://cloud.githubusercontent.com/assets/2461812/14976760/176af08a-1141-11e6-8dd9-81c3d43a0f49.PNG)

**Comment by dhowe** [comment]
what is the issue?

**Comment by CyrusSUEN** [comment]
> what is the issue?

Attached a screenshot, it's HTTP 404 not found error.
and a warning from line 2663 rita-1.0.63.min.js

**Comment by dhowe** [comment]
the sketch shows up or no?

**Comment by CyrusSUEN** [comment]
> the sketch shows up or no?

On my machine, no

**Comment by dhowe** [comment]
Ok, try again

**Comment by CyrusSUEN** [comment]
> Ok, try again

Fixed

**Comment by CyrusSUEN** [comment]
Not sure if this is my problem.

Favicon icons are still missing in most index.php pages in Reference page on Chrome (both PC and Mac) and Safari on Mac.
e.g. [this page](http://rednoise.org/rita/reference/RiGrammar/ready/index.php)
However it has no problem showing the icons on Firefox or Microsoft Edge.

To view the favicon icon on Safari: click on the address bar
![screen shot 2016-05-03 at 3 34 13 pm](https://cloud.githubusercontent.com/assets/2461812/14977245/00ffe90a-1145-11e6-9278-cf40aa858209.png)

**Comment by CyrusSUEN** [comment]
The link of †[text by Brian Kim Stefans](http://blog.sfmoma.org/2011/09/third-hand-plays-automatype-by-daniel-c-howe/) on the bottom of the page http://rednoise.org/rita/gallery/Automatype/ cannot be reached.

----------------------
Favicon icon is missing on [RiTa Twitterbots](http://rednoise.org/rita/gallery/RiTaTwitterbots) page in the Gallery.
And missing some resources (404):
![capture](https://cloud.githubusercontent.com/assets/2461812/14977403/1b3d96e0-1146-11e6-93f9-3d3481f5f3b2.PNG)

**Comment by dhowe** [comment]
First issues is fixed (and will update when a new version is pushed).
And lets ignore the 2nd issue.
