### ISSUE TITLE
Option to turn off version output RitaJS

### ISSUE THREAD

**Issue by UndergroundLabs** [dhowe/RiTa#331]
I'm using NodeJS 4.2.3 on Debian Jessie. I installed RitaJS using npm: `npm i rita --save-dev`

Whenever I include rita in my node project I always get a line of output on the command line that shows RitaJS version number.

I create a simple JS file and include like so:

    var rita = require('rita');

Running the file like so: `node index.js` produces the following output:

    [INFO] RiTaJS.version [1.1.35]

Is it possible to turn this output off?

**Comment by dhowe** [comment]
you should be able to say:

````js
RiTa.SILENT = true;
