### ISSUE TITLE
RitaJS isSentenceStart is not a function

### ISSUE THREAD

**Issue by UndergroundLabs** [dhowe/RiTa#332]
I'm trying to test `RiMarkov` using NodeJS. The website lacks any real examples of using it within Node. When attempting to generate a sentence from loaded text I get an error that ` i[s].isSentenceStart is not a function`.

NodeJS version 4.2.3 running RiTaJS 1.1.35 running on Debian Jessie.

**index.js**

```
var rita = require('rita');
var markov = new rita.RiMarkov(2);
markov.loadText("My name is James and I am a software developer");
sentences = markov.generateSentences(1);
```

**Run:**

    node index.js

**Output:**
```
node index.js 
[INFO] RiTaJS.version [1.1.35]
/home/sheldon/random-lies/node_modules/rita/lib/rita.js:35
var i=a.length,r=n.charAt(e-1),s=e>1?n.charAt(e-2):SP,t=e>2?n.charAt(e-3):SP,b=a.charAt(0),T=i>1?a.charAt(1):SP,l=i>2?a.charAt(2):SP;return b==b.toUpperCase()||T==T.toUpperCase()&&-1!=b.indexOf("`'\"([{<")||l==l.toUpperCase()&&("`"==b&&"`"==T||"'"==b&&"'"==T)||"_"==a||"<"==b?"?"==r||"!"==r||-1!=s.indexOf("?!.")&&-1!=r.indexOf("\"'}>)")||-1!=t.indexOf("?!.")&&"'"==s&&"'"==r?!0:"."!=r?!1:2==e&&s==s.toUpperCase()?!1:4==e&&"."==t&&s==s.toUpperCase()&&n.charAt(0)==n.charAt(0).toUpperCase()?!1:!0:!1},isW_Question:function(n){for(var a=RiTa.tokenize(n),h=0;h<W_QUESTION_STARTS.length;h++)if(equalsIgnoreCase(a[0],W_QUESTION_STARTS[h]))return!0;return!1},unescapeHTML:function(n){if(!n||!n.length)return n;var a=n.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&quot;/g,'"');return String.fromCharCodePoint=function(){for(var n=[],a=0;a<arguments.length;a++){var h=arguments[a];arguments[a]<65536?n.push(arguments[a]):arguments[a]<1114112&

TypeError: i[s].isSentenceStart is not a function
    at Object.RiMarkov._nextNodeForNode (/home/sheldon/random-lies/node_modules/rita/lib/rita.js:35:8427)
    at Object.RiMarkov.generateSentences (/home/sheldon/random-lies/node_modules/rita/lib/rita.js:35:6715)
    at Object.<anonymous> (/home/sheldon/random-lies/index.js:5:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3](url)
```

I've ran the tests and everything passes:

```
npm test

> rita@1.1.35 test /home/sheldon/random-lies/node_modules/rita
> gulp test-npm

[12:45:01] Using gulpfile ~/random-lies/node_modules/rita/gulpfile.js
[12:45:01] Starting 'clean'...
[12:45:01] Finished 'clean' after 6.12 ms
[12:45:01] Starting 'build-nolex'...
[12:45:01] Starting 'build-lex'...
[12:45:01] Finished 'build-nolex' after 33 ms
[12:45:01] Finished 'build-lex' after 17 ms
[12:45:01] Starting 'build'...
[12:45:01] Finished 'build' after 7.48 μs
[12:45:01] Starting 'test-npm'...
[12:45:01] Starting 'test-only'...
[INFO] Source: lib/rita.js
[12:45:01] Finished 'test-npm' after 164 ms
[INFO] RiTaJS.version [1.1.35]
[INFO] Testing LibraryStructure
[INFO] Testing RiTaEvent
[INFO] Testing RiString
[INFO] Testing RiTa
[INFO] RiTa-tests: skipping lancaster tests
[INFO] Testing RiGrammar
[INFO] Testing RiMarkov
[INFO] Testing UrlLoading

Global summary:
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 151   │ 2388       │ 0      │ 2388   │ 3147    │
└───────┴───────┴────────────┴────────┴────────┴─────────┘
```

**Comment by dhowe** [comment]
This should be fixed in v1.1.37 -- can you give it a try?

**Comment by UndergroundLabs** [comment]
Yes! It works. Many thanks @dhowe.

**Comment by tuneum** [comment]
I am also trying to run RiTa with NodeJS, but am getting the following error: 

**Error:** [RiTa] No sentence starts found! genSen=true

**Comment by dhowe** [comment]
Are there actual sentences in your input texts  (pls include a link to your input text here) ?

**Comment by Gingerguo** [comment]
RITA 1.3.11 Node 7.9
I meet the same trouble, when I use loadText, it works.
But when I load the "kiss.txt" which contains the exact same texts, it shows this error.
<img width="635" alt="screenshot 2018-02-19 18 36 56" src="https://user-images.githubusercontent.com/14199542/36401216-f4bb8d38-15a3-11e8-952d-8b061ba92537.png">
<img width="850" alt="screenshot 2018-02-19 18 36 47" src="https://user-images.githubusercontent.com/14199542/36401217-f4cb2964-15a3-11e8-81f0-dd865a745972.png">

**Comment by Gingerguo** [comment]
<img width="715" alt="screenshot 2018-02-19 18 39 50" src="https://user-images.githubusercontent.com/14199542/36401265-513c164a-15a4-11e8-9187-38edd1677af6.png">

**Comment by Gingerguo** [comment]
<img width="717" alt="screenshot 2018-02-19 19 27 12" src="https://user-images.githubusercontent.com/14199542/36402235-fda4c502-15aa-11e8-8fb0-4ca2bf47c9e5.png">

**Comment by Gingerguo** [comment]
Test in npm RunKit
[https://runkit.com/embed/5tww7aphfcoi](url)

**Comment by Gingerguo** [comment]
I also test on the front-end, same error
<img width="340" alt="screenshot 2018-02-19 21 47 41" src="https://user-images.githubusercontent.com/14199542/36405421-8fdd8d88-15be-11e8-9210-96f018aed3d6.png">

**Comment by cqx931** [comment]
@Gingerguo Hi! Sorry for taking so long to get back to you. 
I have checked your problem and it is not a RiTa issue.
Please use callback when you are loading from an url, otherwise the when the program runs generateSentence(), the text is not yet loaded in RiMarkov.
Example:
![image](https://user-images.githubusercontent.com/3056154/36569243-010e1f8e-17fb-11e8-8f62-004faa8878a5.png)

**Comment by Gingerguo** [comment]
Great! Thank you for answering me!
