### ISSUE TITLE
Remove [INFO] RiTaJS.version [1.1.37] from NodeJS

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#333]
Simply a line of ```var rita = require('rita');``` produces the console msg  ```[INFO] RiTaJS.version [1.1.37]``` in NodeJS environment.

Perhaps we can disable this info output?

**Comment by dhowe** [comment]
Yes, we should. I will look into it

**Comment by dhowe** [comment]
fixed in 6a9b638
