### ISSUE TITLE
RiTa.SILENT still prints Rita version when set to true

### ISSUE THREAD

**Issue by UndergroundLabs** [dhowe/RiTa#337]
Rita Version: **1.1.38**
Node version: **6.2.0**
OS: **Ubuntu 14.04** 

I am using nodeJS to output some text based on a grammar. All works fine, but every time I run the script at the terminal it prints the version number:

    [INFO] RiTaJS.version [1.1.38]

I understand that it can be silenced, except it doesn't appear to be working. Running the script below still prints the version number even though `Rita.SILENT` is set to true.

    import Rita from 'rita'

    Rita.SILENT = true;
    Rita.RiTa.SILENT = true;

    let grammar = {
        "<start>": "<hello>",
        "<hello>": [
            "Hey",
            "Hi",
            "Hello",
            "Holla"
        ]
    }

    console.log(Rita.RiGrammar(grammar).expand());

**Comment by dhowe** [comment]
@cyrus, can you confirm this?

**Comment by dhowe** [comment]
Fixed in v1.1.39 -- please verify...

**Comment by UndergroundLabs** [comment]
Works fine now.

**Comment by dhowe** [comment]
FYI, you shouldn't need it in node in any case -- version# printing is off by default
