### ISSUE TITLE
RiTa.isQuestion is not a function

### ISSUE THREAD

**Issue by ohenepee** [dhowe/RiTa#338]
![rita](https://cloud.githubusercontent.com/assets/15159487/16206520/50cfb1c4-3718-11e6-8746-8c14d1eeec3b.jpg)

NodeJS 6.2.0 (Linux)

```
var rita = require('rita');

var sentence = "Have you done the assignment";
var features = rita.RiString(sentence).features();

console.log(features);

var possibility = rita.isQuestion(sentence);

console.log(possibility);
```

**Comment by dhowe** [comment]
```
var rita = require('rita');

var sentence = "Have you done the assignment";
var features = rita.RiString(sentence).features();
console.log(features);

var possibility = rita.RiTa.isQuestion(sentence);
console.log(possibility);
```

**Comment by ohenepee** [comment]
Thanks! I think you'll have to make an update to the isQuestion function since "Have you.." and its like always end up as questions as long as it occurs in a single sentence statements and not a multi-sentence statement.

E.g. Do you know how it feels to hold a live salmon [QUESTION: no need for ?]

E.g. Do you know how it feels to hold a live salmon. You have no idea

Hope it helps... thanks for this wonderful package btw

**Comment by dhowe** [comment]
Yes, I've just updated the code to include words like HAVE... These should be live in the next release.
Thanks for your help!

**Comment by ohenepee** [comment]
Any rough time frame I can expect this "next release"?

**Comment by dhowe** [comment]
Sometime today I hope...
