### ISSUE TITLE
Fix NPM test of cdnjs

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#346]
So this is the error for not passing NPM test on cdnjs 
```bash
$ npm test

> cdnjs@1.0.0 test /Users/git/cdnjs
> vows

to start, pass the "run" arg
········· ······························✗·  
   
   
    rita 
      ✗ rita: useless fields check 
        » rita: we don't need bin, jshintConfig, eslintConfig, styles, install, typescript, browserify, browser, jam, jest, scripts, devDependencies, main, peerDependencies, contributors, bugs, gitHEAD, issues, files, ignore, engines, engine, directories and maintainers fields in package.json // valid-packages-test.js:277 
  ✗ Broken » 40 honored ∙ 1 broken (0.035s) 
  npm ERR! Test failed.  See above for more details.
```

Because we have `main`, `bugs` and `engines` in package.json.

**Comment by CyrusSUEN** [comment]
It seems we can keep 2 separate package.json in NPM and cdnjs. I've made the changes to package.json in the PR to cdnjs: https://github.com/cdnjs/cdnjs/pull/8446/commits/dea7542c543e33270f2251e51da6bd5bdcfa2afb

**Comment by CyrusSUEN** [comment]
Passed the [CI test](https://circleci.com/gh/cdnjs/cdnjs/11126). Closing this.

**Comment by dhowe** [comment]
What is the status?

**Comment by CyrusSUEN** [comment]
> the status?

Turns out cdnjs requires developers to pass **its own NPM test** so that the libraries submitted are in their format. (see: https://github.com/cdnjs/cdnjs/pull/8446/commits/dea7542c543e33270f2251e51da6bd5bdcfa2afb)
I've checked that the package.json for submitting to cdnjs is unique to cdnjs that we do not need to modify the one in RiTaJS' repo.
