### ISSUE TITLE
Use https version of RiTa official page when possible

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#347]
Just a finding when submitting RiTa to cdnjs: 
On the [RiTa NPM page](https://www.npmjs.com/package/rita) it shows `https` but it actually uses the `http` version:
![screen shot 2016-07-06 at 3 37 32 pm](https://cloud.githubusercontent.com/assets/2461812/16610725/b32c2d9c-438f-11e6-96d7-d7014bf84fcc.png)

**Comment by CyrusSUEN** [comment]
Just changed the `package.json ` in RiTaJS: https://github.com/dhowe/RiTaJS/pull/29

**Comment by dhowe** [comment]
can this be closed?

**Comment by CyrusSUEN** [comment]
> can this be closed?

Do you need to update the npm package website page? https://www.npmjs.com/package/rita#about-the-project

**Comment by dhowe** [comment]
It will be auto-updated on the next release...

**Comment by CyrusSUEN** [comment]
OK. Closing this one.
