### ISSUE TITLE
Remove executable permission from dist files for cdnjs

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#348]
So cdnjs requires the JavaScript files to have non-executable file permission.

Right now the dist files generated by `gulp build` in Github repo has chmod permission `755`. We should make it `644` (without executable file permission) to comply with the cdnjs specification.

**Comment by CyrusSUEN** [comment]
PV: https://github.com/dhowe/RiTaJS/pull/30

**Comment by dhowe** [comment]
Done - please verify and close

**Comment by CyrusSUEN** [comment]
> verify and close

Verified on Mac. But not working on Windows. (not a big deal though). Closing.
