### ISSUE TITLE
Add rita-tiny.js (minified, core-only) to npm

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#349]

**Comment by dhowe** [comment]
Fixed with 583831f7
please verify

**Comment by CyrusSUEN** [comment]
Verified. There is `rita-tiny.js` in addition to `rita.js` in `\lib`.

There is also another way of doing it by providing a source map (.map) file along with a minified (.js) file as I've seen in other libs in cdnjs.
See: [source map npm package](https://www.npmjs.com/package/source-map) and [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.1ce2c87bpj24)
