### ISSUE TITLE
Update node js example code or the API

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#350]
Some developers are confused about the RiTaJS API in node js environment.

Suggestion:
modify example from 
```node
var rita = require('rita');
var rs = rita.RiString("The elephant took a bite!");
console.log(rs.features());
```

to
```node
var rita = require('rita');

var version = rita.RiTa.VERSION;
console.log(version);

var rs = rita.RiString("The elephant took a bite!");
console.log(rs.features());
```

Or should we instead get rid of the `RiTa` variable in nodejs environment to provide a more intuitive way of using it?

**Comment by dhowe** [comment]
I think it would be possible to export the RiTa object's functions and properties (all of which are static) directly, though this would not help with other objects (e.g., RiString). Thus, one could write:

```node
var rita = require('rita');
var version = rita.VERSION("The elephant took a bite!");
console.log(version);

var rs = rita.RiString("The elephant took a bite!");
console.log(rs.features());

var vrb = rita.conjugate("The elephant took a bite!");
console.log(vrb);
```


We would need to look into what code changes this requires, and how it affects the other environments (browser, p5js, etc.)

**Comment by dhowe** [comment]
see #360
