### ISSUE TITLE
Add video to website

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#352]
https://www.youtube.com/watch?v=lIPEvh8HbGQ
perhaps somewhere on homepage?

**Comment by cqx931** [comment]
This is cool! A video tutorial...
Though I don't think the video matches the style of homepage...
I would suggest placing it under Learning,  a new page or under tutorial.
Or, if you want to have it somewhere on homepage, maybe we can have a whole section for learning and also including the video there.

**Comment by dhowe** [comment]
how about http://rednoise.org/rita/tutorial/index.php ?

**Comment by cqx931** [comment]
how about something like this? And it links directly to the youtube page.
![screen shot 2016-09-23 at 3 32 42 pm](https://cloud.githubusercontent.com/assets/3056154/18777701/2d707486-81a3-11e6-9cfc-ed342d152cc7.png)

**Comment by dhowe** [comment]
good, but lets put it at the top

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/353

**Comment by dhowe** [comment]
Lets add this one as well: https://www.youtube.com/watch?v=VaAoIaZ3YKs

**Comment by cqx931** [comment]
Added https://github.com/dhowe/RiTa/pull/381
