### ISSUE TITLE
Links don't lead back to homepage

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#355]
On: http://rednoise.org/rita/tutorial/index.php

should leave back to home page, but doesn't (same with reference).
fix if easy, or just remove the link if not

![screen shot 2016-10-03 at 2 58 48 am](https://cloud.githubusercontent.com/assets/737638/19022943/7a948a26-8915-11e6-8f86-e0a10e8a2623.png)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/RiTa/pull/359/commits/e46b40fd44e0299c701a9f11b9a7bd92f9d5ca82
