### ISSUE TITLE
Create version of lexicon with most common 1000 words

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#356]
http://www.ef.com/english-resources/english-vocabulary/top-1000-words/
https://gist.github.com/deekayen/4148741

To be included with the default installation of rita.js (as opposed to no lexicon, as we currently do)

**Comment by cqx931** [comment]
Do you mean to extract the data of these 1000 words from the current rita_dict.js, and create a new file(rita_dict_1000.js) that will be put into RiTaJS/src?

**Comment by dhowe** [comment]
exactly

**Comment by cqx931** [comment]
I have writen a little java programme in docgen to generate the new 1000 words dict file from this https://gist.github.com/deekayen/4148741. However, there are a few words that we don't have in rita_dict, please see below for the list of words:
<img width="906" alt="screen shot 2016-10-03 at 11 29 20 pm" src="https://cloud.githubusercontent.com/assets/3056154/19043103/51290e3a-89c1-11e6-8ae6-86ec2d338c45.png">

I think we can ignore words like "children", "don't", "won't", but I'm not sure about those numerical numbers and other words. Shall we add them to both dict files?

**Comment by dhowe** [comment]
Yes, I suppose we should.  You can either look them up manually or use the LTS engine to generate the features, but either way we will have to check them by hand. Actually some of these may already be in the [CMU dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict?in=second), in which case we can just add the POS data

**Comment by cqx931** [comment]
cool, I will add them into both dict them. And after I change these two, am I going to first commit to RiTaJS?(into src, two files, rita_dict.js and rita_dict_1000.js) And later leave the current java file that I used to generate the rita_dict_1000.js in docgen folder in RiTa?

**Comment by dhowe** [comment]
Yes, that sounds right. The rita_dict.js in RiTaJS is the 'truth'. The one in Rita is generated from that one by running the /RiTa/scripts/update-dict.sh. So once the files are updated in RiTaJS and all the tests still pass, then run that script in RiTa, check that all RiTa tests still pass, then submit the PR

**Comment by cqx931** [comment]
oh yes, many of them. So we are going to exclude these right?

was had did been came does went took began told knew heard stood gave ran brought felt sat kept wrote grew sent caught born bought meant

**Comment by cqx931** [comment]
Please check
https://github.com/dhowe/RiTaJS/pull/31
https://github.com/dhowe/RiTa/pull/361

![image](https://cloud.githubusercontent.com/assets/3056154/19065100/2b969178-8a44-11e6-9849-2826c19a284f.png)

**Comment by dhowe** [comment]
what are the 29 deleted words, plurals, or conjugated verbs?

**Comment by cqx931** [comment]
Mainly conjugated verbs and also "children", "don't", "won't".

**Comment by dhowe** [comment]
Ok, we can remove these later, if/when we remove them from the full dictionary.

**Comment by cqx931** [comment]
latest update
https://github.com/dhowe/RiTaJS/pull/45/commits/c2225f822ac5199a6b9d94179aece7cdc6cacd58
