### ISSUE TITLE
Nav-bar aligns too far right on wide screen

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#358]
![screen shot 2016-10-03 at 3 10 37 am](https://cloud.githubusercontent.com/assets/737638/19023027/0cfcb6a8-8917-11e6-83ae-380b22f47c1c.png)

**Comment by cqx931** [comment]
fixed with centered header https://github.com/dhowe/RiTa/pull/359/commits/63f0ef2179b606b67d7add20b37d8a517a323164
