### ISSUE TITLE
API change for RiTaJS

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#360]
Consider the following example code from the [npm README](https://www.npmjs.com/package/rita):

```
var rita = require('rita'),
  rs = rita.RiString("The elephant took a bite!"),
  features = rs.features();
```

One imagines they would be able to say console.log(rita.VERSION) and get some output. However this is not the case. Instead they would have to write: 

```
console.log(rita.RiTa.VERSION);
```

This is because the require function returns a wrapper object containing all the rita objects, including RiTa:

```
{
   RiTa: {},
   RiString: {},
   RiLexicon: {},
  ...
}
```

Instead I propose that the RiTa object itself is returned from require, with the other objects (RiString, RiLexion, etc.) as properties:

```
RiTa: {
  RiString: {},
  RiLexicon: {},
  ...
  pluralize(): function() { ... }
  ...
}
```

This would allow either of the following syntaxes:

```
var RiTa = require('rita'),
  rs = RiTa.RiString("The elephant took a bite!"),
  version = RiTa.VERSION;
```

```
var RiTa = require('rita'),
  RiString = RiTa.RiString,
  rs = new RiString("The elephant took a bite!"),
  version = RiTa.VERSION;
```

Of course this would require significant changes in our examples and tests. Thoughts?

**Comment by cqx931** [comment]
It does make sense or easier to understand if the user can do rita.version directly... 
But as you said, that is a big update almost everywhere... 
not sure about making changes with such great influence to achieve something nice to have...

**Comment by dhowe** [comment]
I believe this can be done while still supporting our current method for backwards compatibility. In which case we just have to update our examples...

**Comment by dhowe** [comment]
This is done, and actually only affects npm examples. As best I can tell, there are only 2 cases: tonic.js and README.md for the RiTaJS repo  on github, neither of which are affected. 

@cqx931 any others you can think of? if not, please close
