### ISSUE TITLE
mistakes in rita_dict

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#363]
Shouldn't it be like this?
caving vbg
cavin nn
![image](https://cloud.githubusercontent.com/assets/3056154/19100784/644592de-8af4-11e6-9f6a-4b2fd905d796.png)

**Comment by dhowe** [comment]
'caving' -> vbg

'cavin' can be removed

**Comment by cqx931** [comment]
actually, I find many cases like this.For the following words, they all have another entry that ends with 'in' instead of 'ing'... Shall we handle all these cases in the same way you mentioned?

talking, busting,nothing, killing, dusting, thinking, asking

**Comment by dhowe** [comment]
yes
