### ISSUE TITLE
Implement pos-tagging of irregular plural nouns

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#368]
We should be able to handle these with NULL_PLURALS, SINGULAR_RULES, & PLURAL_RULES

We would have to integrate a check of these rules whenever a lexicon lookup fails in the posTagger, somewhere around [here](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L3128)...

```
If a word has no entry in the lexicon {
  If it ends with s or es, we strip those and check again {
    If still no match, we check/apply SINGULAR_RULES
    If still no match, we default to 'nns'
  }
  else {
     We check/apply PLURAL_RULES
     If  no match, we default to 'nn'
  }
}
```

Examples:
-----------------------
media nns nn
millennia nn nns
consortia nns nn
concerti nns
consortia nns nn
teeth nns 
minutiae nns
septa nns
millennia nn nns
swine nns
termini nns
cognoscenti nns
larvae nns
vertebrae nns
memorabilia nns
media nns nn
pepperoni nns
alveoli nns
timpani nns
lice nns
multimedia nns
sera nns
maria nns

**Comment by cqx931** [comment]
This is what I have in my mind:
```
If a word has no entry in the lexicon {
  If it ends with s or es, we strip those and check again {
    If there is a match -> nns  [ Ex:boxes]
    If still no match, we singularize the word 
       If there is a match -> nns [Ex:memories]
       If still no match, we default to 'nns'
   //so actually if the default here goes to 'nns', we can just tag all the words that ends with "es"/"s" and also can't be find in the library to 'nns'?Because all the cases leads to 'nns'...
  }
  else {
     We singularize the word
     If there is a match -> nns [Ex:teeth]
     If no match, we default to 'nn'
  }
}
```

**Comment by dhowe** [comment]
If a word has no entry in the lexicon {
  If it ends with s or es, we strip those and check again {
    If there is a match -> add 'nns' to choices[i]  [ Ex:boxes]
    If still no match, we singularize the word 
       If there is a match -> add 'nns' to choices[i] [Ex:memories]
    Use default of 'nns'
  }
  else {
     We singularize the word
     If there is a match -> add 'nns' to choices[i]  [Ex:teeth]
     Use default to 'nn'
  }
}
```
?

**Comment by cqx931** [comment]
RiTa and RiTaJS all done
