### ISSUE TITLE
Add to RiTa Gallery

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#376]
@cqx931 if you think any of these are not worth posting, just let me know...

http://www.brnart.com/invokeobject-object/
http://ciid.dk/education/portfolio/idp15/courses/secret-life-of-objects/projects/bookshelf-writer/
http://sarahmak.es/nightTweets
https://elmcip.net/creative-work/mirroring-tears-visages (link-only)

**Comment by cqx931** [comment]
http://sylviatp.com/screen/snake.php the applet way of presenting processing online doesn't seem to work anymore.

**Comment by dhowe** [comment]
Yes, it does not (or not reliably at least)... If you think the work is interesting enough to warrant inclusion anyway (with screen shots and source code), we can do that. But my sense is that it isn't.

**Comment by cqx931** [comment]
Then I will not include that one...
So for these works are we going to host the intro page and the work on rednoise like what we did before?

**Comment by dhowe** [comment]
Good question. Let me think about this...

**Comment by cqx931** [comment]
@dhow Please let me know when you decided how you would like this to be presented.

**Comment by cqx931** [comment]
Updated here: https://github.com/dhowe/RiTa/pull/387

Currently I used a link for [NightTweets](http://sarahmak.es/nightTweets), as that page has many tweeter widget and other things that are hard to just simply right click and save. If you would like to have one introduction page on the website, I could recreate a more simple page based on the materials on her website.

**Comment by dhowe** [comment]
works for me...

**Comment by dhowe** [comment]
@cqx931 please add: http://www.farbetextemotion.de/?site=poems&lang=en
