### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#379]
/RiTaJS/test/html/RiLexicon-tests.html

![screen shot 2016-10-25 at 9 02 52 pm](https://cloud.githubusercontent.com/assets/737638/19716026/e6a9f1e6-9b8b-11e6-9c4d-f218353d2d25.png)

**Comment by dhowe** [comment]
also please figure out why our travis build still shows as passing: https://travis-ci.org/dhowe/RiTaJS ??

**Comment by cqx931** [comment]
Because we skip the Relixicon_tests deliberately in the build process. Why was the reason to skip it originally?
https://github.com/dhowe/RiTaJS/blob/master/gulpfile.js#L267
I can only see these failing tests if I go to RiLexicon-tests.html, it is also not included in AllTests.html.

**Comment by dhowe** [comment]
I think that because they were too slow... but maybe check the times again with lexicon enabled
This is *exactly* the situation we want to avoid, where tests are failing but we dont know about it

**Comment by cqx931** [comment]
fixed with https://github.com/dhowe/RiTaJS/pull/46
