### ISSUE TITLE
RiTaJS tests not failing in build

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#382]
This is top priority as current (broken) version has already been pushed to npm.
@cqx931 -- please verify ASAP that ALL RiTaJS tests are passing ..

![screen shot 2016-11-16 at 3 11 23 am](https://cloud.githubusercontent.com/assets/737638/20319776/65949f32-abaa-11e6-8300-17af749cdcc4.png)

![screen shot 2016-11-16 at 3 10 21 am](https://cloud.githubusercontent.com/assets/737638/20319741/41d74072-abaa-11e6-8444-96d9b0559a48.png)

Strangely the build still passes in travis: https://travis-ci.org/dhowe/RiTaJS

**Comment by dhowe** [comment]
Before closing this ticket, we need to figure out why we were not notified (by travis-ci) of a failing build see https://travis-ci.org/dhowe/RiTaJS

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/21002261/baafa0a4-bd5f-11e6-903d-ceb427b1ce2b.png)

Above is the logging message from travis.
It runs `gulp test-npm` instead of `gulp test`(what I normally do) and if I understand correctly, what tests are executed in travis is defined in [package.json](https://github.com/dhowe/RiTaJS/blob/master/package.json#L28).

I don't really understand why the destDir is 'lib' instead of 'dist' for 'test-npm'... but to solve this I think we either need to change the destDir for 'test-npm' to 'dist', or we change the command line to 'gulp test' in package.json.
https://github.com/dhowe/RiTaJS/blob/master/gulpfile.js#L196

**Comment by cqx931** [comment]
Any response to this? This is still not fixed...

**Comment by dhowe** [comment]
The first question is why our local tests haven't failed?

**Comment by cqx931** [comment]
1.Is it the same if I do `gulp test-npm` in local and what travis does online?
2. Why gulp test-npm uses lib folder while gulp test uses dist folder?
3.This is the error message I got if I do `gulp test-npm` 

```
{ Error: Cannot find module '/Users/cqx931/RiTaJS/lib/rita'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at _require (/Users/cqx931/RiTaJS/node_modules/qunit/lib/child.js:55:19)
    at Object.<anonymous> (/Users/cqx931/RiTaJS/node_modules/qunit/lib/child.js:173:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
  message: 'Cannot find module \'/Users/cqx931/RiTaJS/lib/rita\'' }
{ files: 0,
  assertions: 0,
  failed: 0,
  passed: 0,
  runtime: 0,
  tests: 0,
  coverage: 
   { files: 0,
     statements: { covered: 0, total: 0 },
     branches: { covered: 0, total: 0 },
     functions: { covered: 0, total: 0 },
     lines: { covered: 0, total: 0 } } }
```

**Comment by cqx931** [comment]
Also test-npm tests with "rita.js"
While a gulp test tests with "rita-full.js"

**Comment by dhowe** [comment]
once packaged for npm, "rita-full.js" becomes lib/rita.js 
so 'npm test' runs this code correctly after an npm install

> This is the error message I got if I do gulp test-npm

To run this test correctly, you need to do:
1. build an npm version
$ gulp npm.build
2. unzip it
$ tar xfz rita-VERSION.tgz 
3. run the test
$ cd package && gulp test-npm

**Comment by dhowe** [comment]
@cqx931 I've updated the build env on travis, and ritajs passes -- can you break some test, then commit, then check the travis result to make sure it fails, then fix whatever you break

**Comment by cqx931** [comment]
Al the tests are passed after I break two test cases: https://travis-ci.org/dhowe/RiTaJS/builds/223530376

**Comment by dhowe** [comment]
you committed the result, then waited for travis to run again?

**Comment by dhowe** [comment]
@cqx931 note that I've added a 'test-npm-test' task in gulp, which does the above. it is a bit slow as it has to install a bunch of dependencies, but it allows one to test the npm package without all the individual steps (close once your read this and test it)

**Comment by cqx931** [comment]
tested
