### ISSUE TITLE
Reference: check that each function (in JSON files) has an 'example' tag

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#383]

**Comment by cqx931** [comment]
can you explain more on this?

**Comment by dhowe** [comment]
This is for version 1.6 (see Milestone to right...)

But [RiGrammar.addRule()](https://rednoise.org/rita/reference/RiGrammar/addRule/index.php) has an example, and [RiGrammar.addRule()]( https://rednoise.org/rita/reference/RiGrammar/hasRule/index.php) does not

**Comment by cqx931** [comment]
just adding the example tag? Or you mean also adding short code example if there is none.

**Comment by dhowe** [comment]
The latter.  However you always need to make sure that the JSON is still valid after updating it, by building the docs via ant:

     [java] [INFO] DocGen.version [0.20]
     [java] Error parsing the JSONObject!
     [java] CWD: /Users/dhowe/Documents/Projects/RiTa
     [java] DATA: docsException in thread "main" java.lang.RuntimeException: rita.json.JSONException: Expected a ',' or '}' at 10476 [character 56 line 349]
     [java] OUTPUT: web/reference/
     [java] 	at rita.docgen.DocGenerator.parseJSON(Unknown Source)
     [java] 	at rita.docgen.DocGenerator.go(Unknown Source)******     RiTa     ******
     [java] 	at rita.docgen.DocGenerator.main(Unknown Source)
     [java] Caused by: rita.json.JSONException: Expected a ',' or '}' at 10476 [character 56 line 349]  Template : docs/php/template.php
     [java] 	at rita.json.JSONTokener.syntaxError(Unknown Source)
     [java]   DocFile : docs/json/RiTa.json
     [java] 	at rita.json.JSONObject.<init>(Unknown Source)
     [java] 	at rita.json.JSONTokener.nextValue(Unknown Source)
     [java] 	at rita.json.JSONArray.<init>(Unknown Source)
     [java] 	at rita.json.JSONTokener.nextValue(Unknown Source)
     [java] 	at rita.json.JSONObject.<init>(Unknown Source)
     [java] 	at rita.json.JSONTokener.nextValue(Unknown Source)
     [java] 	at rita.json.JSONObject.<init>(Unknown Source)
     [java] 	at rita.json.JSONObject.<init>(Unknown Source)
     [java] 	... 3 more
     [java] Java Result: 1

**Comment by cqx931** [comment]
How do I build the docs via ant?

**Comment by dhowe** [comment]
can use 'build' or 'make.docs' task

**Comment by dhowe** [comment]
lets add this to the devFAQ once fixed

**Comment by cqx931** [comment]
Shall I update all these files when I create a new PR?
```
        modified:   ../java/rita/docgen/DictWithoutConjugatedVerbs.java
	modified:   ../java/rita/docgen/DocGenerator.java
	modified:   ../web/download/rita-full.js
	modified:   ../web/download/rita-full.min.js
	modified:   ../web/download/rita.jar
	modified:   ../web/download/rita.js
	modified:   ../web/download/rita.min.js
	modified:   ../web/download/rita_dict.js
	modified:   ../web/reference/RiTa/RiTa.VERSION/index.php
	modified:   ../web/reference/RiTa/RiTa.isAbbreviation/index.php
	modified:   ../web/reference/RiTa/RiTa.isQuestion/index.php
	modified:   ../web/reference/RiTa/RiTa.isW_Question/index.php
	modified:   ../web/reference/RiTa/RiTa.randomItem/index.php
	modified:   ../web/reference/RiTa/RiTa.randomOrdering/index.php
	modified:   ../web/reference/RiTa/RiTa.splitSentences/index.php
	modified:   ../web/rita.zip
```

**Comment by dhowe** [comment]
Sure, thats fine

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/RiTa/pull/416

Examples are now added to all entries, double checked syntax and spacing.

**Comment by cqx931** [comment]
updated devFAQ https://github.com/dhowe/RiTa/wiki#how-do-i-build-docs
