### ISSUE TITLE
Include 1000-word dictionary for default cases (and npm)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#384]

**Comment by cqx931** [comment]
what do you mean exactly by default cases?
Modifying the gulpfile.js so that when do 'gulp build' ReLixicon and 1000-word dictionary will be included for rita.js?
And what is for npm?

**Comment by dhowe** [comment]
> what do you mean exactly by default cases?

![image](https://cloud.githubusercontent.com/assets/737638/23895835/2e260bae-08e2-11e7-8174-01eeda6749eb.png)

> Modifying the gulpfile.js so that when do 'gulp build' ReLixicon and 1000-word dictionary will be included for rita.js?

correct

> And what is for npm?

npm should uses the full dictionary, so no change needed here (though pls double check)

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTaJS/pull/49

I have modified gulpfile.js accordingly, but not sure about npm, bower and rita.tiny.js

**Comment by dhowe** [comment]
- [ ] Add no-lex tests that test things in the 1000-word lexicon only (test-nolex), and don't test words not in 1000-lexicon (should also run for npm)
- [ ] Double-check we have full-set of tests with full lexicon and 1000-word lexicon

**Comment by cqx931** [comment]
- Tiny: rita.js only  154KB
- Small: rita.js + rilexicon.js + dict1000  209KB
- Medium: rita.js + rilexicon.js + dict1000 + rita_lts.js  510KB
- Large: rita.js + rilexicon.js +  dictFull + rita_lts.js  1.6MB

**Comment by dhowe** [comment]
Ok, and what happens when you try to analyze a word in Tiny, or a word not in the dict1000 in Small?

**Comment by cqx931** [comment]
For example, if I do `RiTa.getPosTags("age")` in Tiny,
I got a warning message "No RiLexicon found: part-of-speech tagging will be inaccurate!" and also an error message "rita-tiny.js:3258 Uncaught TypeError: Cannot read property 'containsWord' of undefined" from [this line](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L3083)
`if (!lex.containsWord(words[i]))`
After I fix that error by doing `if (!lex || !lex.containsWord(words[i]))`,
the pos tag analyzing works but not Phonemes,Stresses and Syllables, nothing is returned from those.

For Small, it doesn't work simply removing LTS, as we don't have any code handling the case when RiLexicon exist but without LTS.
I got the error message " Uncaught ReferenceError: _RiTa_LTS is not defined" and nothing from rita is working.

**Comment by dhowe** [comment]
Should get the proper warnings now (and no errors) -- can you check several cases with small/tiny/medium?

**Comment by dhowe** [comment]
perhaps we should standardize on [tiny, medium, large]:

- rita.js (core-only, no lexicon) -> tiny
- rita-small.js (1k-word lexicon + lts) -> medium
- rita-full.js (35k-word-lexicon + lts) -> large

`(as is, but add 2 entries for 'small')`

npm:

- rita-micro.js (core-only, no lexicon) -> tiny
- rita.js (35k-word-lexicon + lts) -> large (default)

browser/p5.js: 
http://rednoise.org/rita/download/rita.min.js  -> tiny
http://rednoise.org/rita/download/rita-full.min.js (comment)  -> large

bower: 
- dist/rita.js  -> tiny
<script src="./bower_components/rita/dist/rita.min.js"></script>


browserify: (uses npm, but add note about rita-micro.js) -> large 
- rita.js (35k-word-lexicon + lts) -> large (default)

**Comment by cqx931** [comment]
https://github.com/cqx931/RiTaJS/commit/3bbc9e19e06117f33ffc35c74412de0427a3319b
I have updated the gulp file to build tiny, medium, and large from `gulp build`, also modified `npm.build` to match with the requirements above.

However, it's not clear to me what to change for browser/p5.js and browserify

**Comment by dhowe** [comment]
Both browser/p5.js and browserify should use the tiny version of RiTa (if this is already correct in the build, then we are good). 

Changes above refer primarily to the documentation (quick-start, etc.), which needs to be updated.

**Comment by cqx931** [comment]
this can be closed
