### ISSUE TITLE
Console error message for Examples

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#385]
Haiku Example in p5js, chrome
<img width="1232" alt="screen shot 2016-11-16 at 1 34 12 pm" src="https://cloud.githubusercontent.com/assets/3056154/20335938/77ef0f1c-ac01-11e6-9fc5-cb01ca1c299f.png">

Kafgenstein & KeyWordsInContext, p5js & dom, firefox & chrome
<img width="1204" alt="screen shot 2016-11-16 at 1 33 30 pm" src="https://cloud.githubusercontent.com/assets/3056154/20335960/98c74736-ac01-11e6-8195-252bb6868d55.png">

<img width="528" alt="screen shot 2016-11-16 at 1 31 07 pm" src="https://cloud.githubusercontent.com/assets/3056154/20335893/2725c0a8-ac01-11e6-8961-97fe9ff897e1.png">

**Comment by dhowe** [comment]
I don't see the first one:

![screen shot 2016-11-16 at 3 34 17 pm](https://cloud.githubusercontent.com/assets/737638/20338447/329c7b1e-ac12-11e6-9b2a-2b9f38195a18.png)

**Comment by cqx931** [comment]
fixed the prism error here. I also don't see the other error message right now... so closed for now.
https://github.com/dhowe/RiTa/pull/388
