### ISSUE TITLE
Runkit version

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#386]
https://runkit.com/npm/rita
On runkit, the version number is still on 1.1.391. Does it need an update?
<img width="922" alt="screen shot 2016-11-16 at 1 46 13 pm" src="https://cloud.githubusercontent.com/assets/3056154/20336167/109a7f98-ac03-11e6-9a01-e449c486cc67.png">

**Comment by dhowe** [comment]
yes, apparently... though i have no idea where that version # comes from

**Comment by cqx931** [comment]
According to what is said here, https://runkit.com/npm/, the content as well as the code snippet on that special page should be provided by us... does Cyrus have an account that manages all the content?

**Comment by dhowe** [comment]
I think what is used in runkit comes from our package.json (and tonic.js file), but its not clear to me where the version comes from:

  "tonicExampleFilename": "tonic.js"

![screen shot 2016-11-16 at 3 46 39 pm](https://cloud.githubusercontent.com/assets/737638/20338753/e9777f4a-ac13-11e6-9f1b-142a982280d3.png)

**Comment by cqx931** [comment]
just saw a response from the link above
![image](https://cloud.githubusercontent.com/assets/3056154/20873229/5cfad496-bae0-11e6-8158-58b75e501aa0.png)

**Comment by dhowe** [comment]
can we close this?

**Comment by cqx931** [comment]
I think it still need a manual update according to the feedback, with the account which was used for the initial uploading.

**Comment by dhowe** [comment]
i have no memory of this

**Comment by cqx931** [comment]
Let me ask Cyrus then.

**Comment by dhowe** [comment]
If he doesn't have an answer, send a message to runkit and/or post on stackoverflow...

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
Does this feedback make sense to you? 
https://discuss.runkit.com/t/npm-package-updates/151/6?u=cqx931
I have no idea why he mentioned 0.1.391 instead of 1.1.39... Isn't the version number in package.json the semver, aren't they the same?

**Comment by dhowe** [comment]
Doesn't make sense. I've asked for clarification...

**Comment by cqx931** [comment]
I think I got what they mean now.
They are saying that '1.1.391' is greater than '1.1.51' according to semver's definition.
I have tested this according to the example here:
https://docs.npmjs.com/misc/semver

And I got true when I run
`semver.gt('1.1.391', '1.1.51') `

**Comment by dhowe** [comment]
yes, i saw that as well ... so we make the next version 1.1.600 at least

**Comment by dhowe** [comment]
runkit has cleared their cache now -- looks ok
