### ISSUE TITLE
Is there any way to retrieve indices of word beginnings?

### ISSUE THREAD

**Issue by trych** [dhowe/RiTa#391]
Hello there,
just got to know RiTa.js via Daniel Shiffman's videos and I am trying to use it in ExtendScript. I got it to work, but to make it work for my purposes, I would need a way to get the indices of word beginnings.

So, if I have a RiString()

```js
var rs = RiString("It was a dark and stormy night.");
```

I can do `rs.words()` to retrieve an array of words:

```js
["It", "was", "a", "dark", "and", "stormy", "night", "."]
```
and I can do something like `rs.pos()` to retrieve parts of speech:

```js
["prp", "vbd", "dt", "jj", "cc", "jj", "nn", "."]
```

However, how could I do something like `rs.wordIndices()`:

```js
[0, 3, 7, 9, 14, 18, 25, 30]
```

Or how could I retrieve this information any other way?

Thanks for looking into this.

**Comment by dhowe** [comment]
Ill have to double-check, but I'm not sure this is possible at the moment. What is the use-case?

**Comment by trych** [comment]
I would like to style words based on their pos in InDesign.

So I would like to first analyze the string via RiTa to later use that info to style the text that I have typeset in InDesign. Then only way for me to know where a RiTa-word begins would be via its index in the string.

The ExtendScript code would look something like this:

```js
textFrame.characters.itemByRange(9, 13).appliedCharacterStyle = myStyle;
```

So I would somehow need to be able to retrieve the beginning and end index of each word (well the end index I could retrieve easily myself, once I have the beginning index).

(Btw. InDesign also has its own way to separate a text into words – `textFrame.words` – but as punctuation is considered part of the word it stands next to, it would get out of sync pretty quickly when I start to mix RiTa words and ExtendScript words).

**Comment by dhowe** [comment]
See how far this gets you (I'm not sure its exactly what you need):

```
  RiString.prototype.splitWords = function() {

      var words = [], wordIdx = 0,
        txt = this.text().replace(/([\\?!\"\\.,;:@#$%&])/g, " $1 ").trim();

      for (var i = 0; i <= txt.length; i++) {
          if (txt.charAt(i) == ' ' || i == txt.length) {
              words.push( RiString(txt.substring(wordIdx, i)).set('charIndex', wordIdx) );
              wordIdx = i;
          }
      }

      return words;
  };

  var words = RiString("It was a dark and stormy and rainy night.").splitWords();
  for (var i = 0; i < words.length; i++) {
    console.log(words[i].text(), words[i].get('charIndex'));
  }

```

**Comment by trych** [comment]
Hi dhowe, thanks for your efforts, this *almost* seems to get me there.
However, it seems to mess up the counting. When I do:

```js
var s = 'It was a dark and stormy and rainy night.';
var r = RiString(s);
var words = r.splitWords();

for (var i = 0; i < words.length; i++) {
  $.writeln(words[i].text() + ": " + words[i].get('charIndex'));
}
```

it logs

```js
It: 0
 was: 2
 a: 6
 dark: 8
 and: 13
 stormy: 17
 and: 24
 rainy: 28
 night: 34
 .: 40
```

while it should log

```js
It: 0
was: 3
a: 7
// etc.
```

It somehow seems to add the whitespace to the word, which seems to mess up the counting. Any idea how to fix this?

**Comment by dhowe** [comment]
try this:

```
RiString.prototype.splitWords = function () {

  var words = [], wordIdx = 0, txt = this.text(),
    punct = /([\\?!\"\\.,;:@#$%&])/g;
  for (var i = 0; i <= txt.length; i++) {
    var c = txt.charAt(i), isPunct = punct.test(c);
    if (c == ' ' || c == '' || isPunct) {
      var word = txt.substring(wordIdx, i);
      words.push( RiString(word).set('charIndex', wordIdx) );
      if (!isPunct) i++;
      wordIdx = i;
    }
  }
  return words;
}
```

**Comment by trych** [comment]
Hi @dhowe,
thank you so much, this works now!

Not sure, if this also useful to other people who use RiTa in a browser context, but I think it might be helpful at times? If not, feel free to close this issue.

In case anyone is interested, here is a snippet of how I use the method. This uses the [basil.js library](http://basiljs.ch/) for ExtendScript in InDesign, that works similar to Processing/p5.js. I had to add some standard polyfills for string and array methods and I added the `splitWords()` method directly into the `rita-full.js` file. Works like a charm now.

```js
//@includepath "~/Documents/;%USERPROFILE%Documents";
//@include "basiljs/bundle/basil.js";
//@include "basiljs/lib/polyfills.js";
//@include "basiljs/lib/rita-full.js";

function draw() {

  var s = "It was a dark and stormy and rainy night.";

  // creates a text frame
  var tf = b.text(s, 50, 50, 200, 100);

  var r = RiString(s);
  var words = r.splitWords();

  for (var i = 0; i < words.length; i++) {
    if(words[i].pos() == "jj") {
      var startIx = words[i].get("charIndex");
      var endIx = startIx + words[i]._text.length - 1;

      // applies a fill color to a range of characters
      b.typo(tf.characters.itemByRange(startIx, endIx), "fillColor", b.color(255, 0, 0));

    }
  }

}

b.go();
```

![bildschirmfoto 2016-12-19 um 01 06 52](https://cloud.githubusercontent.com/assets/9803905/21297831/77cfe6b0-c587-11e6-8b28-391a4e704681.png)

Thanks again!

**Comment by academyofzhuang** [comment]
Another way to do it. This will give you the exact position at the original string.

 ````js
var s =  "It   was a dark and   stormy night.";
// var r = RiString(s);
// var words = r.splitWords();
var words = ["It", "was", "a", "dark", "and", "stormy", "night", "."]

var result = words.reduce(function (a, e) {
  var wordBeginPos = s.indexOf(e, a.pos)
  var wordLen = e.length
  var wordEndPos = wordBeginPos + wordLen
  a.acc.push({word: e, begin: wordBeginPos, end: wordEndPos})
  a.pos = wordEndPos
  return a
}, {acc: [], pos: 0})

console.log(result)
 ````

**Comment by trych** [comment]
Thanks @academyofzhuang, got this to work, too. Good to know that there is an alternative that works with an unaltered RiTA.js.

**Comment by trych** [comment]
Thanks @academyofzhuang, got this to work, too. Good to know that there is an alternative that works with an unaltered RiTA.js.
