### ISSUE TITLE
Increase contrast for text-heavy gallery image

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#394]
Whatever you can do to make the text in the images more pronounced. The Florence piece is the only critical one (before and after below):

![image](https://cloud.githubusercontent.com/assets/737638/24271759/588e1498-1055-11e7-87ee-efcdcc969289.png)

![image](https://cloud.githubusercontent.com/assets/737638/24271753/4e061b56-1055-11e7-917e-e75d594b4cc1.png)

**Comment by dhowe** [comment]
wei @cqx931

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/395
