### ISSUE TITLE
Add some simple tests for node

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#398]
add test/node-tests.js using require: 
* RiTa.functioName() with both syntaxes (which should both work)
* new RiTa.RiString()

new:

```
var RiTa = require('rita');
var words = RiTa.tokenize("The dog ate the cat.");
console.log(words);
```
        

old:

```
var RiTa = require('rita');
var words = RiTa.RiTa.tokenize("The dog ate the cat.");
console.log(words);
```

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/RiTaJS/pull/50
