### ISSUE TITLE
Check all functions have 'description' field specified (in json)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#40]

**Comment by dhowe** [comment]
Please check that each of the above methods have a good/clear description field in the docs. For any that are missing, add the description to the appropriate json documentation file. If you are not sure of the function, ask me...

````$ ls RiTa/docs/json/Ri*
docs/json/RiGrammar.json  docs/json/RiString.json   docs/json/RiText.json
docs/json/RiLexicon.json  docs/json/RiTa.json       docs/json/RiWordNet.json
docs/json/RiMarkov.json   docs/json/RiTaEvent.json

**Comment by CyrusSUEN** [comment]
Made some changes here: https://github.com/dhowe/RiTa/pull/111/files

Things I've not changed but requires your attention:  

### [RiTa website reference page](https://rednoise.org/rita/reference/index.html)
[toCharArray()](https://rednoise.org/rita/reference/RiString/toCharArray/index.html) (Error 404 not found)

### RiWordNet.json
getRandomExamples (needs better description)



### RiGrammar.json
getRule() (entry not found in the json doc)
setGrammar() (entry not found in the json doc)

### RiTa.json
RiTa.p5Compatible() (entry not found in the json doc)
isStopWord (hidden)

**Comment by CyrusSUEN** [comment]
Updated docs.json: https://github.com/dhowe/RiTa/pull/176

### RiWordNet.json
getRandomExample

**Comment by dhowe** [comment]
status?

**Comment by CyrusSUEN** [comment]
> status?

All done. Can be closed
