### ISSUE TITLE
[RiLexicon] rhymes() returns no result if the given word is not in the dictionary

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#400]
If a word is not in the dictionary, it makes sense to me to use LTS to get the phonemes first and return corresponding rhymes
See the test case for rita-medium(lex1000 + rilexicon + LTS)
https://github.com/dhowe/RiTaJS/pull/52/commits/b79d6c1bedada52562273a62ed6f0a045356a8f7#diff-3e23dd2bc1ebc49c864ab454d773d746R97

**Comment by dhowe** [comment]
Good notice. There are several similar cases here:
1. rhymes
1. alliterations
1. similarBySound
1. similarBySoundAndLetter
1. isRhyme
1. isAlliteration

Also possibly:
1. isAdjective
1. isNoun
2. etc...

These functions are part of RiLexicon, so the original thinking was that they should only use the lexicon data. One solution would be to add them all to the RiTa object, e.g., RiTa.rhymes(), or RiTa.getRhymes(), which could then use the LTS data if it was available... But this would be a big API change

Can you check that all the functions above have the same problem?

**Comment by cqx931** [comment]
No result
1. rhymes 

Not influenced:
1. similarBySound
1. similarBySoundAndLetter
1. isAlliteration
1. alliterations

Not accurate:
if the word is not in the dictionary, no raw pos tag will be returned, so the result is always false.
1. isAdjective
1. isNoun
2. etc...

**Comment by dhowe** [comment]
Ok, so please do as you suggest above (add LTS-checking for rhyme if not in lexicon).
And, make sure we have a warning for isAdjective, isNoun, etc.
Also, make sure the behavior is the same in java version (though we don't need to worry about no-lexicon or no-lts cases)

**Comment by cqx931** [comment]
- [ ] LTS-checking for rhymes()
 - [ ] Added warning message for posTag related functions (both in RiLexicon and in RiTa)
 - [ ] Double checked in java version that it doesn't have any problem with the above issue
