### ISSUE TITLE
Showing warning messages for rita-medium 

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#401]
For rita-medium( with lexicon 1000), the result related to posTag could be inaccurate
Right now, there is no warning message or helping message when this happens.

> [WARN] A minimal Lexicon is currently in use. For word features outside the lexicon, use a larger version of RiTa.

**Comment by dhowe** [comment]
Are you suggesting adding the text above?

**Comment by cqx931** [comment]
yes

**Comment by dhowe** [comment]
Sounds good.
