### ISSUE TITLE
Alliteration is not fixed in RiTaJS

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#402]
https://github.com/dhowe/RiTa/pull/380/files

**Comment by dhowe** [comment]
how are tests passing?

**Comment by cqx931** [comment]
I still need to check this, the JS version is actually up to date with the Java, but I got some confusing results when I tried to test with different sizes, we need some better test-cases for alliterations.
https://github.com/dhowe/RiTaJS/blob/master/test/RiLexicon-tests.js#L86

**Comment by dhowe** [comment]
Ok, pls create a separate ticket (then close this one). It is very important that our tests fail when they should

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/issues/403
