### ISSUE TITLE
Need Better Test cases for Alliterations

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#403]
https://github.com/dhowe/RiTaJS/blob/master/test/RiLexicon-tests.js#L86

**Comment by dhowe** [comment]
Do we have them in Java, or same problem?

**Comment by cqx931** [comment]
Same problem: https://github.com/dhowe/RiTa/blob/master/java/rita/test/RiLexiconTest.java#L161

**Comment by cqx931** [comment]
now, alliteration is comparing the first consonant of the first Syllabus of two words.
So "dog" and "addle" is going to be a pair of alliteration, as the first consonant in "addle" is "d".

Though we don't consider assonance in our case, we still need to check first phoneme instead of the first consonant to avoid cases above, correct?

**Comment by cqx931** [comment]
question: Are 'contradictorily' and 'dog' also alliterations?

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/RiTaJS/pull/55
If this is ok, I'm going to make the same changes for Java.

**Comment by dhowe** [comment]
for 'contradictorily', 'con' should be 1st stressed
for 'videoconference', 'vid' should be the 1st stressed

**Comment by cqx931** [comment]
contradictorily, stress is on 'd'
https://en.oxforddictionaries.com/definition/us/contradictorily

**Comment by dhowe** [comment]
hmm, that is a subtle pronunciation difference, but if that is what both the lexicon and LTS say, then yes, it should be an alliteration, according to our definition...

however, I wonder if we should sort the results so that words that start with the same letter as the original word come first?

**Comment by cqx931** [comment]
Changes made in java: https://github.com/dhowe/RiTa/pull/411

In javascript I used `unshift()` for words that start with the same letter as the original word, and `push()` if they don't. So that words start with the same letter come first.
Not sure about doing the same thing in Java as HashSet is used for the returned result. Is it better to sort the whole result after the loop is done?

**Comment by dhowe** [comment]
ideally we want to divide the results into two sets, which are shuffled randomly, then append the non-matching first letter/phoneme to the end of the good set.

and, yes, we should actually be matching first-phoneme, not first-letter, to get cases like wreath and restaurant

**Comment by cqx931** [comment]
Yes, agree.
How about using the Fisher-Yates (aka Knuth) Shuffle mentioned below?
http://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array

Still, it's a bit weird from a user perspective to see non-matching first-phoneme-matches at the end of a matching set. I would imagine it more like a switch, either I got all the result or only those that are matched in first-phoneme. The whole set is shuffled randomly. (instead of two randomly shuffled set returned as one)

**Comment by dhowe** [comment]
Lets just shuffle them all randomly for now and worry about it post 1.6. HashSets are randomly ordered already, and js can just use the global shuffle() function already in ritajs

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTaJS/pull/58
