### ISSUE TITLE
Fix bower warnings

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#404]
```
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "description" is too long, the limit is 140 characters
```

**Comment by dhowe** [comment]
@cqx931  please see if you can recreate this with a bower install

**Comment by cqx931** [comment]
This is what I see if I do `bower install rita`
I can't reproduce this warnings
```
bower cached        https://github.com/dhowe/RiTaJS.git#1.1.51
bower validate      1.1.51 against https://github.com/dhowe/RiTaJS.git#*
bower new           version for https://github.com/dhowe/RiTaJS.git#*
bower resolve       https://github.com/dhowe/RiTaJS.git#*
bower download      https://github.com/dhowe/RiTaJS/archive/v1.1.62.tar.gz
bower extract       rita#* archive.tar.gz
bower mismatch      Version declared in the json (1.1.60) is different than the resolved one (1.1.62)
bower resolved      https://github.com/dhowe/RiTaJS.git#1.1.62
bower cached        https://github.com/jeremyfa/yaml.js.git#0.2.10
bower validate      0.2.10 against https://github.com/jeremyfa/yaml.js.git#^0.2.3
bower install       rita#1.1.62
bower install       yaml.js#0.2.10

rita#1.1.62 bower_components/rita
└── yaml.js#0.2.10

yaml.js#0.2.10 bower_components/yaml.js
```

**Comment by dhowe** [comment]
ok, so what about this one?

` bower mismatch      Version declared in the json (1.1.60) is different than the resolved one (1.1.62)`

**Comment by cqx931** [comment]
it should be caused by bower.json which has a version number of 1.1.60 while the final release is 1.1.62... I'm not sure why this could happen because it should be automatically updated when doing `gulp build`
https://github.com/dhowe/RiTaJS/blob/master/gulpfile.js#L336

**Comment by dhowe** [comment]
correct, that is why it is strange

**Comment by cqx931** [comment]
'make.lib' is called from ant build in rita[JAVA], the script itself works well. 
Added version checking to post-release testing.
