### ISSUE TITLE
1 POS test failing in 'npm test'

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#413]
Module: RiTa Test: testGetPosTags
    at Object.<anonymous> (/Users/dhowe/Documents/Projects/RiTaJS/package/test/RiTa-tests.js:791:7)
Actual value:
[ 'prp', 'vbn', 'dt', 'nn' ]
Expected value:
[ 'prp', 'vbp', 'dt', 'nn' ]

**Comment by cqx931** [comment]
When I do npm test following the instruction, I got more than one POS test failing.
According to the gulp file, test-npm uses rita.js instead of rita-full.js to test, which has the 1000-word-dictionary instead of the full one.
So it fails many tasks on syllables, stress and posTags.

**Comment by dhowe** [comment]
> According to the gulp file, test-npm uses rita.js instead of rita-full.js to test, which has the 1000-word-dictionary instead of the full one.

test-npm uses rita.js which _is_ rita-full.js after a node install (in some recent ticket I gave instructions on how to use this with build.npm)

**Comment by dhowe** [comment]
> One of the main issue we have now is that we can only due with nn/nns if a word could not be found in the dictionary. So we got many vbn/vbd identified as nn, and many vbz identified as nns.

Does this only happen with the verbless-dictionary, or the regular dictionary as well?

**Comment by cqx931** [comment]
The regular dictionary doesn't have this issue for now as it has all the regular entries for vbn/vbd/vbz

**Comment by dhowe** [comment]
> For syllables and stresses, I think we need to mark both results as correct(from lexicon and LTS), so that the same test suite can be used for both.

Actually, unless we think the LTS is incorrect, I would prefer that we change the dict to match it, this way, users get the same result with or without the lexicon...

**Comment by dhowe** [comment]
> The regular dictionary doesn't have this issue for now as it has all the regular entries for vbn/vbd/vbz

ok, so lets abandon the verbless-dictionary, at least for the moment

**Comment by cqx931** [comment]
> ok, so lets abandon the verbless-dictionary, at least for the moment

This is still an issue for lex_1000

**Comment by dhowe** [comment]
> ok, so lets abandon the verbless-dictionary, at least for the moment

>> This is still an issue for lex_1000

Its ok to have some POS tagging errors with lex_1000, as long as we issue the warning

**Comment by cqx931** [comment]
no more valid, close
