### ISSUE TITLE
Include sizes (tiny, medium, large) in gulp tasks and add to release tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#418]
Don't need the names, but need to make sure we are generating all the correct files in our gulp builds, and that we are correctly testing each in the release-tests

 (see #384)

Note: for testing console warning (about LTS/lexicon, etc.) we may want to use the 'sinon' package, but probably only after 1.6

**Comment by cqx931** [comment]
Please check the update in rita build and website download: https://github.com/dhowe/RiTa/pull/421

**Comment by cqx931** [comment]
done
