### ISSUE TITLE
Release testing v1.6

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#422]
- [x] Step carefully through all 'quickstart' installation [instructions]
(http://rednoise.org/rita/quickstart.php)
- [x] Go through [WordNet README file](https://github.com/dhowe/RiTa/blob/master/README.WordNet.md)
- [x] Go through [Android README file](https://github.com/dhowe/RiTa/blob/master/README.android.md)

### Before release 
- Run each of the RiTa [examples](http://rednoise.org/rita/examples.php) on each of the platforms:

#### JavaScript
- [x] In the browser with dom (Chrome/Firefox)
- [x] In the browser with browserify (manually update npm module)
- [x] In the browser with p5.js
- [x] Test 'Analysis' and 'RandomRhymes' examples with no lexicon, using rita.js, rather than rita-full.js and verify that the correct warning message is shown
 
#### Java
- [x] In Processing
- [x] As a standalone Java program (jar)
- [x] In Processing for Android
- [x] As a standalone Android app (jar)
(Ignore the example: ReplaceableWriting for Android tests)
  &nbsp; 

 #### Testing RiTa website: http://rednoise.org/rita/ 

- [x] Check and fix errors in the console tab of developer tools for each page 
- [x] Check links (with a [link-checker](https://validator.w3.org/checklink)) and fix any errors  

### Post release
- [x] Install RiTa via `npm install` and test instructions on npm [README page](https://www.npmjs.com/package/rita#in-nodejs)
- [x] Test the npm/runkit example here: https://runkit.com/npm/rita 
- [x] Test RiTa In the browser via `bower install`
- [x] Test RiTa In the browser via [browserify instructions](https://github.com/dhowe/RiTaJS#with-browserify-and-npm)
- [x] Download from the library tool within the Processing IDE
- [x] Check that processing library tool is prompting for update if older rita exists
- [x] Verify the version # on [RiTa downloads page](http://rednoise.org/rita/download.php)
- [x] Verify 3 new versions (6 including minified) exist on [RiTa downloads](http://rednoise.org/rita/download.php)
- [x] Verify the existence and version # of the [RiTa lib on cdnjs](https://cdnjs.com/libraries/rita/)
- [x] Verify the existence and version # of the [rita.txt file on rednoise](http://rednoise.org/rita/rita.txt)

&nbsp;

**Comment by cqx931** [comment]
> Test each JavaScript example with no lexicon, using rita.js, rather than rita-full.js (some will not run)
This one doesn't seem to be applicable by now. For all the javascript examples we have, those don't need to use RiLexicon already uses rita.js instead of rita-full.js. The two examples that need RiLexicon can ran smoothly with both rita-full.js and rita-small.js

**Comment by cqx931** [comment]
I have reorganized the release testing and finished all the testing items before release, please see whether the changes makes sense to you @dhowe

**Comment by dhowe** [comment]
> > Test each JavaScript example with no lexicon, using rita.js, rather than rita-full.js (some will not run)
> 
> 
> This one doesn't seem to be applicable by now. For all the javascript examples we have, those don't need to use RiLexicon already uses rita.js instead of rita-full.js. The two examples that need RiLexicon can ran smoothly with both rita-full.js and rita-small.js

Actually, we need these to test that we are getting the right warnings...

**Comment by cqx931** [comment]
> > > Test each JavaScript example with no lexicon, using rita.js, rather than rita-full.js (some will not run)
> > 
> > 
> > This one doesn't seem to be applicable by now. For all the javascript examples we have, those don't need to use RiLexicon already uses rita.js instead of rita-full.js. The two examples that need RiLexicon can ran smoothly with both rita-full.js and rita-small.js
> 
> Actually, we need these to test that we are getting the right warnings...

Ah, I see...

**Comment by dhowe** [comment]
Otherwise looks good -- I've made some additions to the post-release tests (please check)

**Comment by dhowe** [comment]
@cqx931 i've made a couple of minor changes to post-release testing (see last item). Once finished, lets move this list to the rita wiki/faq page

**Comment by cqx931** [comment]
The RiTa version in Processing 3 library tool is still 1.1.51.

**Comment by dhowe** [comment]
Yes, why is this?  It should use this text-file to decide on version: http://rednoise.org/rita/rita.txt

**Comment by cqx931** [comment]
Processing is now at 1.1.60.
All verified, closed
