### ISSUE TITLE
Different font-sizes for author names in gallery

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#427]
![image](https://cloud.githubusercontent.com/assets/737638/25426111/aef0b9e8-2aa0-11e7-8a60-2189b0a635ca.png)

Also, can we add a thin gray border around the white images here?

Also, is it possible, without changing the images themselves, to display all images here as rounded rectangles ?

**Comment by cqx931** [comment]
Shall I also change the downloaded boxes to rounded rectangles if we want to keep a consistent style?

**Comment by dhowe** [comment]
lets give it a try -- i will check it locally before pushing

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/430
