### ISSUE TITLE
npm WARN optional dep failed, continuing yamljs@0.2.10

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#428]
```
$ npm update rita
npm WARN optional dep failed, continuing yamljs@0.2.10
rita@1.1.60 node_modules/rita
```

**Comment by cqx931** [comment]
I can't reproduce this issue when I do `npm update rita`.
When I search "npm WARN optional dep failed, continuing...", this seems to be only a warning message  and doesn't influence the update or installation of the package. 
Also for the cases I have read so far, it has nothing to do with the package itself...

**Comment by dhowe** [comment]
to recreate you would have to have an old package, then update to a new
for example, do 'npm list rita' in ReadersJS. If the version is v1.1.51, then you can do 'npm update rita'

**Comment by cqx931** [comment]
that is how I tested `npm update rita`, but even in ReadersJS, I still can't reproduce this warning message.

**Comment by dhowe** [comment]
closing for now
