### ISSUE TITLE
Update documentation to match recent code changes

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#439]
- [x] remove removeWord() function
- [x] remove RiLexicon object from the API altogether
- [x] add RiLexicon methods to the 2nd column of the index page, labeled RiTa.addWord, RiTa.alliterations, etc.
- [x] add some kind of subtle header showing that these are lexicon-related functions

**Comment by dhowe** [comment]
see https://github.com/dhowe/RiTa/pull/440

**Comment by cqx931** [comment]
close

**Comment by dhowe** [comment]
Add RiLexicon to list of deprecated objects (above RiText) in reference index, with link to its documentation page. At top of documentation page, it should have a note saying all functions can be accessed via RiTa.*...

**Comment by dhowe** [comment]
Adjust horizontal spacing of columns so that they better spaced and avoid the problem below:

![image](https://cloud.githubusercontent.com/assets/737638/26445127/9b17530e-4171-11e7-90c9-f0765f462a3a.png)

**Comment by dhowe** [comment]
Also, comment out RiTa.clear, RiTa.words, RiTa.reload

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/RiTa/pull/441

**Comment by dhowe** [comment]
1. remove vertical space between RiLexicon and RiText
2. shift RiString column to right so that space after longest function name is equal
3. again, remove RiString.wordCount
4. change text on RiLexicon page: 'Note: All functions in ReLexicon can now be accessed via RiTa.*'

**Comment by cqx931** [comment]
Tweak: https://github.com/dhowe/RiTa/pull/443
