### ISSUE TITLE
Make list of PENN part-of-speech tags a publicly exposed variable

### ISSUE THREAD

**Issue by Niels-NTG** [dhowe/RiTa#442]
Currently in the JS version or RiTa you have the variable `RiTa.ALL_PHONES`. This is a list of possible phoneme tags as defined here: https://rednoise.org/rita/reference/PhonemeTags.html. It would be very useful and consistent if all possible Part of Speech tags (https://rednoise.org/rita/reference/PennTags.html) where also exposed this way. This could be `RiTa.ALL_POS`. This could be just a list of all the tags. But preferably this would be a list that contained both the tag and description as either a dictionary type structure or an array of objects.

**Comment by dhowe** [comment]
Can you give me a use-case? My initial inclination is not to add them (at least to JS) for the sake of file size...

**Comment by Niels-NTG** [comment]
Well, file size shouldn't be much of a concern since it's already there at https://github.com/dhowe/RiTa/blob/e0ce27cf4c5f64c05179f21e658107342f1100fa/web/download/rita.js#L3709 in the `PosTagger` singleton.

And as for the use case: Think about a situation where you would like to categorise each word of a text by its POS. First I break the text with the `.words()` method, then I iterate through them getting the POS of each of them. If I already know all possible POS tags I can easily check by checking if the results equals something from the list. Without the list I have to save the POS tag of each word together with the POS tag itself, then I have to look through this entire list to see what possible POS tags exist. Only then can I properly categories them. Of course you can take some shortcuts here, but trust me that for my use case I like to keep my code as simple as possible by abstracting this tedious part.

**Comment by Niels-NTG** [comment]
An example of how the POS tag list data could look like: https://github.com/dhowe/RiTa/blob/849887e3448b52837356a75c37b34dcbcf3c716d/web/gallery/MemoireInvolontaireNo1/lib/rita.js#L4182

**Comment by dhowe** [comment]
that data is from the Java version (and was originally included in JS after the port). For the 1.2 release we're working on now, however, we're trying to trim down the size of JS, trimming incorrect or uncommon words from the lexicon, and moving unused functions and data out of the code. So its likely those will go away, though I've already added them to the [documentation],
(http://rednoise.org/rita/reference/PennTags.html). If its useful, I can add the data (format) you link to above as well..
