### ISSUE TITLE
Fix different size/shape sharing buttons on index.php/download.php/ref.php

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#447]
index.php (correct)
![image](https://cloud.githubusercontent.com/assets/737638/26528508/318c3ed8-43e0-11e7-98a6-2c963c5f770b.png)

download.php (too big)
![image](https://cloud.githubusercontent.com/assets/737638/26528513/5b0e41e8-43e0-11e7-8759-13e511cb7e6c.png)

reference*.php (wrong shape)
![image](https://cloud.githubusercontent.com/assets/737638/26528514/5dad8eea-43e0-11e7-9913-488ad3f56d9e.png)

**Comment by cqx931** [comment]
I fixed the size issue, but the shape one is very tricky... It is caused by different hight of the element 'private-sharing-button__icon', but I can't find the cause for that.
intohttps://github.com/dhowe/RiTa/pull/452/commits/9163db70ce3c0c19e137e6c6560d5f86d0b7ddc5

**Comment by dhowe** [comment]
I also notice the type for author name is different on the pages above -- don't we have a standard footer for all?

**Comment by cqx931** [comment]
Fix: different type for author name:  https://github.com/dhowe/RiTa/pull/454
Yes, all the footer are rendered from footer.php.
