### ISSUE TITLE
Make sure we are handling randomWord('nns') correctly

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#450]

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTaJS/commit/a10612b5867905c3f70e8c8143cc42a5e674b432
https://github.com/dhowe/RiTaJS/commit/4a2d38e2075012ce011ca809c8546b6326a36138
https://github.com/dhowe/RiTaJS/commit/0474a8e3e0690f6fc70c178324d4efe1da044e4e

This should work after the above commits, can this be closed now?
