### ISSUE TITLE
Improving singularize() for SE_SES

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#453]
The current singularize() function get the result wrong when the singular form ends with 'se' and the plural ends with 'ses'.
Please find test cases here : https://github.com/dhowe/RiTaJS/pull/75/commits/a10612b5867905c3f70e8c8143cc42a5e674b432#diff-e6fb5aa635b340fe5899a506e000bf04
The current categorySE_SES variable doesn't have a very long word list.
https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L4756

So I suggest that we could add more words to the categorySE_SES list as a starting point.

The following is a list of words that I generated from the old dictionary combined with the current categorySE_SES variable.
I printed out nns words end with 'ses' that and after removing the last 's' it has a corresponding 'nn' in the dictionary.

```
abuses
blouses
bruises
cheeses
chemises
clauses
corpses
courses
cruises
curses
databases
defenses
dioceses
discourses
diseases
doses
eclipses
enterprises
expenses
fuses
glimpses
guises
horses
impulses
noises
noses
nurses
offenses
overdoses
phrases
pretenses
pulses
purposes
purses
racehorses
repurchases
responses
roses
spouses
surmises
tortoises
treatises
vases
verses
```

The lists have excluded many words end with 'houses'/'cases'... which I think it is better to add them into SINGULAR_RULES
https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L5333

**Comment by dhowe** [comment]
this makes sense -- remember that we need to do the same for java

**Comment by cqx931** [comment]
More words for se_ses/ze_zes plurals, for words that only had noun entry but no plural in the dictionary before:
```
anises
antifreezes
apocalypses
applauses
archdioceses
celluloses
chaises
crazes
creases
dazes
demises
expertises
finesses
friezes
fructoses
gauzes
glucoses
greases
hazes
hearses
impasses
kamikazes
mazes
mousses
nooses
obverses
polonaises
posses
premises
proses
proteases
recluses
recourses
relapses
ruses
stripteases
subleases
sunrises
trapezes
universes
vises
wheelbases
```
Also words end with horses

Uncountable words that didn't get caught up by RiTa:
```
booze
cellulose
incense
intercourse
journalese
malaise
manganese
mayonnaise
menopause
merchandise
nitrocellulose
overuse
paradise
poise
polymerase
recompense
remorse
repose
sleaze
suspense
unease
```

Please let me know if you think any of the word listed here is categorized wrongly.

**Comment by dhowe** [comment]
Incorrect plurals (uncountables):
```
anises
antifreezes
applauses
archdioceses
celluloses
expertises
finesses
fructoses
gauzes
glucoses
greases
hazes
polonaises (removed)
proses
```

Also, I've removed the following: 
```

nitrocellulose
journalese
polonaise(s)
protease(s)
```

**Comment by cqx931** [comment]
done. close
