### ISSUE TITLE
Example Font doesn't work as expected in dom Firefox

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#457]
KwicModel
![image](https://cloud.githubusercontent.com/assets/3056154/26584318/fc48e676-457a-11e7-87da-c6b3e9318a77.png)
Kafgenstein
![image](https://cloud.githubusercontent.com/assets/3056154/26584330/0662020a-457b-11e7-9e98-3e18ac0b2f71.png)
HaikuGrammar
![image](https://cloud.githubusercontent.com/assets/3056154/26584397/387eda74-457b-11e7-8f04-963af7ea12d2.png)

**Comment by dhowe** [comment]
but ok in chromium?

**Comment by cqx931** [comment]
yes, the first two should be an easy fix but the haiku one seems to be caused by this:
https://stackoverflow.com/questions/19817459/firefox-font-face-with-local-file-downloadable-font-download-failed

**Comment by cqx931** [comment]
hmm...there might be something wrong with my firefox, I got font problems on many sites... let me check.

**Comment by dhowe** [comment]
error?

**Comment by cqx931** [comment]
no error message

**Comment by dhowe** [comment]
nothing to do with rita, just font-face, yes?

```
    @font-face {
      font-family: Resagokr;
      src: url(../../fonts/Resagokr.otf);
    }
```

**Comment by cqx931** [comment]
Yes, it has nothing todo with rita, just some font-face syntax:
https://github.com/dhowe/RiTaJS/pull/78

**Comment by dhowe** [comment]
ok, so let's not let it hold-up 1.2

**Comment by cqx931** [comment]
fixed
