### ISSUE TITLE
Error when testing 'Analysis' and 'RandomRhymes' examples with no lexicon

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#459]
No warning message about lexicon

Analysis
![image](https://cloud.githubusercontent.com/assets/3056154/26586826/fa4299dc-4582-11e7-9252-fc64a91c752c.png)

RandomRhymes
The page just doesn't load and there is no error message, no response. (it get stuck in the while loop)

Also, currently we don't have a unique warning message for no lexicon.
The warning message I got with rita.js when I test in RiLexicon-tests.html is 
"A minimal Lexicon is currently in use. For word features outside the lexicon, use a larger version of RiTa."

**Comment by dhowe** [comment]
That warning is fine, but we can't have the error...

**Comment by cqx931** [comment]
In the PR above, I have modified the example code for both 'Analysis' and 'RandomRhymes' (p5 and dom), so that no error message is showing when rita.js is used.

Warning message:
When lex size is 0, what need a warning message are functions that have a for loop iterating through the whole lexicon data set to return something back.(`randomWord()`, `rhymes()`, `_getRawPhones()`...etc.) So I changed all the `this.data.length` in those for loops to `this.size()` and add a warning message in lex.size(), if the lexicon size is zero.

Please let me know if there is any concern about this method.

**Comment by dhowe** [comment]
sounds right
