### ISSUE TITLE
Links broken on rita website

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#460]
- [x] https://rednoise.org/rita-archive/WordNet-3.1.zip fixed

- [ ] https://rednoise.org/rita-archive/RiTa.Wordnet-034.zip

- [ ] https://rednoise.org/rita-archive/RiTa-1022.zip

**Comment by cqx931** [comment]
This link is forbidden:
https://rednoise.org/rita/rita.zip

**Comment by dhowe** [comment]
This is the problem -- I entered it in another ticket. You cannot commit that file as is:

![image](https://cloud.githubusercontent.com/assets/737638/26665633/9be9bb9e-46cd-11e7-894b-c6db5ab379bc.png)

**Comment by dhowe** [comment]
Top 3 links are still pending, so I leaving open...

**Comment by cqx931** [comment]
The first one is fixed but the two older versions don't, do we still want to keep them in the downloads?

**Comment by dhowe** [comment]
Lets remove that whole section from the downloads page

**Comment by dhowe** [comment]
done
