### ISSUE TITLE
bower error

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#463]
In the bower example it is using rita.min.js
 ` <script src="./bower_components/rita/dist/rita.min.js"></script>`
However the latest rita I installed from bower doesn't have any min file.
In the dist folder, there are `rita-full.j` `rita-small.js` and `rita.js`

**Comment by dhowe** [comment]
https://www.reddit.com/r/javascript/comments/5ls30m/is_bower_dead_should_we_start_using_other/

**Comment by cqx931** [comment]
It makes sense to me to remove bower, npm and browserify should be sufficient.

**Comment by dhowe** [comment]
cool -- can you check through our docs/wiki/etc and remove all these references...

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/RiTaJS/pull/81

**Comment by dhowe** [comment]
should probably remove instructions for processing.js at some point as well, but ok for now I guess
