### ISSUE TITLE
Plural Noun Exception

### ISSUE THREAD

**Issue by aledwassell** [dhowe/RiTa#464]
I have found so far one error with the plural for 'moose' I believe it remains 'moose', RiTa changes it to mooses, that is incorrect

**Comment by dhowe** [comment]
thanks, we'll take a look

**Comment by cqx931** [comment]
@aledwassell  Thanks for pointing this out, I have added 'moose' into the NULL_PLURAL word list and it should be fixed in both rita and ritaJS now.
RiTa: https://github.com/dhowe/RiTa/pull/468
RiTaJS: https://github.com/dhowe/RiTaJS/pull/82

**Comment by dhowe** [comment]
@aledwassell let us know if you notice any others...

**Comment by cqx931** [comment]
close for now
