### ISSUE TITLE
Issues about word lists: CategorySP and Null_Plurals

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#469]
When I worked on non-countable nouns or word that is both singular and plural, I found these two word lists a bit confusing/problematic:

[CategorySP](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L4780) : Words that are both singular and plural (from RiTa.stemmers.Pling)
[Null_Plurals](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L5357): these don't change for plural/singular

From their definition in comment, both word lists sound like the place to add a word that is both singular and plural.
However, what actually in use is Null_Plurals, which is used in lex._isPlural(), pluralzie(), singularize().
CategorySP is only used for `isSingular()` and `isSingularAndPlural()` in RiTa.stemmers.Pling. But these two functions are not used in other part of the code.
Except a few cases, most of the words in CategorySP are not covered in Null_Plurals, therefore there are wrong results like:
```
RiTa.pluralize("acoustics") --> acousticses
RiTa.singularize("acoustics") -> acoustic
```

To solve issues above, I can think about two ways to do this:
1. Move words from CategorySP to Null_Plurals
2. Consider words from CategorySP in lex._isPlural(), pluralzie(), singularize()

@dhowe  which one sounds better to you?

Words from `CategorySP` but not included in `Null_Plurals`:

> 'acoustics', 'aesthetics', 'aquatics', 'basics', 'ceramics', 'classics', 'cosmetics', 'dialectics', 'dynamics', 'ethics', 'harmonics', 'heroics', 'mechanics', 'metrics', 'optics', 'physics', 'polemics', 'pyrotechnics', 'quadratics', 'quarters', 'tactics', 'tropics'

*I am only talking about RiTaJS here, same changes could be later implemented in java accordingly.

**Comment by dhowe** [comment]
Sounds better to "Move words from CategorySP to Null_Plurals"
then use Null_Plurals" for lex._isPlural(), pluralize(), singularize(), yes?

**Comment by cqx931** [comment]
Please check:
Null_Plurals is already in use for  lex._isPlural(), pluralize(), singularize().
https://github.com/dhowe/RiTa/pull/470
https://github.com/dhowe/RiTaJS/pulls

**Comment by dhowe** [comment]
Have relevant tests been added in java and js?

**Comment by cqx931** [comment]
'quadratics' - Not sure about this word, I can only find 'quadratic' but not 'quadratics' when I search, better removed?
 'quarters', 'tactics', 'tropics' - These three should better be removed from Null_Plurals because they could be both countable and uncountable at the same time.

**Comment by dhowe** [comment]
yes, 'quadratic' is an adjective and possibly a noun as well, but 'quadratics' should not exist

'quarters', 'tactics', 'quarter', 'tactic',  'tropics', 'tropic' all are ok

**Comment by cqx931** [comment]
Test cases added for RiTaJS: https://github.com/dhowe/RiTaJS/pull/84
Java is blocked by this issue: https://github.com/dhowe/RiTa/issues/472

**Comment by cqx931** [comment]
All done
