### ISSUE TITLE
Image file missing on website

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#471]
http://rednoise.org/rita/Video/snap.png

![screen shot 2017-06-19 at 6 46 00 pm](https://user-images.githubusercontent.com/737638/27281731-9989721c-551f-11e7-82b7-81dac27e5e66.png)

**Comment by cqx931** [comment]
Not sure why it is not on the server, but it is in the website folder:
https://github.com/dhowe/RiTa/blob/master/web/video/snap.png

**Comment by dhowe** [comment]
It is case-sensitive, the code asks for 'Video' and it is in 'video'
