### ISSUE TITLE
The difference between singularize() in java and in js

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#472]
In RiTaJS, it first go through all the [SINGULAR_RULES](https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L5360), then check the stem in Pling stemmer
https://github.com/dhowe/RiTaJS/blob/master/src/rita.js#L242

However, in java, it only check the stem in Pling stemmer and there is no variable called SINGULAR_RULES.
https://github.com/dhowe/RiTa/blob/master/java/rita/RiTa.java#L617

**Comment by dhowe** [comment]
(assuming that there are no failing tests in either) I believe RiTaJS is correct -- can we update RiTa to follow RiTaJS?

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/473 done, please check
