### ISSUE TITLE
Error on Processing install

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#474]
I have fixed this temporarily, by temporarily creating a second symlink, but we need a permanent fix (this should not have gotten through release testing for v1.2).

![image](https://user-images.githubusercontent.com/737638/27505849-9c00a98c-58dc-11e7-95de-fdd631f53831.png)

**Comment by cqx931** [comment]
When I last checked this last time, it was still on 1.1.72 and didn't pass the test. 
I remembered that it used to be a case-sensitivity issue for the link in processing library, is it still the same issue?
Or we can talk about it later today.

**Comment by dhowe** [comment]
No, this is the case-sensitivity problem. In any case, I am currently creating links to the zip with both casings: rita.zip and RiTa.zip

**Comment by cqx931** [comment]
Added a double check of this in post-release testing 
https://github.com/dhowe/RiTa/wiki
