### ISSUE TITLE
Add curly single/double-quotes to RiTa.stripPunctuation() and RiTa.trimPunctuation() 

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#475]
java/js -- plus appropriate tests...

’‘
may need to use unicode, as double-quotes may be difficult to type

**Comment by cqx931** [comment]
This is already implemented in java, I added a few test cases:
https://github.com/dhowe/RiTa/pull/476
RiTaJS
https://github.com/dhowe/RiTaJS/pull/85
