### ISSUE TITLE
RiTa: stripPunctuation and RiTa: trimPunctuation tests failing in JS

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#478]
RiTa: stripPunctuation and RiTa: trimPunctuation tests failing in JS

**Comment by cqx931** [comment]
When I check the latest commit in RiTaJS https://github.com/dhowe/RiTaJS/commit/b1e70577a8fc5c86dd5dd8a972a034807c499f2f, I can only see testUntokenize() failing... have you pushed all your changes?

![image](https://user-images.githubusercontent.com/3056154/27851850-355890ee-618f-11e7-8ece-913cf77c938c.png)

**Comment by dhowe** [comment]
let me double-check

**Comment by cqx931** [comment]
Fixed here: https://github.com/dhowe/RiTaJS/pull/86
