### ISSUE TITLE
RiTaJS failing travis for 'iojs' environment

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#479]
RiTaJS failing travis only on 'iojs':
Can you check this out, @cqx931 ?
https://travis-ci.org/dhowe/RiTaJS/jobs/250274559

If its easy to fix, then do so; if not, then lets remove that environment from our builds for now

**Comment by cqx931** [comment]
This doesn't seem to be caused by our code. If I rebuild successful old commits, RiTaJS is also failing on 'iojs'.
Temporarily removed iojs for now. https://github.com/dhowe/RiTaJS/pull/89/commits/30950f065ba51ecb1b12636d0980c1c9a98160f9

**Comment by dhowe** [comment]
close for now
