### ISSUE TITLE
Post various tutorials on website

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#48]
TOPICS
-- Using RiMarkov
-- Using RiGrammar
-- Using RiWordNet
-- Analyzing text (phonemes, stresses, tokens, pos, etc)
-- Conjugation, stemming, plurals/singulars, splitting-sentences, tokenizing/untokenizing, etc

Each of these should have a little explanatory section at the top, like this (found [online](http://tipsandtricks.runicsoft.com/Other/JavaStemmer.html), then edited):

### Stemming
Stemming means reducing a word to its base (or stem). For example, the words 'writing', 'wrote' and 'written' all have the stem 'write'. A stemmer takes a word, or a list of words, and produces the stem, or a list of the stems, of the input.

Stemming is useful when you are doing any kind of text-analysis: when you are concerned about the contents of a text, the different times of verbs, and the different endings for singular and plural, make it difficult to discern the importance of specific words within the text.

For example the text "I wrote a book about cats, after I had written a short article on cats. Currently I'm writing about dogs. Next year I'll write poems. But I made my best writings when i was younger."
It's obvious (to a human) that this text is mainly concerned with writing. But when you run a program to analyse it, the program will come to the conclusion that it's a text about cats, because the word 'cats' is the only word (aside from words like 'I', 'a', etc.) that occurs more than once.

But if you stem the text before analysing it, replacing all words with their stems, the program will correctly tell you that it's a text about writing, since after stemming, the word 'write' will appear five times )because 'writing', 'written', 'writings' and 'wrote' have been replaced by 'write').

<br>

### Tokenizing

...

<br>

**Comment by dhowe** [comment]
where are we with this?

**Comment by cqx931** [comment]
http://lab-lamp.scm.cityu.edu.hk/~qianxchen2/rita/tutorial/index.php
got all of these included in the tutorial
