### ISSUE TITLE
Can't get RiTa to import into my Angular CLI app?

### ISSUE THREAD

**Issue by CharlesEmrich** [dhowe/RiTa#481]
Added it in via `npm install rita --save` but angular's importing syntax doesn't seem to be giving me access to the library's functions.

Typical syntax to import an npm module into a file is `import * as moduleName from 'module'` or `import { ExportedClass } from 'module'` but neither of those seems to work for RiTa.

There is a reasonable chance this is user error, but I've run in circles for about two hours now without progress and figured I'd ask here.

**Comment by dhowe** [comment]
Thanks, we'll take a look...

**Comment by dhowe** [comment]
This should work the same as any external, 3rd-party library... Have you tried the guide here: https://github.com/angular/angular-cli/wiki/stories-third-party-lib

**Comment by jtsiskin** [comment]
I'm having the same issue, using react.
var rita = require('rita');
import * as rita from "rita"
import rita from "rita"
import {RiTa} from "rita"

None of the above work, and rita always resolved to an empty object. RiTa is undefined.

**Comment by jgorene** [comment]
Hello,
I build a web app with webpack and I have the same problem after trying almost the same solutions mentioned above... On the other hand, the cdn link to the min file works perfectly !

For now, I'm just discovering your library and it looks full of promises for my use in any case ;)
Thank you very much for your "hard work" !

**Comment by dhowe** [comment]
I'm having trouble finding documentation for what is expected from an external library used in react. Can you link to a library on npm that works as expected?

**Comment by jgorene** [comment]
@dhowe [Ical.js](https://github.com/mozilla-comm/ical.js/) is a node module that I use and seems look like your npm configuration.

Unfortunately, I don't know how build a node module for now and I'm just a user, basically to call it in app with webpack...
`import ICAL from 'ical.js';`

**Comment by dhowe** [comment]
This should be fixed in v1.3.89. Please test and report back:

![image](https://user-images.githubusercontent.com/737638/53293203-7c6f2d00-380a-11e9-97de-47b9ab86e8e5.png)

**Comment by jgorene** [comment]
I installed the new version but no change for me it fails when launching in dev mode with webpack
I checked the version package after installation and it's good for v1.3.89 but maybe I missed something.
Here is the error message...
```
./node_modules/rita/lib/rita.js
Module not found: Error: Can't resolve 'fs' in '/my_config_path/node_modules/rita/lib'
```
Just for info if needed [the repo](https://github.com/jgorene/ical-vision) where I use your library

**Comment by dhowe** [comment]
Apparently this is a bug in webpack -- see https://github.com/webpack-contrib/css-loader/issues/447

The workaround, from the ticket about, is to add the following to your webpack config:

```
node: {
   fs: "empty"
}
```

**Comment by dhowe** [comment]
@jtsiskin @CharlesEmrich can you verify the fix in your react apps?

**Comment by jtsiskin** [comment]
I can confirm this is now working for me.  Thanks!!
