### ISSUE TITLE
New project(s) for gallery

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#484]
New project for gallery: http://www.abstract-codex.net/D3D4LU5_SW/

**Comment by dhowe** [comment]
http://www.jamesxzhou.com/work/experiments/

![image](https://user-images.githubusercontent.com/737638/42080236-9a21de14-7bb4-11e8-
9516-8d225650342d.png)

**Comment by cqx931** [comment]
I can't find the sketch/live p5js page for the Pop-Culture-Poetry...

**Comment by cqx931** [comment]
https://github.com/dhowe/RiTa/pull/515
Added 4 projects

Richard Lapham's Sol Lewitt Generator: https://www.richardlapham.com/itp/2017/11/14/sol-lewitt-generator
Halpenny's Poetry.dna http://www.matthewhalpenny.com/web & http://www.matthewhalpenny.com/poetry_dna/dna.html
@SortingBot by Darius Kazemi
How I made Bracket Meme Bot by Darius Kazemi

The video from jamesxzhou looks cool, but there is no detailed documentation about how the movement is related to the text

**Comment by dhowe** [comment]
see #517

**Comment by dhowe** [comment]
Lets include DAEDALUS, even though there is no source code: http://www.abstract-codex.net/DAEDALUS/index.html

**Comment by dhowe** [comment]
NEW: 
  The Hands of Gutenberg: http://cmuems.com/2018/60212f/breep/11/16/breep-book/

**Comment by cqx931** [comment]
Shall I use the usernames as authors for these two projects? There is no real name on the course website, I should be able to find their real name somewhere online but I don't think that's very appropriate...

**Comment by dhowe** [comment]
Agreed. There are actually lots of projects at the link for Golan's [class](http://cmuems.com/2018/60212f/deliverables/7-due-11-16/generated-book-gallery/). So we should pick the best ones, then ask the authors if they want to be included, then ask for the info...

**Comment by cqx931** [comment]
Apart from the two, the following projects are also using RiTa:
[Nannon • REDDIT BIBLE?](http://cmuems.com/2018/60212f/nannon/11/21/nannon-book/)
[Dinkolas • Bioinvasive Dingus](http://cmuems.com/2018/60212f/dinkolas/11/18/dinkolas-book/)
[Chewie • High Stakes](http://cmuems.com/2018/60212f/chewie/11/17/chewie-book/)
[Airsun • The Value of Advertisements](http://cmuems.com/2018/60212f/airsun/11/17/airsun-book/)
[Harsh • Build Limericks Not Walls](http://cmuems.com/2018/60212f/harsh/11/16/harsh-book/)
[Nerual • A-Z, Or Something Like That](http://cmuems.com/2018/60212f/nerual/11/17/nerual-book/)
[Paukparl • Generated Self-Help Books](http://cmuems.com/2018/60212f/paukparl/11/17/book-paukparl/)
[Shuann • A Guide to Absurd Movies](http://cmuems.com/2018/60212f/shuann/11/17/shuann-book/)
[Weirdie • Extraterrestrial](http://cmuems.com/2018/60212f/weirdie/11/17/weirdie-book/)
[Yuvian • Fortune Cookies](http://cmuems.com/2018/60212f/yuvian/11/16/yuvian-book/)

Among all the projects I found "The Hands of Gutenberg" and "The Value of Advertisements" the best ones. Also I didn't find email/contact/name of the students on the course website, would it be easier to reach out and ask the professor for their contacts?

**Comment by dhowe** [comment]
done - if there are others that are worth including, let me know...

**Comment by dhowe** [comment]
**Feedback from Golan**

> One of the projects you expressed interested in is "The Hands of Gutenberg" by Philippe De Bree <pdebree@andrew.cmu.edu>, a sophomore in the CMU School of Art. His project is documented at the link below; as you can see, he used RiTa for finding rhymes: 
> http://cmuems.com/2018/60212f/breep/11/16/breep-book/
> Philippe is especially interested in generative poetry (I am sending him to an Allison Parrish workshop this summer at Anderson Ranch), I'm quite certain that he would love to hear from you, and would be incredibly flattered by your interest in his project. 
> 
> Another project that I like from that assignment was created by Cassie Scheirer <cscheire@andrew.cmu.edu>, an Art freshman. She created rhyming poetry through the creative reuse of lines taken from an enormous database of music lyrics: http://cmuems.com/2018/60212f/casher/11/19/casher-book/
> Incidentally, after much experimentation, Cassie demonstrated to me that she found a 'bug' with RiTa, which is that it has trouble rhyming the word 'eight.'
> 
> You mentioned the project "Value of Advertisements". I confess I don't think this is one of the best results, but to each his own. This project was created by Clair Sun <sijings@andrew.cmu.edu>. Her project description is here: http://cmuems.com/2018/60212f/airsun/11/17/airsun-book/
> 
> You might also be interested in a "speech assignment" I gave to my students in Spring 2018, in which they were asked to "Create a (whimsical/provocative/sublime/playful) interactive game, character, chatbot or other system that uses speech input and/or speech output. Graphics are optional." The project description is here: 
> http://cmuems.com/2018/60212s/deliverables/05-due-2-23/
> One of the sample projects I gave them used RiTa for interactive rhyming against speech-to-text. You can view some of the students' projects here: 
> http://cmuems.com/2018/60212s/category/projects/05-speech/

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
Patrick Presto: ResumeBot and Poetry-in-Motion are already included in the current gallery. Two projects from Golan's class are added to the gallery.("The Hands of Gutenberg" and "Lyric Poems")
http://rednoise.org/rita/gallery.php

**Comment by dhowe** [comment]
Please add: https://blog.homeforfiction.com/2019/02/17/anapest-generator-a-javascript-poem-maker/

**Comment by kennyviperhk** [comment]
added as an html, linkage most resources from his site

**Comment by kennyviperhk** [comment]
grabbed 90% but he used  api.datamuse.com that has to relied on external site.

**Comment by kennyviperhk** [comment]
Recheck all gallery projects on the new website #561 
2 project with issues:
- http://sarahmak.es/nightTweets link doesnt work anymore. delete?
- https://elmcip.net/creative-work/mirroring-tears-visages java applet is obsolete for browser and cannot use anymore. shall we keep the website anyway?

**Comment by dhowe** [comment]
Add: http://cmuems.com/2016/60212/jaqaur/10/27/jaqaur-book/

**Comment by dhowe** [comment]
Add: https://arnoldhoogerwerf.net/portfolio_page/teaching-module-generator/

**Comment by kennyviperhk** [comment]
updated with PR

**Comment by dhowe** [comment]
Should I see this in RiTa v2 website?

**Comment by dhowe** [comment]
Mark Sample's Pandemic Dreams: https://fugitivetexts.net/pandemicdreams/
