### ISSUE TITLE
Processing library update

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#492]
At this moment, the latest version number in processing library is still on 1.2.12.
If the local version number is lower than 1.2.12,  the library tool is prompting for update, after clicking the update button, the latest 1.13.11 version would be installed.

Will revisit this tomorrow to double check.

**Comment by dhowe** [comment]
Same here:

![image](https://user-images.githubusercontent.com/737638/34635882-fa579d7c-f2d0-11e7-9a10-28068e03b3dd.png)

**Comment by dhowe** [comment]
The properties file is at rednoise.org/rita/rita.txt -- is it possible this needs to be the same capitalization as the library (RiTa.txt)? I don't remember the result of our conversation with the processing folks...

**Comment by cqx931** [comment]
Last time when the add-library tool in Processing seems to stuck on the previous version, it was caused by a case-sensitivity issue.But this issue should already be fixed, I can contact Elie to follow up.

http://www.rednoise.org/rita/RiTa.txt (the link they used to have)
http://www.rednoise.org/rita/rita.txt (the current one)

> Hi Daniel,
> 
> Not sure what was going on. I just ran the update script manually and that seems to have fixed it.
> 
> --
> Elie Zananiri

**Comment by dhowe** [comment]
Actually the are both accessible now on rednoise:

http://www.rednoise.org/rita/RiTa.txt
http://www.rednoise.org/rita/rita.txt

**Comment by cqx931** [comment]
Updated. Close
