### ISSUE TITLE
getPhonemes does not work with don't or won't

### ISSUE THREAD

**Issue by mflerackers** [dhowe/RiTa#494]
getPhonemes does not work with don't or won't, these are not in the phoneme lookup dictionary it seems.

don't - D OW N T
won't - W OW N T

**Comment by cqx931** [comment]
negative contractions
is not | isn't
are not | aren't
was not | wasn't
were not | weren't
have not | haven't
has not | hasn't
had not | hadn't
will not | won't
would not | wouldn't
do not | don't
does not | doesn't
did not | didn't
cannot | can't
could not | couldn't
should not | shouldn't
might not | mightn't
must not | mustn't

**Comment by cqx931** [comment]
negative contractions are added to the dictionary: https://github.com/dhowe/RiTaJS/pull/94/commits/e5b7c468b8a271544a64991b0b8a76ec27f75cdc
