### ISSUE TITLE
rita.SplitSentences doesn't correctly split quotations.

### ISSUE THREAD

**Issue by tsdubose** [dhowe/RiTa#498]
See attached screenshots. True for both curly and straight quotes, but the same sentence works with no quotes. Using the latest RiTa in NodeJS.

<img width="510" alt="screen shot 2018-02-23 at 8 23 31 am" src="https://user-images.githubusercontent.com/16959078/36596212-ebb4941a-1872-11e8-912d-534e7ac209b1.png">
<img width="384" alt="screen shot 2018-02-23 at 8 23 43 am" src="https://user-images.githubusercontent.com/16959078/36596224-ef1c16a0-1872-11e8-9df8-2d97461fcec5.png">

**Comment by scaryghosty** [comment]
https://github.com/dhowe/RiTaJS/blob/3ce868538d3324b9217319af68854a0bc15d3a92/src/rita.js#L340

(\S.+?[.!?])(?=\s+|$) is the offending code on line 340.

Sentences are recognized as ending with a period, exclamation point, or question mark. The additional condition is that a sentence is only recognized if they are followed by whitespace or it is the end of the string being examined. A quotation mark at the end of a sentence causes the sentence not to be recognized because a quotation mark is not one of the characters ending a sentence AND a quotation mark is not whitespace or the end of a string.

My proposed solution is this: (\S.+?[.!?**"**])(?=\s+|$) - This captures the quotation mark as part of the sentence.

**Comment by cqx931** [comment]
Questions:
1.How should we deal with the quotation mark when we split the sentences within it?
Keep the quotation mark or remove it?

2.`She wrote: "I don't paint anymore. For a while I thought it was just a phase that I'd get over.`
What should be the correct result here?

**Comment by tsdubose** [comment]
1. Keep the quotation mark. It's semantically useful.
2. `['She wrote:', '"I don't paint anymore.', 'For a while I thought it was just a phase that I'd get over."']`
My working assumption is that speech tags ("he said", "she said" etc.) should be considered "sentences" for the purposes of the function. There are likely viable counterarguments, however.

I recognize this has the potential to open a can of worms.

**Comment by scaryghosty** [comment]
1. I agree with @tsdubose. The quotation marks are semantically useful and also allow the distinguishing of dialogue from regular sentences. That is the most important part of the proposed solution: keeping the quotation marks.

2. `['She wrote:', '"I don't paint anymore.', 'For a while I thought it was just a phase that I'd get over.']` - leave it how it is. The proposed solution would still classify all three as separate sentences and it leaves the integrity of the original text in-tact without adding things that weren't there.

**Comment by cqx931** [comment]
@scaryghosty 
`(\S.+?[.!?]["”]?)(?=\s+|$)`
 I think this would be a better solution to avoid the following cases:
`I had a visit from my "friend" the tax man.`

@dhowe What's your thoughts on the second case?
This will influence our current test cases like this one:
"The boy went fishing.", he said. -> right now considered as one sentence.

**Comment by scaryghosty** [comment]
@cqx931 I agree with your proposed solution... it would not count `"friend"` in your example as the end of a sentence whereas my original proposed solution would have. Your way, you always need a period, exclamation point, or question mark but you there can be an optional quotation mark following. Nice.

**Comment by cqx931** [comment]
@dhowe

**Comment by dhowe** [comment]
sounds good to me -- are there any tests cases that will fail using the proposed solution?

**Comment by cqx931** [comment]
@dhowe This will influence our current test cases like this one:
"The boy went fishing.", he said. -> right now it is considered as one sentence, and the proposed solution will break it to two.

**Comment by dhowe** [comment]
What would the two sentences be?
1. "The boy went fishing."
2. , he said.

**Comment by dhowe** [comment]
>> JOHN: This is one sentence with a sentence as the (transposed) object of the verb "said". (But I've never researched how NLP handles such cases.)

**Comment by dhowe** [comment]
@shadoof currently it is handled as one sentence -- there is a proposal (see above) to split it into two...

**Comment by dhowe** [comment]
My current feeling is to leave this as is -- I don't like the idea of spitting sentences like the above, where we end up with things that are clearly not sentences, e.g., ", he said."

Among other problems I haven't yet imagined, this will cause issues with the Markov models which depend upon our current definition of a sentence

**Comment by cqx931** [comment]
Ok, so I have ignored the second case here and added the test case from this issue to RiTaJS. Please check and close the ticket
