### ISSUE TITLE
rita.getPosTags throws TypeError when encountering "Money" followed by punctuation

### ISSUE THREAD

**Issue by tsdubose** [dhowe/RiTa#501]
I haven't been able to replicate it with any other word or combination. Putting "money" in lower case works, as does removing the punctuation. But any non-word character following the word "Money" throws the TypeError shown below.

Talk about edge cases!

<img width="491" alt="screen shot 2018-03-15 at 9 31 29 am" src="https://user-images.githubusercontent.com/16959078/37466456-2b3f847a-2834-11e8-9c1a-1dade83f8458.png">

**Comment by tsdubose** [comment]
Forgot to note: this is the most recent version running on node.

**Comment by cqx931** [comment]
Sorry about the late response. @tsdubose 
What is the exact combination you tested? I tried 'Money' with a few punctuation but it seems to work correctly.
![image](https://user-images.githubusercontent.com/3056154/42626046-9342a398-85c9-11e8-8d7c-5dd7860094d0.png)

**Comment by tsdubose** [comment]
I had forgotten about this. I just went back and got the same error. Then uninstalled and reinstalled RiTa, and the problem was solved. Maybe my installation was corrupted or recent releases fixed the problem. I haven't worked on this project in some months.
