### ISSUE TITLE
Runkit + npm : Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#508]
The rita part works fine but error message for canvas module
![image](https://user-images.githubusercontent.com/3056154/41501822-f8423fce-71ab-11e8-9c93-372aa9d03b18.png)

**Comment by dhowe** [comment]
I tried to remove the canvas part...

**Comment by cqx931** [comment]
No it is not updated. I think a new version number is needed for it to be updated?

**Comment by dhowe** [comment]
OK. I will update the version # soon and we can retry

**Comment by dhowe** [comment]
Fixed
