### ISSUE TITLE
testRandomNNS fails intermittently

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#521]
This test occasionally fails. One example of the returned NNS was 'turves', which is incorrect. But even 'hooves' fails, which is correct.  ??

```
  test("testRandomNNS", function() {
      for (var i = 0; i < 20; i++) {
        var result = lex.randomWord("nns");
        if (!lex._isPlural(result)) console.log(result);
        ok(lex._isPlural(result), "randomWord nns: " + result);

        //No nn & vbg
        //No -ness, -ism
        var pos = lex._getPosData(result);
        ok(pos.indexOf("vbg") < 0, "randomWord nns: " + result);
        ok(!result.endsWith("ness"), "randomWord nns: " + result);
        ok(!result.endsWith("isms"), "randomWord nns: " + result);
      }
  });
```

![image](https://user-images.githubusercontent.com/737638/42764281-d0a1aafa-8947-11e8-9581-aa1c532fcecf.png)

**Comment by cqx931** [comment]
Yes, it's hard to make this test pass 100% as it try to compare the singular form of a nns to the original nn, and there are edge cases.

This one should comes from the word 'turf'.
Now rita.singular('turves') doesn't return 'turf', but 'turve'

**Comment by dhowe** [comment]
Yes, I've created two new tickets (#522, #523) for failures of pluralization and singularization
