### ISSUE TITLE
Missing videos

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#526]
Page: https://rednoise.org/rita/gallery/VisualGrammars/

http://rednoise.org/video/insertSubway.mp4
http://rednoise.org/video/insertSubway.oga
http://rednoise.org/video/insertGlassElevator_ALL4.mp4
http://rednoise.org/video/insertGlassElevator_ALL4.oga

**Comment by dhowe** [comment]
uploading now

**Comment by cqx931** [comment]
checked
