### ISSUE TITLE
[RiTa.js] Phoneme to word mapping?

### ISSUE THREAD

**Issue by koltclassic** [dhowe/RiTa#530]
I was wondering if there was a way to map from phoneme to the original word. The case that I am encountering is one in which I load phoneme text into an RiMarkov, and then generate text until I find a matching phoneme. Upon finding that match, I am hoping to be able to convert the results into their original words. Thank you for the help!

**Comment by koltclassic** [comment]
I assumed that because all of the phonemes were created from words that were present in the lexicon that there would always be a corresponding word available. This is probably a misunderstanding on my part of what the `nFactor` in RiMarkov actually _is_ . It makes sense that it wouldn't be possible if the n-grams were constructed character-by-character, but it seems like there could be a solution for a word-by-word n-gram mapping.

**Comment by koltclassic** [comment]
Regarding the "arbitrary string length" part: I was trying to say what you wrote, tokens as words 👍 I wonder if the solution to mapping from phoneme => word would require saving the initial word => phoneme mapping, _then_ running the markov process with the phonemes, and then attempting to match the resulting phonemes with the saved values.

Regarding the original question (apologies for the mind-wandering): I was hoping to find the inverse of 
`RiTa.getPhonemes("apple"); // returns -> ae-p-ah-l `,
something like:
`RiTa.getWord("ae-p-ah-l "); // returns -> apple`.

**Comment by dhowe** [comment]
> I wonder if the solution to mapping from phoneme => word would require saving the initial word => phoneme mapping, _then_ running the markov process with the phonemes, and then attempting to match the resulting phonemes with the saved values.

This would certainly solve the original question -- when you load the text, you create a dictionary mapping words to phonemes, and then invert keys and values to go the other way with your output...

**Comment by koltclassic** [comment]
Thank you again for the assistance!
