### ISSUE TITLE
RiMarkov failed to complete after 5000 tries

### ISSUE THREAD

**Issue by alexxcharr** [dhowe/RiTa#531]
hello, i wrote a piece of code to get the content of wikipedia articles and use the RiMarkov on it to generate poems. At first it worked just fine but later on when i tried to clean the content with regex i got this error in the console "RiMarkov failed to complete after 5000 tries and 0 successful generations. You may need to add more text to the model...". The only lines i added are these:
content = content.replace(/\W/g," ");
content = content.replace(/\s\s+/g," ");
and as soon as i comment them out it works just fine. the content i get is the same just without brackets, commas, extra whitespace etc. Any idea what the regex change that may cause this error?

**Comment by dhowe** [comment]
What function are you using to generate ? If you are using generateSentences(), then the input needs to be in the form of sentences. Removing the punctuation makes RiTa unable to detect sentence boundaries, which will cause this failure. 

If you are using a different function, post your code here and I'll take a look...

**Comment by alexxcharr** [comment]
Great! That was it. 
Thank you!
