### ISSUE TITLE
women should be W IH M AH N instead of W OW M EH N

### ISSUE THREAD

**Issue by mflerackers** [dhowe/RiTa#532]
women gives W OW M EH N when you request phonemes, it should be W IH M AH N

**Comment by dhowe** [comment]
what about 'w ih m eh n' ?

**Comment by mflerackers** [comment]
Also OK maybe. CMU gives W IH M AH N, while wiktionary gives W IH M IH N
I think the former is American English, while the latter is British English.

**Comment by dhowe** [comment]
Thanks for these... Feel free to modify [this file](https://github.com/dhowe/RiTaJS/blob/master/src/rita_dict.js) in the future, and submit a PR!
