### ISSUE TITLE
genuine is JH EH N Y UW AH N, not JH EH N IY AH W AH N

### ISSUE THREAD

**Issue by mflerackers** [dhowe/RiTa#533]
genuine should be JH EH N Y UW AH N, not JH EH N IY AH W AH N

**Comment by dhowe** [comment]
Is this preferable to JH EH N Y UW IH N ?

Note: the syllable break was incorrect on this as well, should be: 'jh-eh1-n y-uw w-ah-n' or  'jh-eh1-n y-uw w-ih-n'
