### ISSUE TITLE
Rednoise.org & the documentation are down

### ISSUE THREAD

**Issue by lvdovicb** [dhowe/RiTa#534]
Hi, since the website is down, is there a way to get the RiTa.js documentation ? We've been working with RiTa and it would help us tremendously.

**Comment by dariusk** [comment]
Here, I just made a quick backup: http://tinysubversions.com/rita-docs-backup/RiTa/web/reference/index.php

**Comment by lvdovicb** [comment]
Perfect ! Thanks a lot darius ! It is much appreciated.

**Comment by dhowe** [comment]
I assume this was some sort of temporary network blip or dns issue. But in the future, pls notify me directly if this happens at daniel-at-rednoise-dot-org... thanks
