### ISSUE TITLE
Incorrect rhyming of word "eight" ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#539]
from user

**Comment by dhowe** [comment]
pls add a test for this and report the result here

**Comment by KenLiHK** [comment]
Added "eight" and "weight" into IsRhymeTest.java

![screen shot 2019-02-09 at 6 56 46 pm](https://user-images.githubusercontent.com/24424527/52519863-f2b55080-2c9c-11e9-99f9-1aa27d6f8ed3.png)

And there is StringIndexOutOfboundsException in Junit Test.

![screen shot 2019-02-09 at 7 03 09 pm](https://user-images.githubusercontent.com/24424527/52519897-8d159400-2c9d-11e9-87e4-96a8e7353ea1.png)

**Comment by KenLiHK** [comment]
To solve the StringIndexOutOfboundsException, I think we can add this condition

![screen shot 2019-02-09 at 8 34 40 pm](https://user-images.githubusercontent.com/24424527/52520930-6b6ed980-2caa-11e9-8276-130a69ccd0c4.png)

**Comment by KenLiHK** [comment]
I think we should remove the space between ey1- and t
Update 
'eight':['ey1- t','cd'],
to 
'eight':['ey1-t','cd'],

![screen shot 2019-02-09 at 9 02 01 pm](https://user-images.githubusercontent.com/24424527/52521261-5f394b00-2caf-11e9-8f47-c5a510167c98.png)

**Comment by dhowe** [comment]
If it fixes the test, then please do it (for both rita and ritajs)
