### ISSUE TITLE
Add download banner to website

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#541]
as  below (from: http://graphalchemist.github.io/Alchemy/)
![image](https://user-images.githubusercontent.com/737638/50051114-32513780-0147-11e9-8252-8484309b9ca9.png)

**Comment by cqx931** [comment]
Questions:
1. Is it only for the home page of rita?
2.Do you want to keep the other buttons as well or just the download function?
3.Are we going to remove the current 'fork me on github' banner if we move that to the banner?

I will first do a mockup to confirm the style.

**Comment by dhowe** [comment]
> 1. Is it only for the home page of rita?

yes

> 2. Do you want to keep the other buttons as well or just the download function?

keep all, maybe "I'm coding language with RiTa[link]" for the tweet text

> 3. Are we going to remove the current 'fork me on github' banner if we move that to the banner?

yes, but just from the homepage

**Comment by cqx931** [comment]
Are we going to  remove the download button on homepage?
Which version of RiTa is it going to download for? The complete zip?

**Comment by dhowe** [comment]
> Are we going to remove the download button on homepage?
no

> Which version of RiTa is it going to download? The complete zip?
just link to the download page for now

**Comment by cqx931** [comment]
![image](https://user-images.githubusercontent.com/3056154/50376966-3536a700-05e3-11e9-9648-dce80a115daf.png)
![image](https://user-images.githubusercontent.com/3056154/50376969-38ca2e00-05e3-11e9-8c79-f382719f127e.png)

**Comment by cqx931** [comment]
A brighter background for the banner:
![image](https://user-images.githubusercontent.com/3056154/50377131-bee77400-05e5-11e9-8a6d-c920d145470a.png)

**Comment by dhowe** [comment]
that looks good! -- any reason not to dock it to the edge of the screen?

**Comment by cqx931** [comment]
No particular reason. It stands out more if it is not aligned to the edge, depending on what effect you would like here.

**Comment by tuneum** [comment]
Sounds like a particular reason to me


On Saturday, December 22, 2018, 1:32 PM, cqx931 <notifications@github.com> wrote:


No particular reason. It stands out more if it is not aligned to the edge, depending on what effect you would like here.

**Comment by cqx931** [comment]
can this be closed?
