### ISSUE TITLE
Verify handling of "i.e." and "e.g." in RiTa.tokenize() and RiTa.untokenize()

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#544]
should each be treated as single words in both functions

**Comment by dhowe** [comment]
First, just test to see how they are currently treated (within a single sentence)

**Comment by KenLiHK** [comment]
Testing the following sentences,
"What Does e.g. Mean? e.g. is used to introduce a few examples, not a complete list."
"What Does I.e. Mean? i.e. means in other words."


[INFO] RiTa.version [1.3.86]
Tokeniszd result:
For e.g.: [What, Does, e, ., g, ., Mean, ?, e, ., g, ., is, used, to, introduce, a, few, examples, ,, not, a, complete, list, .]
For i.e.: [What, Does, I., e, ., Mean, ?, i, ., e, ., means, in, other, words, .]

Untokeniszd result:
For e.g.: What Does e. g. Mean? e. g. is used to introduce a few examples, not a complete list.
For i.e.: What Does I. e. Mean? i. e. means in other words.


Both "i.e." and "e.g." are not treated as a single word.

**Comment by KenLiHK** [comment]
Maybe we can add line 42 and update line 43 and 71 as below to fix it, but need to do more testing.


[INFO] RiTa.version [##version##]
Tokeniszd result:
For e.g.: [What, Does, e.g., Mean?, e.g., is, used, to, introduce, a, few, examples, ,, not, a, complete, list, .]
For i.e.: [What, Does, I.e., Mean?, i.e., means, in, other, words, .]

Untokeniszd result:
For e.g.: What Does e.g. Mean? e.g. is used to introduce a few examples, not a complete list.
For i.e.: What Does I.e. Mean? i.e. means in other words.



![rita01](https://user-images.githubusercontent.com/24424527/51422760-6361d380-1bef-11e9-90de-bb3fd888d0cb.png)

**Comment by dhowe** [comment]
For proper English, the capitalization should be as follows:
    For e.g.: What Does e.g. Mean? E.g. is used to introduce a few examples, not a complete list.
    For i.e.: What Does i.e. Mean? I.e. means in other words.

**Comment by KenLiHK** [comment]
For untokenize, my method is not good, I am finding a better way.

[INFO] RiTa.version [##version##]
Sentences before tokeniszed:
For e.g. : What Does e.g. Mean? E.g. is used to introduce a few examples, not a complete list.
For i.e. : What Does i.e. Mean? I.e. means in other words.

Tokeniszed result:
For e.g. : [What, Does, e.g., Mean?, E.g., is, used, to, introduce, a, few, examples, ,, not, a, complete, list, .]
For i.e. : [What, Does, i.e., Mean?, I.e., means, in, other, words, .]

---------------------------------------------------------------------------------------------------------
Array before untokeniszed:
For e.g. : [What, Does, e, ., g, ., Mean, ?, E, ., g, ., is, used, to, introduce, a, few, examples, ,, not, a, complete, list, .]
For i.e. : [What, Does, i, ., e, ., Mean, ?, I, ., e, ., means, in, other, words, .]

Untokeniszed result:
For e.g. : What Does e.g. Mean? E.g. is used to introduce a few examples, not a complete list.
For i.e. : What Does i.e. Mean? I.e. means in other words.



![rita02](https://user-images.githubusercontent.com/24424527/51425907-a33faf80-1c1d-11e9-8f9a-b7e05dddfa11.png)

**Comment by dhowe** [comment]
This is just special casing... not ideal. Let me see if there is something better...

**Comment by KenLiHK** [comment]
Add more test cases for #544.
https://github.com/dhowe/RiTa/pull/548/commits/36dcb6f3e4137f5bd5f0a0a3c49672ed199c9eaf

The above test case for RiTa.untokenize() is not correct, it is no need to cater a space between e.g. and i.e.

**Comment by KenLiHK** [comment]
Updated RitaJS for #544.
https://github.com/dhowe/RiTaJS/pull/99/commits/b4bf6b3f86b27337cf36bb3530d37d95127611a4

Added more test cases for #544 
https://github.com/dhowe/RiTaJS/pull/99/commits/0ab812cc1943ab1ac385e1b77476806f2559af9b
