### ISSUE TITLE
Seeded random in Java

### ISSUE THREAD

**Issue by kabrio** [dhowe/RiTa#552]
Hello,

maybe I am using it wrong but when calling 
`RiTa.randomSeed(someSeed);`
I'd expect randomWord() etc.. to give me the same random words as long as I do not change the seed.
However this is not working for me. Am I using it wrong or is this a bug?

Best,
J

**Comment by dhowe** [comment]
This was indeed a valid bug (thanks for the report). It is fixed in the current dev version and will be in the next release, hopefully in the next day or so.

**Comment by dhowe** [comment]
(fixed in js as well)

**Comment by kabrio** [comment]
Great, thanks!
PS: The first bug I discovered on Github. 🤗

**Comment by dhowe** [comment]
Nice!
