### ISSUE TITLE
Processing HaikuGrammar example - error in <start> rule

### ISSUE THREAD

**Issue by MarconGit** [dhowe/RiTa#555]
If one runs HaikuGrammar.pde and clicks, an array out of bound error is thrown. The reason is that the code expects the generated sentence to contain "% symbols as separators. This can be fixed in haiku.yaml as follows:

The start symbol should be as follows:
 "<start>": ["<5-line> % <7-line> % <5-line>"]
instead of:
  "<start>": ["<5-line>", "<7-line>", "<5-line>"]

**Comment by dhowe** [comment]
Thanks for this -- fix will be included in next build...
