### ISSUE TITLE
New design for website

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#561]
Scrolling style... something like https://nestjs.com/ or the derivative https://rednoise.org/daniel/dialogic/

Release to be timed with release of RiTa v2.0

**Comment by dhowe** [comment]
@kennyviperhk make sure to add the updated API: https://github.com/dhowe/RiTa/issues/568#issuecomment-503512056

**Comment by dhowe** [comment]
Also, @kennyviperhk we need a section called 'New in RiTa v2.0':
* Support for rita-script
* Support for ES6
* Significant performances improvements
* Newly simplified API (API should be linked to the reference page)

**Comment by dhowe** [comment]
status?

**Comment by kennyviperhk** [comment]
pls check rita/web2

> Also, @kennyviperhk we need a section called 'New in RiTa v2.0':
> 
>     * Support for rita-script
> 
>     * Support for ES6
> 
>     * Significant performances improvements
> 
>     * Newly simplified API (API should be linked to the reference page)

will need to update these and #568 next and current status is on rita/web2

**Comment by dhowe** [comment]
Minor issues:

Blue of button should make blue of header:
![image](https://user-images.githubusercontent.com/737638/79311063-76b53900-7f2f-11ea-9d9c-d194ec48e490.png)

**Comment by dhowe** [comment]
Feedback on PR  #561-New-design-for-website
----------------------
- [ ] See comments above (some still not fixed)
- [ ] Add 'Reference' to homepage, API is [here](https://github.com/dhowe/rita-script/issues/8)
- [ ] Is there a reason not to move 'Examples' below as well?
- [ ] Strange URL after clicking top 'download' button: `/RiTa/web2/#[object%20Object]`
- [ ] Reduce space between 'RiTa' and 'a software toolkit for computational literature'
- [ ] Better favicon

**Comment by kennyviperhk** [comment]
Is there a reason not to move 'Examples' below as well?
-it is for readability reason. created a separate branch that has moved to below.

**Comment by dhowe** [comment]
- [ ] I still get a separate page for 'reference'
- [ ] errors in console

![image](https://user-images.githubusercontent.com/737638/80601934-0e06aa00-8a61-11ea-9a85-521b41dfa93e.png)

![image](https://user-images.githubusercontent.com/737638/80601898-00512480-8a61-11ea-99a6-0df9f84ff663.png)

**Comment by kennyviperhk** [comment]
https://github.com/dhowe/RiTa/pull/592

**Comment by dhowe** [comment]
- [ ] reference is old, please use the info linked above ([here](https://github.com/dhowe/RiTaJSv2/issues/8))
- [ ] 'examples' should be different bg color than Quick Start/Tutorials
- [ ] still see errors in console (on chrome at least)

**Comment by kennyviperhk** [comment]
how does one navigate the gallery on mobile (see image 2 below) ?
- swipe left / right

**Comment by dhowe** [comment]
> how does one navigate the gallery on mobile (see image 2 below) ?
> - swipe left / right

ok, but the dots should not overlap the text (as it does in the image above)

**Comment by kennyviperhk** [comment]
fixed

**Comment by dhowe** [comment]
> - [x] broken links in tutorial (please check all links, not including reference)
> - [x] how does one navigate the gallery on mobile (see image 2 below) ?
> - [x] reference is old, please use the info linked above ([here](https://github.com/dhowe/rita2js/blob/master/README.md#rita-v2-api))
> - [x] 'examples' should be added to menu, and different bg color than Quick Start/Tutorials

**Comment by kennyviperhk** [comment]
checked my master and #561 branch both are fine
![Screenshot 2020-05-23 at 1 08 02 PM](https://user-images.githubusercontent.com/4047303/82722140-778f7680-9cf6-11ea-888a-6a50b3086480.png)
![Screenshot 2020-05-23 at 1 07 05 PM](https://user-images.githubusercontent.com/4047303/82722141-7a8a6700-9cf6-11ea-8b21-ba364f5887ef.png)

**Comment by dhowe** [comment]
Looks good

**Comment by dhowe** [comment]
Migrate to separate repo?
