### ISSUE TITLE
"be" conjugated as a gerund returns "being"

### ISSUE THREAD

**Issue by zischwartz** [dhowe/RiTa#565]
[Here's an example of the behavior](https://runkit.com/embed/352ehb8r69br), basically:

```js
let opt = {
     form: RiTa.GERUND,
}
let result = RiTa.conjugate("be", opt)
// returns "bing" instead of "being"
```

Maybe I'm missing something? Looks like there's some special handling for this [hereish](https://github.com/dhowe/RiTa/blob/70e78c717988db2c5a3a94186a29bc6318d67b4f/web/download/rita.js#L3694-L3703).

**Comment by dhowe** [comment]
fixed in e5a42dd
