### ISSUE TITLE
RitaJS: Conflict with BrainJS

### ISSUE THREAD

**Issue by dhruv-tech** [dhowe/RiTa#566]
I fail to understand this, but every time I require Rita in my NodeJS project, it causes BrainJS to crash. Please investigate this.

**Comment by dhowe** [comment]
Need more info to debug this. Can you create/post an [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) for the problem? This is the smallest, simplest program that easily demonstrates the issue. Thanks

**Comment by dhowe** [comment]
closing for lack of follow-up
