### ISSUE TITLE
RiString.replaceWord removes line breaks

### ISSUE THREAD

**Issue by padmalcom** [dhowe/RiTa#567]
Hi, it seems as replaceWord removes all line breaks from a RiString.

`RiString s = new RiString("This is a " + System.lineSeparator() + " test);`
`System.out.println(s); // ok`
`s = s.replaceWord(1, "was");`
`System.out.println(s); // not okay, line breaks are missing`

Can you check on that?

Thanks for your great library by the way!

**Comment by dhowe** [comment]
Thanks for the kind words. Its a bit unclear to me what the correct behavior should be here. Currently the words are divided using the RiTa.tokenize method, which strips things like line breaks. If we keep the line break in the string, then we get this word array [ "This", "is", "a", "\n", "test" ] . Do we expect users to count 'invisible' characters when computing the correct index? Another option might be  "This", "is", "a\n", "test" ], but then there is no way to replace the 'a' without the line break. A final options, which might be the best is to allow the user to pass in a regex via which the string is split, something like / +/ (split on one or more spaces), thus giving them complete control at that point. What do you think?

**Comment by padmalcom** [comment]
Hi Daniel, I'd simply add a second function like replaceWordPreserveLineBreaks() to make the behavior clearer to the developers. I'm with you concerning the question "what is the correct behavior" but I think removing the line breaks in "replaceWord" is not as users would expect it to work.

**Comment by dhowe** [comment]
perhaps a 'preserveLineBreaks' option...

**Comment by padmalcom** [comment]
I like the idea but when you add an obligatory parameter like 'preserveLineBreaks' the function would not be backwards compatible.

**Comment by dhowe** [comment]
Would be an optional parameter of course. But I think that most, if not all, of the RiString methods will be removed in the upcoming version 2.x of the API. You can see (and comment) here: https://github.com/dhowe/RiTa/issues/568.

Meantime the quick/dirty workaround is as follows (using whatever delimiter):

 ```
    RiString s = new RiString("This is a " + System.lineSeparator() + " test");
    s.replaceAll(System.lineSeparator(), "___");
    s.replaceWord(1, "was");
    s.replaceAll("___", System.lineSeparator());
    System.out.println(s); 
```

**Comment by padmalcom** [comment]
Thanks for posting the workaround. Issue can be closed.
