### ISSUE TITLE
Cannot install RiTa library in Processing

### ISSUE THREAD

**Issue by LucianaMarques** [dhowe/RiTa#569]
Hi guys!

I'm trying to install RiTa library in my Processing IDE as mentioned in README.md.

However, it does not seem to find it! Is there any other way to do it?

Thank you,

Luciana

**Comment by LucianaMarques** [comment]
PS: I fixed this manually installing the library! I'm submitting a PR soon with some changes on README.md that I think that would be helpful! :)

**Comment by dhowe** [comment]
@LucianaMarques can you describe what happens when you try with the ProcessingIDE?

**Comment by LucianaMarques** [comment]
@dhowe the IDE simply does not find the library! :(

**Comment by dhowe** [comment]
You are using the 'Add Library' Tool (under menu->Sketch->Import Library) ?

![image](https://user-images.githubusercontent.com/737638/60225440-db928c00-9854-11e9-8204-19a5160f6a94.png)

**Comment by LucianaMarques** [comment]
Yes, I made exactly this path and the IDE still didn't recognize it! It only finds Redis for the libraries starting with an "R".

**Comment by dhowe** [comment]
@cqx931 can u try to recreate this?

**Comment by LucianaMarques** [comment]
Hey guys, any news on this? :)

**Comment by dhowe** [comment]
Hi Eli,
How goes? Any idea why RiTa is no longer showing up in the Processing Library Manager (see below)?
The library.properties file is hosted in the usual place with both capitalisations:
  http://rednoise.org/rita/rita.txt <http://rednoise.org/rita/rita.txt>
  http://rednoise.org/rita/RiTa.txt <http://rednoise.org/rita/RiTa.txt>
thanks!
Daniel 

twitter: @danielchowe

**Comment by dhowe** [comment]
I've confirmed this issue, and looking into it now (see email above) 
I will keep the ticket updated as we get feedback

**Comment by dhowe** [comment]
> hello

**Comment by dhowe** [comment]
Meantime you can install the library manually as follows: 

1. Quit Processing
1. Download [RiTa-Complete](http://rednoise.org/rita/rita.zip) from the [downloads page](http://rednoise.org/rita/download.php)
1. Unzip the downloaded file, and move it to your Processing sketch folders libraries directory
1. Open Processing and it should appear under Sketch->Import Library in the menu:

![image](https://user-images.githubusercontent.com/737638/60773375-aac31a00-a0d2-11e9-965c-16713e806391.png)

**Comment by dhowe** [comment]
Hi Daniel,

It should be back now.

The last time the script ran it got the following error:
Error reading http://rednoise.org/rita/rita.txt
<urlopen error [Errno 111] Connection refused>

--
Elie Zananiri
@prisonerjohn

**Comment by dhowe** [comment]
Thanks Elie
