### ISSUE TITLE
Add Rita.joinSentences to join multiple sentences to a string

### ISSUE THREAD

**Issue by padmalcom** [dhowe/RiTa#570]
Hi, I figured out that it is not trivial, to join sentences to a text since there are a lot of rules to add spaces or not. Maybe this is a nice feature for RiTa 2.0? :-)

**Comment by dhowe** [comment]
Can you include some example inputs/outputs for this function?

**Comment by padmalcom** [comment]
I figured out the title was a bit misleading. What I am looking for is a kind of detokenizer which works as shown in the following examples:
Input 1: "My", "name", "is", "Jonas", ".", "I", "am", "a", "pirate", "."
Output 1: "My name is Jonas. I am a pirate."

Input 2: "She", "said", "she", "was", "mad", "at", "me", ",", "because", "of", "my", "past", "."
Output 2: "She said she was mad at me, because of my past.

**Comment by dhowe** [comment]
[RiTa.untokenize()](https://rednoise.org/rita/reference/RiTa/RiTa.untokenize/) ?

**Comment by padmalcom** [comment]
Shame on me... can be closed.
