### ISSUE TITLE
gallery AnapestGenerator link issue

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/RiTa#584]
refer to PR fixed permission issue and link issue #583, when doing #198-Check/fix-broken-gallery-pages, 

links to AnapestGenerator(RiTa/web/gallery/AnapestGenerator) has problem with the links to all files including html and css. PR #583 was attempt to fix the files to make it work again.

**Comment by dhowe** [comment]
permissions look the same to me as all the other folders:

![image](https://user-images.githubusercontent.com/737638/78951107-7ec24280-7b03-11ea-80dc-581230ee6b9e.png)

**Comment by dhowe** [comment]
what is the actual problem? please post the error you are getting here

**Comment by dhowe** [comment]
index.html not index.htm -- i shouldn't have to spend time on this

![image](https://user-images.githubusercontent.com/737638/78951344-643c9900-7b04-11ea-8dbb-78bfc99c50df.png)

**Comment by dhowe** [comment]
verify and close
