### ISSUE TITLE
NullPointerException when using RiLexicon

### ISSUE THREAD

**Issue by pbouda** [dhowe/RiTa#65]
I get a "RiTaException: rita.RiTaException: java.lang.NullPointerException" when I create an instance of RiLexicon. Here is my code:

```
import rita.*;

void setup() {
  RiString s = new RiString("Hello World!");
  RiLexicon lexicon = new RiLexicon();
}
```
The line with "RiString" works fine, but then the programm breaks. Maybe I am using it wrong, but I tried several examples from the web and couldn't get it working. Probably I missed something...

I work on Mac OSX 10.9.4 with Processing 2.2.1.

**Comment by dhowe** [comment]
Cyrus, please verify this with current RiTa and Processing...

**Comment by CyrusSUEN** [comment]
I cannot reproduce this on Processing 2.2.1 @ OS X 10.10.2
![screen shot 2015-03-04 at 12 49 43 am](https://cloud.githubusercontent.com/assets/2461812/6467357/94b0b1a8-c208-11e4-8385-e9597e86a4dc.png)
