### ISSUE TITLE
Add new projects to gallery page

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#68]
Replace the duplicate projects on this page (http://rednoise.org/rita/projects.html), with those in the list below. Grab title, author, and a nice screen image/screenshot of the appropriate size for each one:

* The Whole Brilliant Enterprise: http://www.popsci.com/article/science/behind-scenes-%E2%80%9C-whole-brilliant-enterprise%E2%80%9D
* http://robclouth.com/uncategorized/harry-potter-and-the-statistically-generated-nonsense/
* SpinState: http://rednoise.org/rita/sketches/spinstate/
* Roulette: http://collection.eliterature.org/2/works/howe_roulette.html 
* No Time Machine: http://turbulence.org/Works/notime/
* open.ended: http://collection.eliterature.org/1/works/howe_kaprinska__open_ended.html
* Automatype: http://rednoise.org/~dhowe/automatype
* Mark Sample's Twitter-Bots: https://twitter.com/samplereality/lists/samplereality-bots (you will need to figure out which of these actually use RiTa

**Comment by CyrusSUEN** [comment]
New projects.html
<a>https://www.dropbox.com/sh/ieasavrzhtzf23j/AACQRzmVT4b7v1lPZR3pSu3Na?dl=0</a>

**Comment by dhowe** [comment]
assigned to dhowe for checking

**Comment by dhowe** [comment]
looks good
