### ISSUE TITLE
Tests: check test coverage against API

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#69]
- Check the list [here](http://rednoise.org/rita/reference) against the JSON function lists for each class in RiTa/docs/json/  (or run rita.docgen.DocGenerator)
- Note any discrepancies here
- Then check each of the corresponding test files (ignore RiText for now) in RiTa/src/rita/test/ to make sure that each function has AT LEAST one test function
- Note any missing tests here

**Comment by dhowe** [comment]
When the above is finished, then we can do the same for the test .js files in RiTaJS/test/

**Comment by CyrusSUEN** [comment]
Difference 

Rita
Rita project has:
````
RiTa.isStopWord()
RiTa.p5Compatible()
RiTa.pauseTimer()
RiTa.start()
RiTa.timer()
````

RiString
Rita project has:
````
split()
````
but missing:
````
replaceLast()
````

RiWordNet
Rita project has:
````
getBaseForm()
````

**Comment by CyrusSUEN** [comment]
check each of the corresponding test files (ignore RiText for now) in RiTa/src/rita/test/ to make sure that each function has AT LEAST one test function:

Rita missing:
RiTa.isStopWord
RiTa.loadString
RiTa.p5Compatible
RiTa.posToWordNet
RiTa.randomItem (many testRandom functions but no one contains the word 'Item')

RiString missing:
equals
insertWord (is named testInsertWordAt())
removeChar (is named testRemoveCharAt())
replaceChar (is named testReplaceCharAt())
ReplaceWord testReplaceWordAt (is named testReplaceWordAt())

RiGrammar missing:
expandWith
load
ready

RiMarkov missing:
ready
sentenceAware
useSmoothing

RiTaEvent missing:
data
isType

RiWordNet missing:
RiWordNet.ADJ
RiWordNet.ADV
RiWordNet.NOUN
RiWordNet.VERB

RiWordNet missing:
getAllVerbGroups
getAnagrams
getBaseForm
getContains
getEndsWith
getRandomWord
getRegexMatch
getSoundsLike
getStartsWith
getWildcardMatch
isIgnoringCompoundWords
isIgnoringUpperCaseWords
iterator
printHypernymTree

**Comment by dhowe** [comment]
I've added several of the missing tests above to #74. First finish listing the missing JS tests here, then write the code for the tests in #74.

**Comment by CyrusSUEN** [comment]
<b>Missing RiTaJS tests (excluding RiText):</b>
Rita
RiTa.randomItem

RiTa.isStopWord
RiTa.p5Compatible    
RiTa.timer
RiTa.stopTimer
RiTa.pauseTimer


RiGrammar
loadFrom (tested in another file?)
ready
reset

Rimarkov
ready
loadFrom
loadTokens

RiLexicon
reload
size

RiwordNet
printHypernymTree
iterator
isVerb
isStem
isNoun
isIgnoringUpperCaseWords
isIgnoringCompoundWords
isAdverb
isAdjective
ignoreUpperCaseWords
ignoreCompoundWords
getWildcardMatch
getVerbGroup
getSynset
getSynonyms
getStems
getStartsWith
getSoundsLike
getSimilar
getSenseIds
getSenseCount
getRegexMatch
getRandomWords
getRandomWord
getRandomExamples
getPos
getNominalizations
getMeronyms
getHyponymTree
getHypernyms
getHolonyms
getGloss
getExamples
getEndsWith
getDistance
getDescription
getDerivedTerms
getCoordinates
getContains
getCommonParents
getCommonParent
getBestPos
getRandomExample
getAntonyms
getAnagrams
getAlsoSees
getAllVerbGroups
getAllSynsets
getAllSynonyms
getAllSimilar
getAllNominalizations
getAllMeronyms
getAllHyponyms
getAllHypernyms
getAllHolonyms
getAllGlosses
getAllExamples
getAllDerivedTerms
getAllCoordinates
getAllAntonyms
getAllAlsoSees
exists
RiWordNet.VERB
RiWordNet.NOUN
RiWordNet.ADV
RiWordNet.ADJ
getBaseForm

**Comment by dhowe** [comment]
Good. I've entered the tests you should write in #74 and #76.
