### ISSUE TITLE
Compare RiGrammar.print() function between RiTa and RiTaJS

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#70]
We need to compare the output of the RiGrammar.print() function in RiTa and RiTaJS.

- Use an example in RiGrammar-tests (.java/.js) to load the same grammar file in RiTa and RiTaJS, then call myGrammar.print() for each.

- Post both outputs here if they are different.

**Comment by erikccoder** [comment]
The differents:
 * the orders
 * the float values in brackets
 * output text format 

```
[INFO] RiTaJS.version [##version##]
RiGrammar-tests.js:16 [TEST] Skipping checkAPI() for RiGrammar
rita.js:3201 ------------------------------
<start>
  '<noun_phrase> <verb_phrase>.' [1]
<noun_phrase>
  '<determiner> <noun>' [1]
<verb_phrase>
  '<verb>' [1]
  '<verb> <noun_phrase>' [.1]
<determiner>
  'a' [.1]
  'the' [1]
<noun>
  'woman' [1]
  'man' [1]
<verb>
  'shoots' [1]------------------------------
```
```
[INFO] RiTa.version [##version##]
[INFO] Loaded 33388(0) lexicon in 271 ms
------------------------------
<verb>
  'shoots' [1.0]
<start>
  '<noun_phrase> <verb_phrase>.' [1.0]
<noun>
  'woman' [1.0]
  'man' [1.0]
<noun_phrase>
  '<determiner> <noun>' [1.0]
<verb_phrase>
  '<verb>' [1.0]
  '<verb> <noun_phrase>' [0.1]
<determiner>
  'the' [1.0]
  'a' [0.1]
------------------------------
```

**Comment by dhowe** [comment]
Good -- can you list the file you used to test these?

**Comment by erikccoder** [comment]
First of all, I tested with the load data from string:"sentenceGrammarJSON" in RiGrammar-tests (.java/.js). 
I re-tested with .loadFrom() using:
* [sentence1.json](https://github.com/dhowe/RiTaJS/blob/master/test/data/sentence1.json)
* [sentence2.json](https://github.com/dhowe/RiTaJS/blob/master/test/data/sentence2.json)
* [sentence1.yaml](https://github.com/dhowe/RiTaJS/blob/master/test/data/sentence1.yaml)

the different are the same.
But in RiTaJS, It shows a warning when load from .json:
```javascript
[Warning] [WARN] YAML parsing failed, trying JSON (rita.js, line 6978)
```
And when loading from .yaml, it just let the browsers(safari & chrome) download the .yaml. no result is printed.

**Comment by dhowe** [comment]
Can you explain this last comment... Are you saying that nothing prints when loading a yaml-file??

**Comment by erikccoder** [comment]
Nothing print out in js version. When I run the test, the .yamk-file will be downloaded instead of loaded. So no callback runs when pass to .liadForm().

**Comment by dhowe** [comment]
This is what I see:

![screen shot 2015-03-13 at 3 29 17 pm](https://cloud.githubusercontent.com/assets/737638/6634595/ca2cef88-c995-11e4-8755-566197d310d9.png)

But perhaps this is a browser setting issue? Anyhow, please include a screenshot of the download prompt that you see...

**Comment by erikccoder** [comment]
loadFrom() json:
![json-cap](https://cloud.githubusercontent.com/assets/1491962/6650108/1c8303f2-ca3c-11e4-876a-d8feae1f96ee.jpg)

loadFrom() yaml:
![yaml-cap](https://cloud.githubusercontent.com/assets/1491962/6650110/42ff9b62-ca3c-11e4-9695-63d0b59319c2.jpg)

tested on Chrome & Safari in Osx

**Comment by erikccoder** [comment]
I can use .yaml in loadFrom() and print it out. 
Sorry this was due to my http-server settings. I use apache and it is now. 
![test2](https://cloud.githubusercontent.com/assets/1491962/6745805/d57c877e-cef7-11e4-9ff0-23276c8a3c44.jpg)
![test3](https://cloud.githubusercontent.com/assets/1491962/6745939/6b4f8f74-cefa-11e4-89f6-8ee69055cffb.jpg)
The differents:
* the orders
* the float values in brackets

**Comment by dhowe** [comment]
close enough
