### ISSUE TITLE
Post instructions on building RiTa from github in eclipse

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#72]
Step by step instructions (no screenshots for now) of how to:
- get current Eclipse for java installed (on OS X)
- get the project imported (from github) and fully setup in Eclipse 
- run the JUnit tests in ant

Post here for me to check, using markdown (.md) format (it should look like the 'Development Setup' instructions at the bottom of [this page](https://github.com/dhowe/RiTaJS))

**Comment by CyrusSUEN** [comment]
1\. Download and install [Eclipse for Java.](https://www.eclipse.org/downloads/?osType=macosx)

2\. In Eclipse's menu select 'File' > 'Import...'

3\. In the Import Window select 'Git' > 'Projects from Git' and press Next.

3\. Select 'Clone URI' > then Next and copy and paste the 'HTTPS clone URL' [https://github.com/dhowe/RiTa.git](https://github.com/dhowe/RiTa.git) from RiTa's Github page to the URI section.

4\. Press Next to proceed with the default master branch and (optionally) configure the project directory in the next page.

5\. Press Next and 'Import as existing projects' to finish importing the project.

6\. In Rita project navigate to 'resources' > 'build.xml' and right click 'Run as' > 'Ant Build' to perform JUnit test.

**Comment by dhowe** [comment]
Ok. You can see my version [here](https://github.com/dhowe/RiTa).
Closing.
