### ISSUE TITLE
EclEmma installation instruction for coverage test 

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#73]
<b>Installation: </b>

Option 1 (recommended): Install from Eclipse Marketplace Client  Drag and drop into a running Eclipse Indigo workspace to install EclEmma
Since Eclipse 3.6 [the Eclipse Marketplace Client](http://marketplace.eclipse.org/marketplace-client-intro) allows direct installation of EclEmma from within Eclipse. Follow the steps below or drag and drop the button above into a running Indigo workspace.

1. From your Eclipse menu select Help → Eclipse Marketplace.

2. Search for "EclEmma".

3. Hit Install for the entry "EclEmma Java Code Coverage".

4. Follow the steps in the installation wizard.

Option 2: Installation from Update Site
The update site for EclEmma is http://update.eclemma.org/. Perform the following steps to install EclEmma from the update site:

1. From your Eclipse menu select Help → Install New Software...

2. In the Install dialog enter http://update.eclemma.org/ at the Work with field.

3. Check the latest EclEmma version and press Next

4. Follow the steps in the installation wizard.

Option 3: Manual Download and Installation
For manual installation please download the latest EclEmma release. Unzip the archive into dropins folder of your Eclipse installation and restart Eclipse:
````
<your eclipse installation>/
+- dropins/
   +- eclemma-x.y.z/
      +- plugins/
      |  +- ...
      +- feature/
         +- ...
````

from [http://www.eclemma.org/installation.html#marketplace](http://www.eclemma.org/installation.html#marketplace)

<b>Usage:</b>
After installation right click on Rita project on Eclipse package Explorer window and then select 'Coverage as' > 'JUnit test'.

**Comment by dhowe** [comment]
good
