### ISSUE TITLE
Add missing RiTa tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#74]
Implement the following missing tests in RiTa (created from results of #69).
Finish #69 before working on this ticket...

RiTa:
RiTa.randomItem(Collection)
RiTa.randomItem(List)
RiTa.randomItem(Object[])

RiString:
equals(String)
equals(Object)

RiTaEvent:
data()
isType()

RiWordNet (low-priority): 
posToWordNet()
getAllVerbGroups()
getRandomWord()

**Comment by CyrusSUEN** [comment]
RiString: // finished and push
equals(String)
equals(Object)

RiTaEvent: // finished and pushed
data()
isType()

------------
RiWordNet (low-priority): 
posToWordNet()
getAllVerbGroups()
getRandomWord()

for the getAllVerbGroups() test
Shall I cmp the result to the this [online database](
http://wordnetweb.princeton.edu/perl/webwn?s=live&sub=Search+WordNet&o2=&o0=&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000000000000000)?

But the main problem is that I can't get RiWordNetTest.java running properly.
It only passed 6/80 JUnit tests and my test cases seem to be never executed.

**Comment by dhowe** [comment]
Have you read a) the [documentation](http://rednoise.org/rita/reference/RiWordNet.html), b) installed WordNet on your machine, and c) set the path in the RiWordNet constructor?

**Comment by CyrusSUEN** [comment]
All done and please verify https://github.com/dhowe/RiTa/pull/94
