### ISSUE TITLE
Create an interactive grammar editor for RiTaJS (html/yaml)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#75]
Allows one to edit, lint, and run a RiTa grammar from a simple html interface.

The interface would have a text-field for the grammar, then buttons for clear, save and lint
as well as for expand(), expandFrom(), and expandWith()

(and perhaps) even a callback function to run on the output of the grammar

**Comment by CyrusSUEN** [comment]
What about using some existing online editor? http://jsbin.com/nejagocuki/1/

**Comment by dhowe** [comment]
let's keep this one on hold...  I'd like you to get confident adding new regex rules for adnauseam that actually work

On June 9, 2015 2:44:09 PM EDT, Cyrus S <notifications@github.com> wrote:
>What about using some existing online editor?
>http://jsbin.com/nejagocuki/1/
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dhowe/RiTa/issues/75#issuecomment-110461187


[mobile]

**Comment by dhowe** [comment]
But once you achieve the above (one or more new regexs for adn that work), feel free to give this a shot. And yes, its fine to use some existing editor code if it is very simple and integrates easily into an html page.

To start , first run the editor in Java and see how it works in RiTa. The nice thing about the Java version is that you can have the editor open while you are running a sketch, and the sketch will reloads the edited grammar when you click 'reload' -- you don't have to start/stop the sketch. 

I think that this should also be possible in JS, but first get the other parts working (see above). As mentioned, it should also be able to do validation of your json/yaml grammar rules (e.g., like http://www.yamllint.com/) when you click the 'lint' button...

As usual, don't get stuck for  more than an hour without asking questions...

**Comment by CyrusSUEN** [comment]
Stumbled upon another JS editor library: https://codemirror.net/

**Comment by dhowe** [comment]
looks fine -- go ahead and use it... 
but remember this is a low-priority ticket, so only need to work on this when everything else is done

**Comment by dhowe** [comment]
on hold for now
