### ISSUE TITLE
Add missing RiTaJS tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#76]
Implement the following missing tests in RiTaJS:

RiTa:
RiTa.randomItem(array)

RiGrammar:
reset()

RiMarkov:
loadTokens()

RiLexicon:
reload()
size()

**Comment by CyrusSUEN** [comment]
> RiGrammar:
> reset()
> 
> RiMarkov:
> loadTokens()
The above two have already been done.

Added the remaining tests here: https://github.com/dhowe/RiTaJS/pull/46
