### ISSUE TITLE
A way for people to donate to development costs...

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#77]
Preferably accepting bitcoin and other common/simple payments methods... Find/document some examples/options  used by other projects...

**Comment by CyrusSUEN** [comment]
USD donation
[Mozilla](https://sendto.mozilla.org): Paypal 
[AdBlock](https://getadblock.com/pay/): Paypal
[Ubuntu](http://www.ubuntu.com/download/desktop/contribute): Paypal
[Linux](https://www.linuxfoundation.org/participate/linux-donate): Paypal

Paypal charges for (2.9% + USD0.3) for each donation
Here is the [Paypal pricing](https://cms.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=merchant%2Fdonations)
![screen shot 2015-03-24 at 12 20 50 pm](https://cloud.githubusercontent.com/assets/2461812/6795740/5317ce7a-d220-11e4-825b-4f3d923d1f03.png)

![screen shot 2015-03-24 at 12 21 10 pm](https://cloud.githubusercontent.com/assets/2461812/6795741/5c1a0e34-d220-11e4-927a-b51471bb8966.png)


Bitcoin donation
[Mozilla]((https://sendto.mozilla.org/page/content/give-bitcoin/))using [Coinbase](https://www.coinbase.com) for donation 
[Linux Mint](http://www.linuxmint.com/donors.php) simply shows its bitcoin wallet address publicly for donation

(Pricing on Coinbase](https://developers.coinbase.com/docs/merchants/pricing)
when cashing out, free for first $1,000,000 in sales; 1% afterwards
Another option I find for is BitPay
(Pricing on BitPay](https://bitpay.com/pricing)
free

**Comment by dhowe** [comment]
Can you check Venmo as well?

**Comment by CyrusSUEN** [comment]
That's easy.
1. sign up for a Coinbase account here: https://www.coinbase.com/signup
2. follow the steps on its website to generate a button
https://developers.coinbase.com/docs/merchants/payment-buttons

**Comment by dhowe** [comment]
Ok, and paypal?

**Comment by CyrusSUEN** [comment]
Paypal:
Follow the steps in [Paypal's webpage](https://www.paypal.com/us/cgi-bin/webscr?cmd=_button-designer&factory_type=donate) to create the button
It's OPTIONAL to use Paypal account's email address for creating a donate button. You can enter any email address to receive the payment.

**Comment by dhowe** [comment]
donate button up. closed for now, thanks.

**Comment by dhowe** [comment]
looks good for bitcoin
