### ISSUE TITLE
Migrate qunit tests to testling or karma

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#78]
Following this: https://ci.testling.com/guide/quick_start

RiTaJS only for now...

**Comment by cqx931** [comment]
Better switch to other tools…
The project seemed to be abandoned and it seemed to make no changes after Github change their web hook settings…
According to what I saw from github…some people moved to Karma and Saucelabs while some others tried Zuul.
In this case, Karma seems to be more reliable so maybe I can move to this tool to continue further...
https://github.com/karma-runner

Reference:
https://github.com/substack/testling/issues/111
https://github.com/substack/testling/issues/88
https://blog.codecentric.de/en/2014/11/testing-javascript-karma-and-saucelabs/

**Comment by dhowe** [comment]
Ok, just keep in mind the objectives:
* to keep the basic format of our tests (tweaks here and there are ok, but no major changes)
* to be able test a number of different browsers from the cmd-line
* to be able to compare outputs between java & javascript tests (so we likely want to be able to output results in TAP or something standard format)
* to be able to easily integrate with some continuous-testing framework (as we do with travis-ci which we are using now)

**Comment by dhowe** [comment]
on hold
