### ISSUE TITLE
Test install instructions for RiTaJS

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#80]
(ritajs on windows && mac/linux)
- on node (from npm): https://www.npmjs.com/package/rita
- on node (from github): https://github.com/dhowe/RiTaJS
- in the browser (standard): https://github.com/dhowe/RiTaJS
- in the browser (with [browserify](http://browserify.org/))
- in the browser (with [bower](http://bower.io/))

**Comment by CyrusSUEN** [comment]
- on node (from npm): https://www.npmjs.com/package/rita
both Windows and Mac has the same error:
[INFO] RiTaJS.version [1.0.85]
[INFO] Testing LibraryStructure
[WARN] No json file at '../../RiTa/docs/json/RiTaEvent.json', or perhaps the JSON is invalid?
[WARN] Skipped checkAPI() test for 'RiTaEvent'
[WARN] No json file at '../../RiTa/docs/json/RiTa.json', or perhaps the JSON is invalid?
[WARN] Skipped checkAPI() test for 'RiTa'
[WARN] No json file at '../../RiTa/docs/json/RiString.json', or perhaps the JSON is invalid?
[WARN] Skipped checkAPI() test for 'RiString'
[WARN] No json file at '../../RiTa/docs/json/RiGrammar.json', or perhaps the JSON is invalid?
[WARN] Skipped checkAPI() test for 'RiGrammar'
[WARN] No json file at '../../RiTa/docs/json/RiMarkov.json', or perhaps the JSON is invalid?
[WARN] Skipped checkAPI() test for 'RiMarkov'
[WARN] No json file at '../../RiTa/docs/json/RiLexicon.json', or perhaps the JSON is invalid?

**Comment by dhowe** [comment]
those are warnings, not errors

**Comment by CyrusSUEN** [comment]
Can't get the browserify to work
```
function hasOwnProperty(obj, prop) {
  return Object.prototype.hasOwnProperty.call(obj, prop);
}

}).call(this,require('_process'),typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
},{"./support/isBuffer":34,"_process":14,"inherits":12}],36:[function(require,module,exports){
var rita = require('rita');
var rs = rita.RiString("The elephant took a bite!");
console.log(rs.features());
```
var rs = rita.RiString("The elephant took a bite!");  - Uncaught TypeError: undefined is not a function

**Comment by dhowe** [comment]
Please retest bower and note results in #83
