### ISSUE TITLE
Create new quickstart tab for RiTa/RiTaJS on website 

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#87]
We need a new tab on the website called 'quickstart'. It should have the following subtopics, each linked to the install instructions (can take these from the various READMEs)

Install (Java)   -------------------------------------------

-- as standalone program (use main)
-- as library in Processing
-- as library in Processing on Android
-- as library in Android (standalone-app)
-- via maven *
-- instructions for RiWordNet *

Install (Javascript) --------------------------------------

-- on node (from npm): https://www.npmjs.com/package/rita
-- on node (from github): https://github.com/dhowe/RiTaJS

--  in the browser (standard): https://github.com/dhowe/RiTaJS
--  in the browser (with browserify)
--  in the browser (with bower)
--  in the browser (with p5.js)
--  in the browser (with ProcessingJS)

**Comment by CyrusSUEN** [comment]
PR here: https://github.com/dhowe/RiTa/pull/90

Missing 2 instructions:
-- in the browser (with browserify)
-- as library in Android (standalone-app)

Because they are not working yet.

**Comment by CyrusSUEN** [comment]
OK. added Android Studio and browserify installation instruction #91 
please verify

**Comment by dhowe** [comment]
added a couple of new items (see list at top)

**Comment by CyrusSUEN** [comment]
> -- instructions for RiWordNet *

added: https://github.com/dhowe/RiTa/pull/99
