### ISSUE TITLE
align(RIGHT) on Android not working

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#88]
On a MotoG running at Android 4.4.4.
Device Resolution: 720x1280

Without the .align(RIGHT) method, the sketch works.

**Comment by dhowe** [comment]
Please note, we are not supporting ANY text-rendering moving forward, so no RiText should ever be used in new examples, and no graphical output from the library.  All examples going forward need to use RiTa for language processing then use the environment's (android, processing, whatever) built-in tools to render the text...

**Comment by CyrusSUEN** [comment]
![screenshot_2015-04-10-22-23-10](https://cloud.githubusercontent.com/assets/2461812/7089896/b14086d6-dfd1-11e4-9f48-bc29af938334.png)
Can RiString or println() be used?

**Comment by dhowe** [comment]
Yes, they can both be used (the latter only in Processing, not straight Java). But it seems it cannot find certain external files (the LTS rules). First try a simpler test: 

```Java
println(RiTa.tokenize("The elephant took a bite!"));
```

**Comment by CyrusSUEN** [comment]
Thank you this one works and I will add it to the Android example

**Comment by dhowe** [comment]
Good. But now we need to solve the problem of the missing resources... So, create a new ticket for the original example (with rs.features())...

Also, for each example you create, make sure to do one in pure java on android, not just in processing...

**Comment by dhowe** [comment]
I think the problem here is due to RiString::line 127

    InputStream is = RiTa.class.getResourceAsStream("rita_lts.js");

**Comment by CyrusSUEN** [comment]
OK. A [new ticket](https://github.com/dhowe/RiTa/issues/95) and closing
