### ISSUE TITLE
LTS rules not found on Android Processing

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#95]
```processing
import rita.*;

RiString rs = new RiString("The elephant took a bite!");
println(rs.features());
```

![](https://cloud.githubusercontent.com/assets/2461812/7089896/b14086d6-dfd1-11e4-9f48-bc29af938334.png)

> I think the problem here is due to RiString::line 127
> 
> InputStream is = RiTa.class.getResourceAsStream("rita_lts.js");

**Comment by dhowe** [comment]
Please figure out how to load an external file as a stream on Android

**Comment by CyrusSUEN** [comment]
To be tested: http://stackoverflow.com/questions/15653771/load-a-file-from-external-storage-to-inputstream

**Comment by dhowe** [comment]
Its not actually from the local file system, it is from within the rita.jar file -- is that clear?

**Comment by CyrusSUEN** [comment]
Modify the code according to [an answer](http://stackoverflow.com/a/2271974/1571343)

```java
  protected void loadLTS() {
    
    InputStream is = RiTa.class.getResourceAsStream(Constants.DEFAULT_LTS);
    try
    {
      if (is == null) {
	URL url = new URL("jar:file:/sdcard/Sketchbook/libraries/RiTa/library/rita.jar!\" + Constants.DEFAULT_LTS);
	is = url.openStream();
	
	if (is == null) {
	  throw new Exception("No LTS rules found");
	}
      }
      loadText(is).close();
    }
    catch (Exception e)
    {
      throw new RiTaException(e);
    }
  }
```
Location of the jar file:
![screenshot_2015-10-05-21-55-34](https://cloud.githubusercontent.com/assets/2461812/10282262/5e1ef778-6bac-11e5-8ace-65418a96b044.png)

Here is the error:
![screenshot_2015-10-05-21-54-03](https://cloud.githubusercontent.com/assets/2461812/10282207/196eed0e-6bac-11e5-97b2-c719a0adcf43.png)

Do you think I should ask the author for help? 
https://github.com/Calsign/APDE

**Comment by dhowe** [comment]
Sure

**Comment by CyrusSUEN** [comment]
OK.

Here are the changes
```java
  protected void loadLTS() {
    
    InputStream is = RiTa.class.getResourceAsStream(Constants.DEFAULT_LTS);
    try
    {
      if (is == null) {
        is = RiTa.class.getClassLoader().getResourceAsStream(Constants.DEFAULT_LTS);
        
        if (is == null)
          throw new Exception("No LTS rules found");
      }
        
      loadText(is).close();
    }
    catch (Exception e)
    {
      throw new RiTaException(e);
    }
  }
```
Result:
![screenshot_2015-10-06-00-24-29](https://cloud.githubusercontent.com/assets/2461812/10286532/b897f4a2-6bc0-11e5-8f46-0cb5139907f5.png)

**Comment by dhowe** [comment]
Make a very simple test: 
* one text file
* one simple java class file (it should attempt to load the txt file as below)
packaged as a processing library in a single jar
test it and when it fails, ask the APDE developer
````java
InputStream is = getClass().getResourceAsStream("textfile.txt");

**Comment by dhowe** [comment]
status??

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by CyrusSUEN** [comment]
No update yet

**Comment by dhowe** [comment]
Status?

**Comment by CyrusSUEN** [comment]
> Status?

I've spent some time testing that. I just cannot get it work.

**Comment by CyrusSUEN** [comment]
I did make a Processing library for testing back then:
![untitled](https://cloud.githubusercontent.com/assets/2461812/14151597/50ee5b6e-f6e1-11e5-8bb3-fa4222c0bfb6.png)
It does not fully work.
![2](https://cloud.githubusercontent.com/assets/2461812/14151693/b647a1c8-f6e1-11e5-9063-e06613db97ff.PNG)

**Comment by dhowe** [comment]
I want you to make the simplest, dumbest Android app that you can, and include one configuration file inside the jar (you can simply put 'hello world' inside the file). All the app should do is read the file and display its contents onscreen. See [this post](http://stackoverflow.com/questions/4548699/load-file-within-a-jar) for how to do it.

**Comment by CyrusSUEN** [comment]
LTS rule not found is not a problem anymore once we switch to [Android mode of Processing](https://github.com/dhowe/RiTa/pull/327/files).

```java
import rita.*;
import java.util.*;

void setup() {

  size(600, 140);
  background(50);
  textSize(20);
  noStroke();

  RiString rs = new RiString("The elephant took a bite!");

  float y = 0;
  Map<String, String> map = rs.features();
  println(map);
  for (Map.Entry<String, String> entry : map.entrySet())
    text(entry.getKey() + "/" + entry.getValue(), 0, y+=20);
}
```
Here is the result on an Android running the above code:
![screenshot_2016-04-20-16-44-47](https://cloud.githubusercontent.com/assets/2461812/14668540/71049b8e-0717-11e6-98e4-5f9b1d768f22.png)

The remaining problem on Android platform is to load WordNet https://github.com/dhowe/RiTa/issues/103.

Closing this one.
