### ISSUE TITLE
Add all examples from readme(s) to quickstart web page (rita/ritajs)

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#96]

**Comment by dhowe** [comment]
Still need better maven instructions, both a) installing as dependency in an existing project -- adding an entry in an existing pom.xml; and b) using maven for development -- including creating eclipse project, fetching source, building (via maven), and running tests (in maven)

**Comment by CyrusSUEN** [comment]
Instruction for RiWordNet on Processing (Android):

1. Download and unzip [RiWordNet 3.1 Database file](http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz) on Android
2. Create and save the sketch named 'RiWordNet' as follow
```processing
importa rita.*;

RiWordNet wordnet = new RiWordNet("wn3.1.dict/dict");
```
3. Accessing the Menu button inside your sketch 
Sketch Properties > Add File > select the database file 
Or manually put the database folder to storage/sdcard0/Sketchbook/RiWordNet/data
4. Run the sketch 

error encountered:
```
Initializing build sequence...
Deleted old build folder
Injected log broadcaster
Detected architecture armeabi-v7a

Packaging resources with AAPT...
Compiling with ECJ...
----------
1. ERROR in /data/data/com.calsignlabs.apde/app_build/src/processing/test/riwordnet/RiWordNet.java (at line 26)
RiWordNet wordnet = new RiWordNet("\\dict");
                    ^^^^^^^^^^^^^^^^^^^^^^^
The constructor RiWordNet(String) is undefined
----------
1 problem (1 error)
Compilation with ECJ failed
```

**Comment by CyrusSUEN** [comment]
Already linked the instruction to use RiWordNet to the reference page in Quickstart page
```
<li><a href="http://rednoise.org/rita/reference/RiWordNet.html" target="_blank">Using rita with wordnet</a></li>
```
https://github.com/dhowe/RiTa/blob/master/www/quickstart/index.html

Do you think we should make another insturction in readme.md detailing how to use that in Eclipse and Processing with example code?

**Comment by dhowe** [comment]
First, we will need to do some more work on WordNet for Android before that is ready -- so please move the stuff above to a separate ticket.

For WordNet in Processing/Java, lets make a separate README.WordNet.md page, and put the full instructions there. Then link to it from quickstart.html

**Comment by CyrusSUEN** [comment]
> For WordNet in Processing/Java, lets make a separate README.WordNet.md page, and put the full instructions there. Then link to it from quickstart.html.

It's done: https://github.com/dhowe/RiTa/pull/104

> We also need the instructions for maven (as detailed above)...

I don't how to do that myself.
All I know is ```$ mvn test``` (but it says all tests are skipped) and ```$ mvn install```

**Comment by dhowe** [comment]
Better read up on Maven then (this is an important Java tool)

**Comment by CyrusSUEN** [comment]
> a) checkout RiTa project from github, b) create/convert to a maven eclipse project

In Eclipse, Import > Projects from Git > Clone URI > https://github.com/dhowe/RiTa.git
In the context menu of RiTa project > Configure > Convert to Maven Project

There will be an error
```
Description	Resource	Path	Location	Type
The method compareTo(RiString) of type RiString must override a superclass method	RiString.java	/RiTa/src/rita	line 881	Java Problem
```

**Comment by dhowe** [comment]
This should be fixed, please retry

**Comment by CyrusSUEN** [comment]
> This should be fixed, please retry

OK. I can now run
* Maven clean
* Maven gernate-sources
* Maven install
* Maven test

from the context menu > Run As

**Comment by dhowe** [comment]
Pull again and verify that maven-test from inside eclipse actually runs all the tests

**Comment by CyrusSUEN** [comment]
I can still run the above options and here is the output if Maven test
```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building RiTa 1.0.92-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rita ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 249 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ rita ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rita ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Cyrus\git\RiTa\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ rita ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ rita ---
[INFO] Surefire report directory: C:\Users\Cyrus\git\RiTa\target\surefire-reports
[INFO] Using configured provider org.apache.maven.surefire.junit4.JUnit4Provider

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running rita.test.RiGrammarTest
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.138 sec - in rita.test.RiGrammarTest
Running rita.test.RiLexiconTest
Tests run: 34, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.112 sec - in rita.test.RiLexiconTest
Running rita.test.RiMarkovTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.774 sec - in rita.test.RiMarkovTest
Running rita.test.RiStringTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in rita.test.RiStringTest
Running rita.test.RiTaEventTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in rita.test.RiTaEventTest
Running rita.test.RiTaTest
Tests run: 59, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 sec - in rita.test.RiTaTest

Results :

Tests run: 186, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.542 s
[INFO] Finished at: 2015-05-23T21:16:56+08:00
[INFO] Final Memory: 8M/155M
[INFO] ------------------------------------------------------------------------
```

**Comment by dhowe** [comment]
nice

**Comment by CyrusSUEN** [comment]
> Can you explain that last comment (about 'Replace With'?)

I think running the Maven options changed the repo a bit so that there was a merge conflict when pulling.

**Comment by CyrusSUEN** [comment]
#### Setting up Rita for Maven in Eclipse from GitHub
1. Install [Eclipse IDE for Java Developers](https://eclipse.org/downloads/) 4.3 or newer
2. In Eclipse, select File > Import... > Projects from Git > Clone URI > https://github.com/dhowe/RiTa.git (or the address of your fork)
3. After that in the context menu of RiTa project > Configure > Convert to Maven Project

Here's the instructions. What do you think?

#### Setting up Rita for Maven in Eclipse from Git Command
1. In Terminal ```$ git clone https://github.com/dhowe/RiTa.git``` (or the address of your fork)
2. Install [Eclipse IDE for Java Developers](https://eclipse.org/downloads/) 4.3 or newer
3. In Eclipse, select File > Import... > Existing Maven Projects, select the RiTa directory from git clone as the Root Directory 

#### Running Maven 
In the context menu of RiTa project select Run As > Maven ...

**Comment by CyrusSUEN** [comment]
added insturctions to README.md
PR here: https://github.com/dhowe/RiTa/pull/109

**Comment by dhowe** [comment]
I"m leaving this open (and the instructions commented-out) for now, until we can run tests in maven

**Comment by dhowe** [comment]
closing
